### ISSUE TITLE
I would like to make an option to use the ANSI colors

### ISSUE THREAD

**Issue by blacksails** [dracula/vim#1]
I checked out the theme and noticed that it uses 256 color approximations. I would like to make an option to use precise colors provided from the 16 ANSI colors. The solarized vim theme does this, and it works really great.

I have made a PR dracula/iterm#2 on the iTerm theme, so that it includes all of the dracula colors within the 16 ANSI colors. If that gets merged I will proceed with improving the vim theme with an option of relying on the 16 ANSI colors.

How does that sound?

**Comment by nesl247** [comment]
I'd be curious to see what the theme would look like. Definitely give it a go.

**Comment by dsifford** [comment]
Closing this due to lack of momentum. If still interested, open a PR for this after #62 lands.
