### ISSUE TITLE
Airline: the specified theme cannot be found

### ISSUE THREAD

**Issue by Lightn1ngStr1ke** [dracula/vim#100]
### What happened

:AirlineTheme dracula says "The specified theme cannot be found"

### What I expected to happen

The dracula vim-airline theme to be applied without issue

### Screenshot

![image](https://user-images.githubusercontent.com/38051123/43975142-af82976e-9caa-11e8-87cb-44291d1e972e.png)
![image](https://user-images.githubusercontent.com/38051123/43975162-bbb2a948-9caa-11e8-807f-f0cc137feb97.png)
![image](https://user-images.githubusercontent.com/38051123/43975174-c089764a-9caa-11e8-8ce7-9a77f983e2b9.png)

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.1 (compiled Jul 21 2018)
- **OS**: Linux earth 4.17.13-gentoo-earth #1 SMP Wed Aug 8 13:07:54 EDT 2018 x86_64 AMD Ryzen 7 2700X Eight-Core Processor AuthenticAMD GNU/Linux
- **Terminal/Terminal Emulator/VTE**: rxvt-unicode, VTE version 0.48.4
- **`TERM` environment variable**: rxvt-unicode-256color

**Comment by benknoble** [comment]
what happens when you do

```
let g:airline_theme = 'dracula'
```

**Comment by dsifford** [comment]
`:AirlineTheme dracula` works for me, so I'm guessing it's an install issue (either outdated or not sourcing correctly in init scripts)

**Comment by Lightn1ngStr1ke** [comment]
@benknoble When I do that, I get the first error shown at startup.

I installed dracula using Vundle. Also occurs when using vim-plug.

@dsifford I'm attempting with pathogen now

**Comment by Lightn1ngStr1ke** [comment]
Same error with pathogen, hmm :thinking:

**Comment by Lightn1ngStr1ke** [comment]
![image](https://user-images.githubusercontent.com/38051123/43975865-fcc8d496-9cac-11e8-94b7-e5c0509b4921.png)
Here's my ~/.vimrc

**Comment by dsifford** [comment]
I'm using vim-plug and there's no issues. 

Can you paste a link to your vimrc?

**Comment by Lightn1ngStr1ke** [comment]
@dsifford https://paste.lightn1ng.space/yovowetari.cs

**Comment by dsifford** [comment]
Is your plugin directory in your runtimepath?

What's the output of `:scriptnames`?

**Comment by Lightn1ngStr1ke** [comment]
@dsifford https://paste.lightn1ng.space/zirowowixo.http

**Comment by dsifford** [comment]
Hm, not sure then. Looks like it's in your runtimepath. Ideas @benknoble?

**Comment by Lightn1ngStr1ke** [comment]
I was able to work around this by installing dracula.vim directly into ~/.vim/colors without using vim-plug, then using vim-airline-themes' version.

**Comment by dsifford** [comment]
That's super strange. Glad you were able to sort it out.
