### ISSUE TITLE
Question about using dracula theme on vim

### ISSUE THREAD

**Issue by zenorocha** [dracula/vim#107]
@KeunwooPark commented on [Thu Aug 09 2018](https://github.com/dracula/dracula-theme/issues/286)

Hi.

I'm trying to use dracula theme with tmux and vim(7.2.1689).
I followed instruction on the webpage. I'm using Vim-plug.

However, the actual result doesn't seem right.
The left shows my sample python code, and the right image shows my vimrc.

![dracula](https://user-images.githubusercontent.com/1640277/43884181-61d8cb42-9bf0-11e8-9ebb-74d5ba7784ef.PNG)

Could anyone tell me what option I should add more on vimrc?

---

@wenindoubt commented on [Wed Aug 15 2018](https://github.com/dracula/dracula-theme/issues/286#issuecomment-413444221)

On the left pane, can you run `:colorscheme` and confirm that it is using dracula?

It's also possible your VIM is unable to find the `dracula.vim` file since Vim-Plug installs the theme to `~/.local/share/nvim/plugged/dracula/colors/dracula.vim`

So basically, try this so your VIM can read your `dracula.vim` color file properly:

`ln -s ~/.local/share/nvim/plugged/dracula/colors/dracula.vim ~/.vim/colors`

---

@KeunwooPark commented on [Sun Aug 19 2018](https://github.com/dracula/dracula-theme/issues/286#issuecomment-414177261)

I ran :colorscheme on the left pane, and it showed that I'm using dracula.

And I don't have 'nvim' directory. I'm using regular vim. 
But I found dracula.vim file in Vim-Plug. 
So I did "ln -s ~/.vim/plugged/dracula/colors/dracula.vim ~/.vim/colors"
But it didn't solve the problem.

---

@fakemonster commented on [Mon Sep 17 2018](https://github.com/dracula/dracula-theme/issues/286#issuecomment-422253036)

try setting your TERM env variable to 256 colors: `export TERM=xterm-256color`. long term you can set that in your .bashrc

---

@KeunwooPark commented on [Tue Sep 18 2018](https://github.com/dracula/dracula-theme/issues/286#issuecomment-422299516)

Thanks for the comment, but your solution did not work too. I added 'export TERM=xterm-256color' in .bashrc and .vimrc is same as the above image. And the output is also the same.

**Comment by dsifford** [comment]
@KeunwooPark check some of the existing issues here that are related to this and see if those can help you resolve your issue. 

If not, chime back and I'll try my best to help. I use tmux as well (which I agree can be frustrating to set up correctly) but just know that it _can_ be done! 🚀 😊

**Comment by benknoble** [comment]
Of note, you shouldn't need to set `t_Co` manually. And it is not considered good practice to set the `TERM` variable yourself--prefer instead to change the terminal emulator settings to emulate the proper terminal (e.g., `xterm-256color`).

You _may_ have to edit `~/.tmux.conf` to include a line like `set -g default-terminal "screen-256color"`, but only do that if you know your tmux/vim/emulator setup supports the configuration (in other words, try it and see).

**Comment by Ruffeng** [comment]
in your tmux.conf
```
set -g default-terminal "xterm256-color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
```

Then in your vimrc
```
" ColorSchema
 let g:dracula_italic = 0
 colorscheme dracula
 highlight Normal ctermbg=None

 if (has("termguicolors"))
   set termguicolors
 endif
```

That did the trick for me

**Comment by dsifford** [comment]
@Ruffeng If you desire to use italic fonts (and assuming you're on macos), you can do so by finding a modified version of the `xterm-256color` or `tmux-256color` terminfo file that has italics defined.

That's what I do on my macbook.

**Comment by Ruffeng** [comment]
@dsifford you are totally right. I guess I didn't change it yet because I don't have the necessity to do it, yet.
Will consider it, though, now you mentioned 👍
