### ISSUE TITLE
texTypeStyle too dark

### ISSUE THREAD

**Issue by fsonner** [dracula/vim#111]
### What happened
The foreground color of commands such as \mathbb in a .tex file is too dark.

### What I expected to happen
Lighter colors.

### Screenshot
![image](https://user-images.githubusercontent.com/12097488/48058448-bb736700-e1b6-11e8-8a47-8dc226511835.png)

### Fix
Remove `hi! link texTypeStyle     DraculaSubtle` from `after/syntax/tex.vim` (added by @dsifford).

**Comment by dsifford** [comment]
That was sort of on purpose just to put the focus on the text itself (in cases of paragraph text). It should only really occur in commands that output formatted text that can be displayed in vim (so `\textbf`, `\textit`, `\underline`, etc).

Happy to take a PR though if you hate it. I added that in a few weeks ago for myself. Happy to concede to the majority.

**Comment by fsonner** [comment]
Another path to resolve this issue is to make the `DraculaSubtle` style a little less subtle.

**Comment by dsifford** [comment]
Open to suggestions/ideas. Feel free to open a PR. 👍
