### ISSUE TITLE
Strange Highlights on Ruby Constants

### ISSUE THREAD

**Issue by fulstop** [dracula/vim#114]
### What happened
Strange highlights on Ruby constants

### What I expected to happen
No highlights on Ruby constants

### Screenshot
<img width="852" alt="screen shot 2018-11-30 at 9 58 13 am" src="https://user-images.githubusercontent.com/3484659/49300051-e20b8180-f486-11e8-83cc-6ba44a76b238.png">

### Machine Info

- **Terminal Vim**:
- **Vim 8.1.550**:
- **OS - Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64**:
- **Terminal.app (MacOS)**:
- **`TERM`= xterm-256color**:

**Comment by dsifford** [comment]
You can fix this by setting `let g:dracula_italic = 0` in your `.vimrc` before loading dracula.

The issue is that your terminal doesn't support italics.

**Comment by fulstop** [comment]
Thanks!
