### ISSUE TITLE
Bad highlighting in some words.

### ISSUE THREAD

**Issue by CristoAMH** [dracula/vim#115]
# Edit:
My terminal doesn't support Italyc

### What happened
Some words are block highlighted in blue and I doubt this should the expected
### What I expected to happen
Should be highlighted without the blue block
### Screenshot
![captura de pantalla 2018-12-16 a las 15 52 38](https://user-images.githubusercontent.com/39212295/50055757-fae48a00-014a-11e9-92f2-99bd0e7d3f85.png)

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: Vim
- **Vim version**: 8.0
- **OS**: MacOS High Sierra
- **Terminal/Terminal Emulator/VTE**: Iterm2(but this happens also with mac terminal and hyper)
- **`TERM` environment variable**: xterm-265color

**Comment by benknoble** [comment]
dracula provides a `g:dracula_italic` as described in the help to control this behavior.
