### ISSUE TITLE
Support Vim 8 terminal status line

### ISSUE THREAD

**Issue by juliansniff** [dracula/vim#118]
### What happened
The vim8 terminal status line is not highlighted by the dracula theme

### What I expected to happen
The vim8 terminal statusline should have been highlighted in colors compatible with the dracula theme

### Screenshot
colorscheme dracula:
![image](https://user-images.githubusercontent.com/6636346/50362144-9e131600-0534-11e9-9972-65c40e717014.png)

### Machine Info
MacOSX

- **Vim type (`vim`/`gvim`/`neovim`)**: gvim
- **Vim version**: 8.1.500
- **OS**: MacOSX
- **Terminal/Terminal Emulator/VTE**: zsh in macvim
- **`TERM` environment variable**: xterm

### Additional Info

FYI Adding
```
call s:h('StatusLineTerm', s:none, s:bglighter, [s:attrs.bold])
call s:h('StatusLineTermNC', s:none, s:bglight)
```
to the `dracula.vim` issue results in the statusline being styled correctly (or at least the same as other statuslines):
![image](https://user-images.githubusercontent.com/6636346/50362417-ad469380-0535-11e9-994e-491890fae653.png)

**Comment by dsifford** [comment]
PRs accepted :+1:
