### ISSUE TITLE
Color scheme doesn't look as expected

### ISSUE THREAD

**Issue by halfo** [dracula/vim#12]
OS: Ubuntu 16.04
This is how it looks like:
![dracula-theme-terminal-screenshot](https://cloud.githubusercontent.com/assets/2076914/17842671/28c76342-6847-11e6-987c-33bd514e851c.png)

**Comment by heinst** [comment]
Not sure what the issue is, looks fine to me. Could you post a picture of what a python file looks like on your machine?

**Comment by halfo** [comment]
Actually, I was expecting it
![dracula-faulty](https://cloud.githubusercontent.com/assets/2076914/17864374/a3062c92-68bf-11e6-8021-babb062150f3.png)

to look like this
![dracula-main](https://cloud.githubusercontent.com/assets/2076914/17864425/dfcd2cb6-68bf-11e6-8598-1c83a7f1d03e.png)

And here is an example of how python code looks like
![dracula-python-sample](https://cloud.githubusercontent.com/assets/2076914/17864458/00ea7f0c-68c0-11e6-8f2c-32fc3da8c4ef.png)

Any kind of help would be much appreciated.
