### ISSUE TITLE
Lightline color scheme not changing

### ISSUE THREAD

**Issue by adityarpillai** [dracula/vim#123]
After installing Dracula in vim via Vundle, it does not change the color scheme of lightline. 

<img width="1123" alt="screen shot 2019-01-17 at 6 48 32 pm" src="https://user-images.githubusercontent.com/29032680/51356494-a9e8ee00-1a88-11e9-811d-945c54df4cbf.png">

Note: the menu at the bottom doesn't follow the Dracula color scheme. 

I have run :PluginInstall after saving the file and sourcing `~/.vimrc`, but there is no effect. 

[Here](https://gist.github.com/adityarpillai/3aca67cae7853cf1f6381f339e7e7abb) is the full `.vimrc`.

Maintainers: @dsifford @benknoble

**Comment by dsifford** [comment]
Plugins need to be added above this line. https://gist.github.com/adityarpillai/3aca67cae7853cf1f6381f339e7e7abb#file-vimrc-L14

Move lines 17 and 19 above that line.

**Comment by adityarpillai** [comment]
Oh shoot, I'm so sorry -- I entirely missed that.

**Comment by adityarpillai** [comment]
Actually, I'm still having the same issue after changing it. @dsifford 

I updated the gist, and restarted `vim` and ran `:PluginInstall`.

**Comment by dsifford** [comment]
Run `:scriptnames` and make sure the path to the lightline directory is listed. If not, your runtime path needs to be fixed.

**Comment by adityarpillai** [comment]
I do get `13: ~/.vim/plugged/lightline.vim/plugin/lightline.vim` and `27: ~/.vim/plugged/vim/autoload/dracula.vim`, but the color still doesn't change.
