### ISSUE TITLE
Completion prompt is colored very similarly to the background with :termguicolors

### ISSUE THREAD

**Issue by AGitBoy** [dracula/vim#124]
This is not a bug, but rather a suggestion.

### What happened
The colouration of the popup menu is very similar to the background of the terminal when in vim's truecolor mode making it hard to distinguish from the background.

### What I expected to happen
I would perfer the popup to be more easily distingishable from the background

### Screenshot
![2019-02-02-140241_1366x768_scrot](https://user-images.githubusercontent.com/30708886/52168168-bb6efe80-26f4-11e9-87c6-74312b25aef8.png)

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.1
- **OS**: GNU/Linux (Fedora 29 Workstation)
- **Terminal/Terminal Emulator/VTE**: Kitty (replicable on other terminals with truecolor support)
- **`TERM` environment variable**: xterm-kitty

**Comment by dsifford** [comment]
I happen to also use a truecolor terminal and my interface looks similar (if not identical) to the one you've provided and I'll say that I actually _prefer_ that the menu background color is only subtly darker than the rest of the editor.

I'll wait for @benknoble to chime in here but for now I'd just recommend that if you want to adjust it to your preferences, you're free to do so in either a fork or in your own init scripts by setting the `PMenu` color to whatever you'd like.

**Comment by benknoble** [comment]
<img width="1147" alt="dracula_autocomplete_background" src="https://user-images.githubusercontent.com/22802209/52168425-53bab280-26f8-11e9-96c3-664859d0e43f.png">

The quality of the image isn't necessarily great (sorry), but this is what the contrast looks like _sans_ `'termguicolors'`. I have never minded it.

As @dsifford mentions, you can customize the `PMenu` color in a fork—or use an autocommand (cf. `:help dracula`):

```vim
augroup dracula_fix
  au!
  au ColorScheme dracula highlight PMenu ...
augroup END
```

**Comment by benknoble** [comment]
@dsifford Should we close as `wontfix`, or do we wait a bit longer?

**Comment by AGitBoy** [comment]
I think that it should be labeled as a `wontfix`
