### ISSUE TITLE
Lightline theme name doesn't match vim colorscheme name

### ISSUE THREAD

**Issue by benallan** [dracula/vim#125]
### What happened
The vim colorscheme name is `dracula`, but the lightline theme is named `Dracula`. This makes it difficult to switch colorschemes programmatically. 

### What I expected to happen
Lightline theme to have the same name as the main vim colorscheme. (I think most of the other colorschemes I've seen work like this.)

However, maybe there are good reasons for the current naming setup that I can't see, such as  legacy compatibility.

- **Vim type (`vim`/`gvim`/`neovim`)**:
- **Vim version**:
- **OS**:
- **Terminal/Terminal Emulator/VTE**:
- **`TERM` environment variable**:

**Comment by benknoble** [comment]
I'll work up a PR to fix this (should be trivial), but it may be considered a "breaking change."

I'm ok with it (I don't use lightline, and it sounds like the right thing to do anyways): even lightline's own documentation uses the spelling `dracula`.

Thoughts @dsifford ?

**Comment by benallan** [comment]
Works great now, thanks a lot!
