### ISSUE TITLE
Black text on a cyan backgroud

### ISSUE THREAD

**Issue by tomphp** [dracula/vim#127]
### What happened

The Dracula the highlighting for types is showing as dark text with a cyan background. 

### What I expected to happen

This feels wrong, possibly it should be cyan text on the normal dark background?

If this is intended, then it's just about bearable for some languages (see C# screenshot below) but not in others (way too much visual noise in the Haskell screenshot below).

- Is this as intended?
- Can I change it/is there a fix?

#### C#
<img width="288" alt="screenshot 2019-02-21 at 23 06 23" src="https://user-images.githubusercontent.com/1959183/53208044-5d677400-362d-11e9-8220-dca428fcd671.png">

#### Haskell
<img width="400" alt="screenshot 2019-02-21 at 23 09 51" src="https://user-images.githubusercontent.com/1959183/53208196-d1a21780-362d-11e9-92f7-763285349df4.png">

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.0 & 8.1
- **OS**: OSX Mojave
- **Terminal/Terminal Emulator/VTE**: iTerm2
- **`TERM` environment variable**: xterm-256color

**Comment by dsifford** [comment]
Your terminal doesn't support italic font.

The fix for you would be to set this before loading the colorscheme:

```vim
let g:dracula_italic = 0
```

**Comment by tomphp** [comment]
Amazing - thanks you @dsifford

**Comment by dsifford** [comment]
No prob.. And just for the record: Your terminal actually _does_ support italics, but your terminfo file does not specify how to render them. I had the same issue on my macbook running iterm2. So if you're really wanting italics, you'd just need to look into how to fix your terminfo file. Stackoverflow has a bunch of answers for how to do that.
