### ISSUE TITLE
Diffs hard to read with cursorline over text

### ISSUE THREAD

**Issue by bdielman** [dracula/vim#130]
### What happened

When diffing files in Vim, changed sections are hard to run under the cursorline.

### What I expected to happen

In other colorschemes, the diff line supersedes the cursorline which makes the text easier to read (example provided with Gruvbox colorscheme).

### Screenshot

![Diff Image](https://user-images.githubusercontent.com/94547/54691802-461b8980-4afa-11e9-9171-dcde45da2b52.jpg)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: MacVim and using Vim in the terminal
- **Vim version**: 8.1.950
- **OS**: MacOS 10.14.3
- **Terminal/Terminal Emulator/VTE**: Terminal.app

**Comment by benknoble** [comment]
That's bizarre... @dsifford @bdielman any ideas what's causing the difference?

**Comment by dsifford** [comment]
I don't use cursorline personally but I can check into this later.

**Comment by dsifford** [comment]
Just looked into this and I can't reproduce this. Is this still happening for you @bdielman?

**Comment by bdielman** [comment]
@dsifford - I can but I'm not sure what could be causing it. I'll try later with the other plugins disabled to see if I can track it down.

**Comment by bdielman** [comment]
Still happening even with my other plugins disabled. Since it's not reproducible I'm cool with closing the issue. 😄
