### ISSUE TITLE
Terminal buffer in airline not using theme colors

### ISSUE THREAD

**Issue by bdielman** [dracula/vim#133]
### What happened

When in `terminal` mode section_c of airline isn't picking up Dracula theme colors, instead it's pulling from the default Dark airline theme included with the plugin.

### What I expected to happen

This section should appear as it does in a regular buffer in `normal` mode.

### Screenshot

![terminal-mode-current](https://user-images.githubusercontent.com/94547/55349661-461b7200-5488-11e9-8b3e-4c2e6dcbed63.jpg)

![terminal-mode-proposed](https://user-images.githubusercontent.com/94547/55349666-49aef900-5488-11e9-97e5-015956a54296.jpg)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: MacVim and using Vim in the terminal
- **Vim version**: 8.1.950
- **OS**: MacOS 10.14.3
- **Terminal/Terminal Emulator/VTE**:  Terminal.app

**Comment by bdielman** [comment]
Here's a [reference to styling of this section](https://github.com/vim-airline/vim-airline-themes/blob/master/autoload/airline/themes/peaksea.vim#L55) in one of their included themes, Peaksea.

**Comment by benknoble** [comment]
Sounds like this would be as simple as extending the dictionaries in the calls in [`./autoload/airline/themes/dracula.vim`](https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim)

**Comment by dsifford** [comment]
How would I be able to test this? Is vim's terminal different than neovim's?

**Comment by dsifford** [comment]
But yeah, @benknoble is correct. You just would have to add an `airline_term` property in one or more of these:

- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L50-L53
- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L59-L62
- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L68-L71
- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L77-L80
- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L86-L89
- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L95-L98
- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L104-L107
- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L113-L116
- https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim#L122-L125

I'd do it myself, but I can't even figure out how to replicate this so it must be a vim-only issue and not affect neovim.

**Comment by bdielman** [comment]
I can try to test these later and let you know what I find.
