### ISSUE TITLE
Feature request: background color for Pmenu (popup menu)

### ISSUE THREAD

**Issue by beefsack** [dracula/vim#14]
In terminal Vim 8, Pmenu background is the same as the editor background, making it hard to read:

![screenshot from 2016-09-15 11-45-56](https://cloud.githubusercontent.com/assets/232322/18535720/19825012-7b3a-11e6-83e2-ecc3cae406fa.png)

I added the following to my .vimrc to make it more readable:

```
color dracula
highlight Pmenu ctermbg=238 gui=bold
```

Which looks like:

![screenshot from 2016-09-15 11-46-24](https://cloud.githubusercontent.com/assets/232322/18535737/35a54290-7b3a-11e6-8fb1-b55d9b94ec7d.png)

It'd be great to have something implemented officially, ideally using a colour closer to Dracula.

**Comment by markwu** [comment]
I just did the same thing, but follow the original dracula theme from PhpStorm, here comes with my customization:

```vim
hi Pmenu ctermfg=NONE ctermbg=236 cterm=NONE guifg=NONE guibg=#64666d gui=NONE
hi PmenuSel ctermfg=NONE ctermbg=24 cterm=NONE guifg=NONE guibg=#204a87 gui=NONE
```

**Comment by zenorocha** [comment]
@BlakeWilliams can we close this one now that #49 was merged?

**Comment by BlakeWilliams** [comment]
I think so 👍

**Comment by beefsack** [comment]
Thanks everyone!

**Comment by sasq64** [comment]
Has this change been reverted? I don't see this nice menu with the latest scheme, and it doesn't look like its in there -- perhaps lost when nicer aliases was created ?

**Comment by dsifford** [comment]
@sasq64 It's in there

![image](https://user-images.githubusercontent.com/5240018/48072655-05eee680-e1ab-11e8-8489-fb7db8e98b60.png)

**Comment by sasq64** [comment]
Hmm for some reason it doesn't work for me, I had to add an explicit Pmenu...

**Comment by dsifford** [comment]
Are you certain you've got the updated plugin? (i.e., if using vim-plug, do you run `:PlugUpdate` regularly?) -- If not, that's likely why.
