### ISSUE TITLE
No colors since cd18ffb

### ISSUE THREAD

**Issue by betseg** [dracula/vim#140]
### What happened
Vim doesn't render the color scheme since the commit cd18ffb. Log of related parts: http://ix.io/1Kiq

### What I expected to happen
Vim to render the color scheme correctly I guess?

### Screenshot
![Grim-Screenshot-2019-05-28_16:06:27](https://user-images.githubusercontent.com/1706369/58480334-d6adc000-8162-11e9-9938-d3faf6411046.png)
![Grim-Screenshot-2019-05-28_16:06:47](https://user-images.githubusercontent.com/1706369/58480335-d6adc000-8162-11e9-89ab-450f554daa10.png)

### Machine Info
```
$ uname -a
Linux betseg 5.1.4-arch1-1-ARCH #1 SMP PREEMPT Wed May 22 08:06:56 UTC 2019 x86_64 GNU/Linux
```

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.1.1186
- **OS**: Arch Linux
- **Terminal/Terminal Emulator/VTE**: kitty
- **`TERM` environment variable**: xterm-kitty

**Comment by dsifford** [comment]
What's the output of `:scriptnames`... Looks like your vim implementation isn't loading autoloads? What version of vim are you using?

**Comment by betseg** [comment]
Vim version is 8.1.1186 and the output is:
```
  1: /etc/vimrc
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: ~/.vimrc
  4: /usr/share/vim/vim81/filetype.vim
  5: /usr/share/vim/vimfiles/ftdetect/augeas.vim
  6: /usr/share/vim/vimfiles/ftdetect/meson.vim
  7: /usr/share/vim/vim81/ftplugin.vim
  8: /usr/share/vim/vim81/indent.vim
  9: /usr/share/vim/vim81/syntax/syntax.vim
 10: /usr/share/vim/vim81/syntax/synload.vim
 11: /usr/share/vim/vim81/syntax/syncolor.vim
 12: ~/.vim/pack/syntax/start/vim/colors/dracula.vim
 13: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
 14: /usr/share/vim/vim81/plugin/gzip.vim
 15: /usr/share/vim/vim81/plugin/logiPat.vim
 16: /usr/share/vim/vim81/plugin/manpager.vim
 17: /usr/share/vim/vim81/plugin/matchparen.vim
 18: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 19: /usr/share/vim/vim81/plugin/rrhelper.vim
 20: /usr/share/vim/vim81/plugin/spellfile.vim
 21: /usr/share/vim/vim81/plugin/tarPlugin.vim
 22: /usr/share/vim/vim81/plugin/tohtml.vim
 23: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 24: /usr/share/vim/vim81/plugin/zipPlugin.vim
 25: ~/.vim/pack/dcrpc/start/vim-dcrpc/plugin/dcrpc.vim
 26: ~/.vim/pack/hypertext/start/emmet-vim/plugin/emmet.vim
 27: ~/.vim/pack/line/start/tmuxline.vim/plugin/tmuxline.vim
 28: ~/.vim/pack/line/start/vim-airline/plugin/airline.vim
 29: ~/.vim/pack/line/start/vim-airline/autoload/airline/init.vim
 30: ~/.vim/pack/line/start/vim-airline/autoload/airline/parts.vim
 31: ~/.vim/pack/line/start/vim-airline/autoload/airline/util.vim
 32: ~/.vim/pack/misc/start/ale/plugin/ale.vim
 33: ~/.vim/pack/misc/start/ale/autoload/ale/events.vim
 34: ~/.vim/pack/misc/start/supertab/plugin/supertab.vim
 35: ~/.vim/pack/misc/start/vim-gitgutter/plugin/gitgutter.vim
 36: ~/.vim/pack/misc/start/vim-gitgutter/autoload/gitgutter/utility.vim
 37: ~/.vim/pack/misc/start/vim-gitgutter/autoload/gitgutter/highlight.vim
 38: ~/.vim/pack/spaces/start/vim-better-whitespace/plugin/better-whitespace.vim
 39: ~/.vim/pack/syntax/start/rust.vim/plugin/cargo.vim
 40: ~/.vim/pack/syntax/start/rust.vim/plugin/rust.vim
 41: ~/.vim/pack/syntax/start/rust.vim/ftdetect/rust.vim
 42: ~/.vim/pack/syntax/start/vim-airline-themes/plugin/airline-themes.vim
 43: ~/.vim/pack/syntax/start/vim/after/plugin/dracula.vim
 44: ~/.vim/pack/syntax/start/vim/autoload/dracula.vim
 45: ~/.vim/pack/spaces/start/indentLine/after/plugin/indentLine.vim
 46: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions.vim
 47: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/quickfix.vim
 48: ~/.vim/pack/line/start/vim-airline/autoload/airline.vim
 49: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/netrw.vim
 50: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/term.vim
 51: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/hunks.vim
 52: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/ale.vim
 53: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/whitespace.vim
 54: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/po.vim
 55: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/wordcount.vim
 56: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tabline.vim
 57: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tabline/autoshow.vim
 58: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tabline/tabs.vim
 59: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tabline/buffers.vim
 60: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tmuxline.vim
 61: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/keymap.vim
 62: ~/.vim/pack/line/start/vim-airline/autoload/airline/section.vim
 63: ~/.vim/pack/line/start/vim-airline/autoload/airline/highlighter.vim
 64: ~/.vim/pack/syntax/start/vim-airline-themes/autoload/airline/themes/dracula.vim
 65: ~/.vim/pack/line/start/vim-airline/autoload/airline/themes.vim
 66: ~/.vim/pack/line/start/tmuxline.vim/autoload/tmuxline/api.vim
 67: ~/.vim/pack/line/start/tmuxline.vim/autoload/tmuxline/util.vim
 68: ~/.vim/pack/line/start/tmuxline.vim/autoload/tmuxline.vim
 69: ~/.vim/pack/line/start/tmuxline.vim/autoload/tmuxline/builder.vim
 70: ~/.vim/pack/line/start/vim-airline/autoload/airline/builder.vim
 71: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/default.vim
 72: ~/.vim/pack/misc/start/ale/autoload/ale.vim
 73: ~/.vim/pack/misc/start/vim-gitgutter/autoload/gitgutter.vim
 74: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
 75: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tabline/builder.vim
 76: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tabline/buflist.vim
 77: ~/.vim/pack/line/start/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim
 78: ~/.vim/pack/misc/start/vim-gitgutter/autoload/gitgutter/hunk.vim
 79: ~/.vim/pack/misc/start/ale/autoload/ale/engine.vim
 80: ~/.vim/pack/misc/start/ale/autoload/ale/statusline.vim
```

**Comment by dsifford** [comment]
Yep, I have no idea...

![image](https://user-images.githubusercontent.com/5240018/58495038-7e67c580-8144-11e9-8e0c-c2ac7a5caff2.png)

That's being loaded and `g:dracula#palette` is clearly defined here...

https://github.com/dracula/vim/blob/cd18ffb1fb2f796fd769c7c00d775500f4fdac31/autoload/dracula.vim#L1-L6

Ping: @benknoble -- thoughts?

**Comment by dsifford** [comment]
One thing I will mention though that seems odd is how your runtime paths are set up...

You've got nested directories that aren't standard at the root level of your package paths.

I'm not a native package manager user so maybe that's normal, but that looks strange to me.

**Comment by dsifford** [comment]
Aha... I think I see the issue.

Rename the directory that contains this repo from `vim` to `dracula` and see if that works.

**Comment by betseg** [comment]
Nope, doesn't fix the issue.

**Comment by dsifford** [comment]
Darn. No idea then. I'll wait to hear back from someone else on this. I use neovim and I can't reproduce this.

**Comment by betseg** [comment]
Oh, I think the problem is that Vim is trying to load `~/.vim/pack/syntax/start/vim/colors/dracula.vim` (which has references to `g:dracula#palette` etc) before `~/.vim/pack/syntax/start/vim/after/plugin/dracula.vim` (which has the definitions). I have no idea how to fix it though.

**Comment by dsifford** [comment]
That shouldn't matter (and it's actually expected) since `g:dracula#palette` is an autoloaded variable.

**Comment by betseg** [comment]
I think it does matter, because I changed my .vimrc to a different color scheme and *then* when I'm in Vim i did `:colorscheme dracula` and it loaded without a problem.

**Comment by dsifford** [comment]
That's an error with your vim implementation then. The purpose of autoloads are to load on demand when needed.

See `: autoload`

**Comment by betseg** [comment]
OK, I got the latest version of Vim (8.1.1413) and compiled it from the source, and I still have the same problem.

**Comment by benknoble** [comment]
Here's what I've been able to identify so far as a user of vim's native packages:

Prior to packages loading (?? maybe... certainly prior to `colorscheme dracula`), my runtime path is

```
/Users/Knoble/.vim
/usr/local/share/vim/vimfiles
/usr/local/share/vim/vim81
/usr/local/share/vim/vim81/pack/dist/opt/matchit
/usr/local/share/vim/vimfiles/after
/Users/Knoble/.vim/after
```

Once packages have loaded:

```
/Users/Knoble/.vim
/Users/Knoble/.vim/pack/utility/start/vader
/Users/Knoble/.vim/pack/utility/start/unimpaired
/Users/Knoble/.vim/pack/utility/start/undotree
/Users/Knoble/.vim/pack/utility/start/tbone
/Users/Knoble/.vim/pack/utility/start/surround
/Users/Knoble/.vim/pack/utility/start/splitjoin
/Users/Knoble/.vim/pack/utility/start/rhubarb
/Users/Knoble/.vim/pack/utility/start/repeat
/Users/Knoble/.vim/pack/utility/start/projectionist
/Users/Knoble/.vim/pack/utility/start/presenting
/Users/Knoble/.vim/pack/utility/start/obsession
/Users/Knoble/.vim/pack/utility/start/indent-object
/Users/Knoble/.vim/pack/utility/start/heroku
/Users/Knoble/.vim/pack/utility/start/fugitive
/Users/Knoble/.vim/pack/utility/start/eunuch
/Users/Knoble/.vim/pack/utility/start/endwise
/Users/Knoble/.vim/pack/utility/start/dispatch
/Users/Knoble/.vim/pack/utility/start/commentary
/Users/Knoble/.vim/pack/utility/start/clam
/Users/Knoble/.vim/pack/utility/start/apathy
/Users/Knoble/.vim/pack/utility/start/ale
/Users/Knoble/.vim/pack/utility/start/ack
/Users/Knoble/.vim/pack/languages/start/tmux
/Users/Knoble/.vim/pack/languages/start/scala
/Users/Knoble/.vim/pack/languages/start/pydoc
/Users/Knoble/.vim/pack/languages/start/puppet
/Users/Knoble/.vim/pack/languages/start/liquid
/Users/Knoble/.vim/pack/languages/start/js
/Users/Knoble/.vim/pack/languages/start/go
/Users/Knoble/.vim/pack/languages/start/docker
/Users/Knoble/.vim/pack/interface/start/winresizer
/Users/Knoble/.vim/pack/interface/start/startify
/Users/Knoble/.vim/pack/interface/start/colorizer
/Users/Knoble/.vim/pack/games/start/code-break
/Users/Knoble/.vim/pack/colors/start/dracula
/Users/Knoble/.vim/pack/benknoble/start/synstax
/Users/Knoble/.vim/pack/benknoble/start/invader
/Users/Knoble/.vim/pack/benknoble/start/auto-origami
/usr/local/share/vim/vimfiles
/usr/local/share/vim/vim81
/usr/local/share/vim/vim81/pack/dist/opt/matchit
/Users/Knoble/.vim/pack/utility/start/apathy/after
/Users/Knoble/.vim/pack/languages/start/js/after
/Users/Knoble/.vim/pack/colors/start/dracula/after
/usr/local/share/vim/vimfiles/after
/Users/Knoble/.vim/after
```

So clearly, the autoload can't be found because of the package. The relevant help entry states:

> When Vim starts up, after processing your .vimrc, it scans all directories in
'packpath' for plugins under the "pack/*/start" directory.  First all those
directories are added to 'runtimepath'.  Then all the plugins are loaded.
See |packload-two-steps| for how these two steps can be useful.

So, solutions would be (to me)

1. Tell users to `packadd! dracula` before they `colorscheme dracula`
1. Tell users to `au VimEnter * colorscheme dracula` (since then the `colorscheme` call happens after `runtimepath` has been manipulated).
1. Revert the autoload commit (a simpler, and less breaking, change—necessitates re-opening the closed issue and investigating a way around it)

**Comment by dsifford** [comment]
> Tell users to packadd! dracula before they colorscheme dracula

Isn't this what we have been telling people? That same sentiment is true for all other package managers.

**Comment by betseg** [comment]
> Isn't this what we have been telling people?

No? It works if I add it, btw.

**Comment by dsifford** [comment]
Would you or other users expect the dracula theme and functionality to be available and working prior to loading the dracula theme? That's what I'm not quite wrapping my head around.

How and where do you both recommend this be stated?

**Comment by benknoble** [comment]
I don’t mind going with solution number 1 above, but we need to announce it

- in the docs
- in the ReadMe
- on the website
- in a version number/release?? @dsifford 

And be prepared to close issues as people upgrade. 

The problem is, we haven’t been telling folks this, *and* by some miracle that I still don’t understand, it was working fine before even without `packload!`-ing it.

**Comment by lsrdg** [comment]
Just passing by to say thanks for the great colorscheme and reporting that the same problem just happened on Neovim, right after updating the plugin. It loads smoothly after running `:colorscheme dracula` though.
Out of curiosity, just opened vim and the same problem and the same solution can be found there as well. (:

**Comment by dsifford** [comment]
Do you have a link to your `init.vim` that I can take a look at?

**Comment by benknoble** [comment]
@dsifford with some digging: https://github.com/lsrdg/dotfiles/tree/a66fd9c8f3a3e4bcd19ef66a8573c001d00eec8d

Didn't see anything re: dracula

I'm happy to put together the necessary PRs for https://github.com/dracula/vim/issues/140#issuecomment-497147203

**Comment by dsifford** [comment]
![image](https://user-images.githubusercontent.com/5240018/58738878-a883e680-83d5-11e9-8e10-77b0c19a30af.png)

Yep, same issue.... Red should come _**after**_ blue.

@benknoble Sounds good to me. Thanks!

**Comment by lsrdg** [comment]
@dsifford and @benknoble ,

Sorry, have moved away from github. The `init.vim` file which produces the error is here: https://gitlab.com/lsrdg/dotfiles/blob/master/.config/nvim/init.vim with red after blue. (:

Nvim v0.3.7. Let me know if I can help, and thank you both for maintaining the project. o/

**Comment by dsifford** [comment]
Not sure what to tell ya then. Can't begin to debug something I can't reproduce.

Some might suggest to just revert back to the old commit, however that commit, too, is broken. If you don't load dracula initially as your first color scheme, running `:colorscheme dracula` will result in errors for _all_ vim users.

**Comment by benknoble** [comment]
@lsrdg based on my understanding of `minpac`, it just clones plugins and places them in the packpath. It doesn't actually add them (this is left to happen after `.vimrc` is loaded).

So, the solution is still

```
packadd! dracula
colorscheme dracula
```

**Comment by dmhenry** [comment]
@benknoble 
Proposed solution 1 from https://github.com/dracula/vim/issues/140#issuecomment-496707448 has no effect:
```
packadd! dracula
colorscheme dracula
```
Proposed solution 2 from https://github.com/dracula/vim/issues/140#issuecomment-496707448 does apply the theme, but the very verbose errors are still outputted upon starting Neovim:
```
au VimEnter * colorscheme dracula
```
Manually sourcing the autoload file works:
```
source $HOME/.config/nvim/pack/minpac/start/vim-dracula/autoload/dracula.vim
colorscheme dracula
```
Alternatively, users of minpac can check out the prior commit alluded to in https://github.com/dracula/vim/issues/140 by adding the following to your init.vim or .vimrc:
```
call minpac#add('dracula/vim', {'name': 'vim-dracula', 'rev': 'bfbc3cadbd142e74d3b92e63f1de8711261015a4', 'frozen': 1})
```
The 'rev' entry chooses the commit and the 'frozen' entry will prevent minpac from automatically updating the plugin upon calling `minpac#update()` Obviously this isn't a great long-term solution, but it's the solution I have chosen for now.

**Comment by benknoble** [comment]
Above should use `'name': 'dracula'` as for vim-plug to help autoload find the correct path.

**Comment by dmhenry** [comment]
Also, https://github.com/dracula/vim/issues/143#issuecomment-500546548.

**Comment by digitallyelite** [comment]
I realize this issue is closed, but I have this issue...

I've tried with pathogen (although my .vim isn't a git repository so the instructions are somewhat off there) 
```
cd ~/.vim
git submodule add git@github.com:dracula/vim.git bundle/dracula-theme
```
Because I'm not using git for my .vim directory, I tried doing
`git clone https://github.com/dracula/vim.git bundle/dracula-theme` instead

This throws an error of 
```
Error detected while processing /user/.vimrc:
line 12:
E185: Cannot find color scheme 'dracula'
Press ENTER or type command to continue
```
Line 11 and 12 of my .vimrc are
```
syntax on
color dracula
```
Which actually coincides with the manual instructions on the website...

```
If you aren't so clever just move the dracula.vim file into ~/.vim/colors and add the following lines into your vimrc file:

syntax on
color dracula
```

But, if I just move the dracula.vim file to ~/.vim/colors.... then I get the same output of the first screenshot in the original bug as output....

**Comment by benknoble** [comment]
@digitallyelite it looks like the site instructions have not yet been updated. Can you try the recommendations in the README?

**Comment by digitallyelite** [comment]
@benknoble thanks for that - `set runtimepath^=~/.vim/bundle/dracula-theme`  seems to do the trick.  does this mean it's no longer possible to simply copy the .vim file into colors?

**Comment by benknoble** [comment]
@digitallyelite there is now more than one `.vim` file, as there has been for a while. But yes, we need dracula on the runtime path for the autoload functionality to work. Pathogen users may need to set the runtimepath, or try the `autocmd VimEnter * colorscheme dracula` approach from this thread.

**Comment by benknoble** [comment]
Just an update for anyone that cares: if you place `colorscheme dracula` in `~/.vim/plugin/somefile.vim`, by the time it runs, packages have already been added to the runtime path. Things will work just fine.
