### ISSUE TITLE
Vim no highlights for Tcl variables while setting or evaluating

### ISSUE THREAD

**Issue by madhurkashyap** [dracula/vim#141]
### What happened
I have setup dracula for vim and gvim as per the guidelines. While editing Tcl code I do not see a distinct color for variables while they are set (set var value) or evaluated (puts $var). 

### What I expected to happen
I expected them to have a reasonably distinct bright color. It seems they are not getting highlighted at all.

### Screenshot
![image](https://user-images.githubusercontent.com/27656264/58743255-b7a57b80-844b-11e9-9251-45258c9577cf.png)

### Machine Info
Linux vl-madhurk-gridsdca 3.0.101-108.84-default #1 SMP Fri Nov 30 15:57:27 UTC 2018 (7a72692) x86_64 x86_64 x86_64 GNU/Linux

- **Vim type (`vim`/`gvim`/`neovim`)**: vim and gvim
- **Vim version**: 7.2.108
- **OS**: SLES11
- **Terminal/Terminal Emulator/VTE**: gnome-terminal 2.28.2
- **`TERM` environment variable**: xterm-256color

**Comment by madhurkashyap** [comment]
Please close the issue as I could make it work by: (a) Downloading latest tcl syntax file (b) adding an after routine to highlight specific things I need.

**Comment by benknoble** [comment]
@madhurkashyap glad you solved your issue!

Would you mind adding a link to the

> latest tcl syntax file

you mentioned? Could also add the code you used in your

> after routine

It would help future users if the solution were here in full.

**Comment by madhurkashyap** [comment]
Sure Ben.

Latest tcl syntax file can be obtained from [vim official site](https://www.vim.org/scripts/script.php?script_id=1603).

In the after routine I updated few lines of code

`
if dracula#should_abort('tcl')
    finish
endif

hi! link tclVariable              DraculaCyan
`
