### ISSUE TITLE
Concealed characters are unreadable

### ISSUE THREAD

**Issue by benknoble** [dracula/vim#144]
### What happened

I am writing a large latex document, and wanted to experiment with the conceal capacity of the shipped-with-vim tex plugins. I `:set conceallevel=2`.

Unfortunately the characters are very difficult to read.

### What I expected to happen

The characters should be clear and visible.

### Screenshot

<img width="1280" alt="Capture d’écran 2019-06-15 à 16 28 54" src="https://user-images.githubusercontent.com/22802209/59556095-00504f00-8f8b-11e9-98eb-a7c007a0a00e.png">

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: `vim`
- **Vim version**:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  4 2019 17:18:47)
Version macOS
Patches included : 1-1450
```
- **OS**: macOS
- **Terminal/Terminal Emulator/VTE**: Terminal.app
- **`TERM` environment variable**: `screen-256color`

### Additional Info

Tmux is being used but not relevant here.

**Comment by dsifford** [comment]
Suggestions?

**Comment by benknoble** [comment]
The only thing I experimented with was to `:hi clear Conceal` which was *mostly* fine because it looks like regular text... but I could understanding preferring it to be somewhat distinct.

**Comment by dsifford** [comment]
Yeah I'm torn. I was the one who made it like it is currently, but I don't use conceal really at all so I'll leave you to decide. 

My thoughts mirror yours Re: it should be something that is clearly distinct enough to let the user know the text has collapsed, but not so distinct that it becomes a distraction.

**Comment by benknoble** [comment]
I'm not a heavy user of it either, but I can play around and find something reasonable.

**Comment by OfficialOxide** [comment]
Hi, was there any resolution to this?

**Comment by benknoble** [comment]
@OfficialOxide I stopped messing around with it, since conceal is not really part of my workflow.

I'd welcome suggestions/screenshots of attempts

**Comment by OfficialOxide** [comment]
In this line:
https://github.com/dracula/vim/blob/86712dc2de083e91a78bddddbb7fe7defe818c79/colors/dracula.vim#L248
I changed it to:
`call s:h('Conceal', s:cyan, s:none)`
Which gave the following result:
![attempt](https://user-images.githubusercontent.com/8658852/66148549-cafd6900-e62e-11e9-888f-27fcbadea261.png)
which looks alright to me.

**Comment by benknoble** [comment]
I kind of like this. @dsifford thoughts?

**Comment by dsifford** [comment]
If that works for you guys, I'm fine with it. I don't use conceal chars really so it doesn't matter to me. If someone else has a problem with it, we can discuss more then, but until then LGTM.

**Comment by benknoble** [comment]
Just wanted to comment and say thanks @OfficialOxide for suggesting this; I recently add a lot of conceal to SML files, and this blue is beautiful!
