### ISSUE TITLE
Colors not working

### ISSUE THREAD

**Issue by Groude** [dracula/vim#145]
### What happened
Colors not working fully:
![image](https://user-images.githubusercontent.com/5012405/59961884-f5e00900-94e6-11e9-8d47-b1bc54feab1c.png)

### What I expected to happen
To be the same as on screenshot preview

### Screenshot
`.vimrc`
![image](https://user-images.githubusercontent.com/5012405/59961909-4fe0ce80-94e7-11e9-97bb-51087e24662c.png)

Also tried setting:
`syntax enable, colorscheme dracula` didn't fix 

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.1.1550
- **OS**: macOS Mojave 10.14.5
- **Terminal/Terminal Emulator/VTE**: Terminal (iTerm2 Build 3.3.20190523-nightly)
- **`TERM` environment variable**: xterm-256color

### Additional Info

What I'am doing wrong?

**Comment by dsifford** [comment]
Unless I'm missing something, it looks like it's working fine. 

You probably are just not happy with the default JavaScript syntax, in which case I'd point you to https://github.com/pangloss/vim-javascript

**Comment by Groude** [comment]
@dsifford I thought when I applied colorscheme I would get the same view as on preview screenshot.

So to get all syntax highlighting, I need to install `vim-javascript`?

@dsifford Thanks!

**Comment by dsifford** [comment]
Correct. The two screenshots are two different languages which use two different syntaxes. 

Some of the built-in syntaxes are quite bad (javascript is one of those) so to get better highlighting, you'll have to install 3rd party syntaxes.
