### ISSUE TITLE
Ruby syntax highlighting broken in VIM 8.1

### ISSUE THREAD

**Issue by marko-avlijas** [dracula/vim#146]
Syntax highlighting is broken for ruby on my vim. It only recognizes strings and private keyword. Everything else is white (except line numbers). 

![image](https://user-images.githubusercontent.com/8687315/50449650-e6617800-0928-11e9-9bb8-8a9e21ceb52c.png)

My platform is linux mint 18.3 Cinnamon desktop.
All other themes work for ruby.

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 24 2018 22:39:34)
Included patches: 1-22
Huge version with GTK2 GUI.  Features included (+) or not (-):

**Comment by dsifford** [comment]
Still having this issue?

**Comment by benknoble** [comment]
pinging @marko-avlijas

**Comment by marko-avlijas** [comment]
Back. Yes issue is still here.

**Comment by benknoble** [comment]
@marko-avlijas Can you verify `:set ft? syntax?` gives the appropriate values? What is the output of the `:filetype` command? Have you checked `:color` output? Can you dump `:verbose hi` somewhere? What version of dracula are you using?

Have you tried tpope's rails plugin?

**Comment by marko-avlijas** [comment]
ft and syntax are both ruby.
filetype detection:ON  plugin:ON  indent:ON 
color: dracula

Paste of `:verbose hi`: https://pastebin.com/VwWgqvLA

I didnt try tpope's rails plugin, only his vim-surround. Is it good?

```
head /home/marko/src/vim/runtime/syntax/dracula.vim
" Vim syntax file
" Language:	Dracula
" Maintainer:	Scott Bordelon <slb@artisan.com>
" Last change:  Wed Apr 25 18:50:01 PDT 2001
" Extensions:   drac.*,*.drac,*.drc,*.lvs,*.lpe
" Comment:      Dracula is an industry-standard language created by CADENCE (a
"		company specializing in Electronics Design Automation), for
"		the purposes of Design Rule Checking, Layout vs. Schematic
"		verification, and Layout Parameter Extraction.
```

I was surprised to find that file there. I installed dracula using vundle and most plugins are in `~/.vim/bundle`, but dracula isn't. This is only file named dracula in my home folder, maybe this is part of reason for the issue? Also I don't know what is PDT 2001, but that doesn't sound right as date of last change.

**Comment by dsifford** [comment]
That is 100% the wrong Dracula plugin.

**Comment by benknoble** [comment]
@marko-avlijas as mentioned, that's a syntax file for some kind of special language. It is not a colorscheme. (`PDT 2001` is Pacific Daylight Time from 2001, so it's part of the timestamp.)

Recommended: Install the dracula that you want as a colorscheme (i.e. this repo). Not sure how to do it with vundle, though draculatheme.com/vim suggests 

```
Plugin 'dracula/vim'
:PluginInstall
```

I'm not 100% sure if this will work, but it should. Let us know if you have issues.
