### ISSUE TITLE
Cursorcolumn color is dark/different from cursorline

### ISSUE THREAD

**Issue by RicherMans** [dracula/vim#147]
### What happened

Cursorcolumn color is different from cursorline.
Cursorline is usually a whiteish color, but cursorcolumn is a somewhat dark color. 

I use KDE with konsole as my terminal, but also tried xterm and uxterm, both have the same result.

### What I expected to happen

Both colors should be the same (I guess?)

### Screenshot

With cursorcolumn on:

![Screenshot_20190710_101102](https://user-images.githubusercontent.com/3957278/60935028-0839af80-a2fb-11e9-82ab-e6c24810d010.png)

Without: 
![Screenshot_20190710_101213](https://user-images.githubusercontent.com/3957278/60935076-34edc700-a2fb-11e9-8c50-5b65cb14d03d.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: `neovim`
- **Vim version**: `0.3.8`
- **OS**: `4.19.56-1-MANJARO #1 SMP PREEMPT Wed Jun 26 03:35:21 UTC 2019 x86_64 GNU/Linux`
- **Terminal/Terminal Emulator/VTE**: `konsole`
- **`TERM` environment variable**: `xterm-256color`

**Comment by benknoble** [comment]
I've stopped using cursorcolumn, but I remember and have verified the behavior you are seeing. Looks like a bit of copy-pasta; I will submit a PR shortly.

**Comment by dsifford** [comment]
I did this on purpose since I liked the distinction between the two. 

That said, I literally never use cursorcolumn, so it won't bother me to change.
