### ISSUE TITLE
airline theme error

### ISSUE THREAD

**Issue by CNMan** [dracula/vim#15]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
same as https://github.com/sosz/vim-darcula-theme/issues/1

**Comment by CNMan** [comment]
```vim
colorscheme darcula
let g:airline_theme='darcula'
```

```vim
Could not resolve airline theme "darcula".Themes have been migrated to github.com/vim-airline/vim-airline-themes.
```
![2016-09-16_183456](https://cloud.githubusercontent.com/assets/8692234/18583358/bb4ccc9e-7c3c-11e6-9255-58a50ac4f90a.png)

**Comment by offa** [comment]
> colorscheme darcula
> let g:airline_theme='darcula'

There's a typo in your setting, it's **`dracula`** not `darcula`. 

```viml
colorscheme dracula
let g:airline_theme='dracula'
```

Will solve it.
