### ISSUE TITLE
Odd highlighting with floating windows in nvim

### ISSUE THREAD

**Issue by ckipp01** [dracula/vim#155]
I can't seem to figure out what is happening here with floating windows. I've tried a bunch of combinations with various settings, no settings, and no plugins etc.

When using a lsp client in nvim, coc.nvim for example, that uses floating windows on hover, you should see something like below.

Example with no theme:
<img width="718" alt="Screenshot 2019-11-24 at 09 18 03" src="https://user-images.githubusercontent.com/13974112/69491932-2f54e000-0e9c-11ea-89c8-377d97989844.png">

As you can see the color in the floating window isn't pretty, but it's consistent. I then tried with Dracula and you get the following:

<img width="744" alt="Screenshot 2019-11-24 at 09 18 52" src="https://user-images.githubusercontent.com/13974112/69491941-4d224500-0e9c-11ea-820c-b18d63012c2e.png">

Not how around the ` : ` the highlighting in the floating window gets all weird. It's not consistent through the window. Just for good measure, I tried it with `termguicolors` and it looks like so:

<img width="744" alt="Screenshot 2019-11-24 at 09 19 37" src="https://user-images.githubusercontent.com/13974112/69491960-8490f180-0e9c-11ea-917e-57134b0aef56.png">

I also just to make sure disabled all syntax related plugins, and here is the result:

<img width="744" alt="Screenshot 2019-11-24 at 09 20 26" src="https://user-images.githubusercontent.com/13974112/69491963-97a3c180-0e9c-11ea-89ba-816f549bf5b1.png">

I normally use Nord theme, but wan't to switch. Here is an example using Nord and it behaving correctly:

<img width="744" alt="Screenshot 2019-11-24 at 09 28 13" src="https://user-images.githubusercontent.com/13974112/69491995-c1f57f00-0e9c-11ea-95e7-cc9b48d176d2.png">

Pinging @dsifford and @benknoble since they are the vim Dracula maintainers. Submitting is this repo as it seems to get a lot more traffic and activity than the vim one.

**Comment by benknoble** [comment]
The popup menu uses `Pmenu` by default, though this is configurable by whatever creates the popup (as a function argument).

It would be helpful to know what code is creating it, so we can see if there is a highlighting group being applied, or if it is relying on the base `Pmenu` (which seems fine...)

**Comment by ckipp01** [comment]
Thanks so much for the quick response! I'll dig into coc.nvim to see where the hover request is being triggered to see if I can point you guys to the relevant snippet where this is being created.

**Comment by ckipp01** [comment]
So if I understand it correctly, this is where the `previewHover` gets the necessary text to display https://github.com/neoclide/coc.nvim/blob/dc888b4a6e1e3c70049c41d1edda06c76b853983/src/handler/index.ts#L1133

**Comment by benknoble** [comment]
@ckipp01 thanks for digging in—I'm not a neovim user, and I don't know it's typescript interface well enough to know what's going on.

I do see this line

```
nvim.command(`setl winhl=Normal:CocFloating,NormalNC:CocFloating,FoldColumn:CocFloating`, true)
```

But `winhl` is not a part of vim that I could find, so I'm not sure what it's doing.

Might just be best to ask coc.nvim if they are highlighting the buffer—then you could do something like

```
augroup popup-fix
  au!
  au ColorScheme dracula hi somegroup ....
augroup END
```
