### ISSUE TITLE
dracula does not work on .vimrc but works with :colorscheme dracula

### ISSUE THREAD

**Issue by cloveistaken** [dracula/vim#161]
### What happened
I recently just installed dracula on Vim 8.1 with by cloning the repo to `~/.vim/pack/default/start/dracula`
However dracula does not load with `colorscheme dracula` in `.vimrc` but manually run `:colorscheme dracula` works fine.
The error message seems to be similar to [this issue](https://github.com/dracula/vim/issues/149).
```
Error detected while processing /home/cloveistaken/.vim/pack/default/start/dracula/colors/dracula.vim:
line   34:
E121: Undefined variable: g:dracula#palette
line   36:
E121: Undefined variable: g:dracula#palette
line   37:
E121: Undefined variable: g:dracula#palette
line   38:
E121: Undefined variable: g:dracula#palette
line   39:
E121: Undefined variable: g:dracula#palette
line   40:
E121: Undefined variable: g:dracula#palette
line   42:
E121: Undefined variable: g:dracula#palette
line   43:
E121: Undefined variable: g:dracula#palette
line   44:
E121: Undefined variable: g:dracula#palette
line   46:
E121: Undefined variable: g:dracula#palette

(... The rest is snipped...)
```

### What I expected to happen
dracula loads normally

### Screenshot
![1](https://user-images.githubusercontent.com/26355224/70404695-2a1a9800-1a3b-11ea-9848-7cf777e7c4cd.png)
![2](https://user-images.githubusercontent.com/26355224/70404724-3c94d180-1a3b-11ea-983d-19dce8ca9530.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
- **OS**: Debian 10.2 (fresh install from non-free live)
- **Terminal/Terminal Emulator/VTE**: MATE-terminal
- **`TERM` environment variable**: xterm-256color

### Additional Info

- `colorscheme gruvbox` in `.vimrc` works fine, same method of installation, I haven't tested with other colorschemes
- Possible steps of replicate:
  + Install Debian 10.2 (non-free+live) and install vim, vim-gtk3, git
  + Install dracula with: `git clone https://github.com/dracula/vim ~/.vim/pack/default/start/dracula`
  + Add `.vimrc`:
    ```
    colorscheme dracula
    syntax on
    ```

**Comment by dsifford** [comment]
I'm not familar with how vim's builtin package manager works behind the scenes, but I believe @benknoble uses that so I'll defer this to him.

**Comment by benknoble** [comment]
This is the classic we saw back in #140 and it's many linked issues.

The several solutions I can suggest, in suggested order:

1. Put `colorscheme dracula` in `~/.vim/plugin/load_plugins.vim`—anything in the plugin directory runs *after* packages have been added to the runtimepath.
2. Try `packadd! dracula | colorscheme dracula` in your vimrc—you need the runtimepath set properly
3. Try `au VimEnter * colorscheme dracula`—try firing the command at the last possible minute.

**Comment by cloveistaken** [comment]
> This is the classic we saw back in #140 and it's many linked issues.
> 
> The several solutions I can suggest, in suggested order:
> 
>     1. Put `colorscheme dracula` in `~/.vim/plugin/load_plugins.vim`—anything in the plugin directory runs _after_ packages have been added to the runtimepath.
> 
>     2. Try `packadd! dracula | colorscheme dracula` in your vimrc—you need the runtimepath set properly
> 
>     3. Try `au VimEnter * colorscheme dracula`—try firing the command at the last possible minute.

All 3 purpose solutions work perfectly. Thanks a lot.
