### ISSUE TITLE
screen in place of tmux

### ISSUE THREAD

**Issue by Bulliby** [dracula/vim#168]
### What happened

I'm facing the same problem that this issues : https://github.com/dracula/vim/issues/114 or https://github.com/dracula/vim/issues/115

### Screenshot
![vim_dracula](https://i.imgur.com/ATDWOVA.png])

### Machine Info

- **Vim type** vim
- **Vim version**: 8.1.2268
- **OS**: Linux IRobot 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux
- **Terminal/Terminal Emulator/VTE**: [alacritty](https://github.com/alacritty/alacritty)
- **`TERM` environment variable**: screen-256color

**Comment by dsifford** [comment]
Your terminal doesn't support italic fonts.

Set `let g:dracula_italic = 0` prior to setting your colorscheme in your vimrc.

**Comment by Bulliby** [comment]
Thx, no i already tried this but when I'm in a screen session the problem persist.

**Comment by dsifford** [comment]
Make sure you call it before setting colorscheme for the first time.

**Comment by Bulliby** [comment]
Yes i answered too fast set it before color scheme fixed the problem. Thanx
