### ISSUE TITLE
Vim + vue files not highlighting javascript?

### ISSUE THREAD

**Issue by Lilja** [dracula/vim#172]
I'm running Vim with a few plugins, more specifically a plugin that fixes a few syntax highlights for .vue files [posva/vim-vue](https://github.com/posva/vim-vue).

When I'm running it with gruvbox I get some highlighting. To the left, a .vue file and to the right is some random babel javascript file.

<img width="1280" alt="bild" src="https://user-images.githubusercontent.com/6134511/76258997-f70fbc80-6254-11ea-8a50-992b9fa4330e.png">

With dracula, not so much.
<img width="1280" alt="bild" src="https://user-images.githubusercontent.com/6134511/76259011-00008e00-6255-11ea-8e85-c6dca17d4cd8.png">

Is there something wrong that I'm doing?
`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 17 2020 07:44:02)`
`silent! let g:plugs['vim'].commit = 'ed490ae'`

**Comment by dsifford** [comment]
@Lilja can you copy a code sample that I can try to this thread?

**Comment by dsifford** [comment]
I tried in a few dozen vue files that I found throughout the web and I can't reproduce the issue in any of them.

**Comment by Lilja** [comment]
Hmm. I cut a lot of stuff from my `vimrc` and I still can replicate it on my own.
<img width="538" alt="bild" src="https://user-images.githubusercontent.com/6134511/76364505-a025e800-6325-11ea-9f9c-c5b87c790a4d.png">

[File that I'm using](https://raw.githubusercontent.com/Lilja/blog/master/pages/index.vue)
Reduced vimrc, using vim-plug as my plugin manager.
```
" ============================== XDG_CONFIG STUFF =====================
set rtp+=$XDG_CONFIG_HOME/vim
set rtp+=$XDG_CACHE_HOME/vim

call plug#begin("$XDG_CACHE_HOME/$VIM_PLUGIN_DIR")

" ============================== Plugins ==============================

" Status bar revamp
" Vue support
Plug 'posva/vim-vue'
" Dracula theme
Plug 'dracula/vim'

call plug#end()

try
    let g:dracula_italic = 0
    colorscheme dracula
catch /^Vim\%((\a\+)\)\=:E185/
    echo 'Color scheme dracula does not exist'
endtry
" Cheat sheet
" Ctrl + W = Resize window splits
"
```

**Comment by dsifford** [comment]
![image](https://user-images.githubusercontent.com/5240018/76414701-3b42b000-636e-11ea-8715-a6549cf67daf.png)

**Comment by dsifford** [comment]
Looks like your terminal doesn't support truecolor, so you might start by trying `let g:dracula_colorterm = 0`.

**Comment by dsifford** [comment]
Also, double check that you're running the latest version of this plugin... (i.e. do a quick `:PlugUpdate`)

**Comment by Lilja** [comment]
I'm running iterm 2, 
```bash
$ echo $TERM
xterm-256color
```

True color looks to be supported?
`curl https://raw.githubusercontent.com/robertknight/konsole/master/tests/color-spaces.pl | perl`
![image](https://user-images.githubusercontent.com/6134511/76415449-845c2980-6399-11ea-95f6-e8f47ef41077.png)

`:PlugUpdate` did not change anything 
![image](https://user-images.githubusercontent.com/6134511/76415676-e583fd00-6399-11ea-821f-7c8f019cbd45.png)
Above screenshot taken with this vimrc
```
" ============================== XDG_CONFIG STUFF =====================
set rtp+=$XDG_CONFIG_HOME/vim
set rtp+=$XDG_CACHE_HOME/vim

call plug#begin("$XDG_CACHE_HOME/$VIM_PLUGIN_DIR")

" ============================== Plugins ==============================

Plug 'posva/vim-vue'
Plug 'dracula/vim'

call plug#end()
" ============================== UI Config ==============================
" Syntax
set termguicolors
syntax on
filetype plugin indent on

" Looks
set background=dark

" Set 256 color support
set t_Co=256

let g:dracula_italic = 0
let g:dracula_colorterm = 0
" Colorscheme
" colorscheme gruvbox
colorscheme dracula
```

**Comment by dsifford** [comment]
Hm.. reason I thought your terminal wasn't truecolor is because the background color of the theme is objectively not correct either.

Not totally sure. Thoughts @benknoble?

**Comment by Lilja** [comment]
Could it matter that i'm running gruvbox as a fish theme?

Truecolors print with no gruvbox 
![image](https://user-images.githubusercontent.com/6134511/76424077-0d7a5d00-63a8-11ea-8c83-81ea38acd8ce.png)

**Comment by dsifford** [comment]
for the background color thing, _maybe_ that could be the issue. However it's still strange that all of your highlight colors are pink in your example. Mine is not at all like that (with or without that vue plugin you mentioned)

**Comment by benknoble** [comment]
It could definitely affect the bg color (esp. if `dracula_color_term` is turned off; IDK why that option is named as is since it has more to do with bg color than actual gui colors).

A couple of things:
1. No need to set `t_Co` if your `xterm-256color` profile has all the right attributes compiled.
2. Dracula should automatically use truecolor or not based on `TERM`, `gui`, `'termguicolors'`, etc.
3. This doesn't look like a gui v. term colors: it looks more like a syntax issue to me. Could @Lilja and @dsifford try grabbing the syntax groups being applied to the parts where they differ? Code to do so can be found in https://github.com/tpope/vim-scriptease and https://github.com/benknoble/vim-synstax, among other places.

**Comment by dsifford** [comment]
@benknoble in my editor, without the vue plugin, everything in (and including) `<template>` is html syntax groups, and everything in `<script>` is javascript.

**Comment by dsifford** [comment]
syntax groups over `asyncData` are `jsObjectFuncName jsObject javaScript`

**Comment by leandrocunha** [comment]
For me is almost perfect with some issues comparing with VS Code. Looking to the image, some properties are not green, some : are no pink, functions parameters are not orange, the "this" is pink instead purple and CSS in the end of document is all orange.

I'm using [Polyglot](https://github.com/sheerun/vim-polyglot) which use [vim-vue](https://github.com/posva/vim-vue) under the hood

<img width="783" alt="Screenshot 2020-04-09 at 12 54 36" src="https://user-images.githubusercontent.com/1820920/78888997-13289880-7a63-11ea-8ea5-8d22630d5aa0.png">

**Comment by benknoble** [comment]
@leandrocunha that's because of vim's syntax engine and the various things we try to do to be comparable simply aren't precise enough.

We're getting close to tree-sitter syntax integration with the new text-properties though.

**Comment by benknoble** [comment]
I'm going to close this since OP (@Lilja) hasn't responded to requests for syntax groups which would help us debugging. Feel free to reopen if this is still an issue and you want to help us track it down.

**Comment by Lilja** [comment]
Sorry, I did not understand any actions on my part. What syntax groups are we talking about?

**Comment by benknoble** [comment]
@Lilja vim's syntax highlight mechanism is multi-stage.

Syntax files create "groups" based on keywords, matches, and regions, and then name those groups (e.g., `jsObject`).

They often link these groups to one of the standard groups (`:help highlight-groups`).

Colorschemes (like dracula) are responsible for highlighting these default groups (though many, including ours, support some plugins and filetypes by targeting their specific groups as well).

If the syntax groups applying to your file somehow differ from what's expected, it could causes a coloring issue.

---

Long-story short, we need you to confirm if the highlight groups on `asyncData` (one spot where things seem to disagree) are the same as in [dsifford's comment, where things seemed to be working](https://github.com/dracula/vim/issues/172#issuecomment-598698806)?

I provided a couple of references on how to do so [here](https://github.com/dracula/vim/issues/172#issuecomment-597971625); a quick Google for "get syntax under cursor vim" gives many more.

**Comment by Lilja** [comment]
![image](https://user-images.githubusercontent.com/6134511/80891937-a1411900-8cc7-11ea-8886-f0190f33fcb6.png)

I ran `echo synstax#UnderCursor()`

**Comment by benknoble** [comment]
Right, there’s at least two missing groups there, which means that whatever syntax is being applied is not matching dsifford’s. 

In all likelihood, that’s a vim-vue issue.

**Comment by Lilja** [comment]
Hmm. I installed [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) and it seems to work. The syntax groups for `asyncData` are `['javaScript', 'jsObject', 'jsObjectFuncName']`. Closing this.
