### ISSUE TITLE
Unnecessary configuration

### ISSUE THREAD

**Issue by ImperadorSid** [dracula/vim#173]
### What happened
In the Vim manual it says that plugins placed inside the ``start`` folder are loaded automatically. If this is true, why do I have to use the "packadd! Dracula" directive?

### What I expected to happen
Loads dracula colorscheme correctly

### Screenshot
![image](https://user-images.githubusercontent.com/18284740/77804123-91497000-705d-11ea-8e0b-77f5c5b4e86b.png)

### Machine Info

Linux samore-lnx 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Vim type (`vim`/`gvim`/`neovim`)**: vim

- **Vim version**: 8.0.1453
- **OS**: Linux Mint 19.3 Tina
- **Terminal/Terminal Emulator/VTE**: Terminal Emulator (Tilix) and Terminal Emulator (GNOME Terminal)
- **`TERM` environment variable**: xterm-256color

##### Without ``packadd dracula`` directive
runtimepath=\~/.vim,\~/.vim/pack/themes/start/dracula,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,\~/.vim/after,\~/.vim/pack/themes/start/dracula/after
 
##### With``packadd dracula`` directive
runtimepath=\~/.vim,\~/.vim/pack/themes/start/dracula,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,\~/.vim/after,\~/.vim/pack/themes/start/dracula/after

##### Without ``packadd dracula`` directive
runtimepath=\~/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,\~/.vim/after

##### With ``packadd dracula`` directive
runtimepath=\~/.vim,\~/.vim/pack/themes/opt/dracula,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,\~/.vim/after,\~/.vim/pack/themes/opt/dracula/after

**Comment by benknoble** [comment]
It has everything to do with what the `runtimepath` is when you do `colorscheme dracula`.

If you do it in your `vimrc`, you *need* dracula on the `runtimepath`, because we have some stuff in `autoload`. If you do it later, you're probably ok.
