### ISSUE TITLE
Unwanted underlining and italics

### ISSUE THREAD

**Issue by bazzb** [dracula/vim#174]
###What happened
various things had special fonts
ints were italic
matching brackets highlighted

### What I expected to happen
those things to not have special fonts
how can i disable it

### Screenshot
![image](https://user-images.githubusercontent.com/15130680/77810154-69f8a000-7069-11ea-8bb5-116f300ecbe8.png)
### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: neovim
- **Vim version**: nvim v0.4.3
- **OS**:fedora 31
- **Terminal/Terminal Emulator/VTE**:xfce terminal
- **`TERM` environment variable**:xterm-256color

**Comment by benknoble** [comment]
Matching brackets is a vim option, not a dracula one. Have a look at the help for `showmatch`, among other things. 

Idk anything about special fonts (examples would help), but we have a setting to disable italic (`let g:dracula_italic = 0`, if memory serves). You’ll need to set that before loading the colorscheme.

**Comment by bazzb** [comment]
> Matching brackets is a vim option, not a dracula one. Have a look at the help for `showmatch`, among other things.
> 
> Idk anything about special fonts (examples would help), but we have a setting to disable italic (`let g:dracula_italic = 0`, if memory serves). You’ll need to set that before loading the colorscheme.

that did it!
