### ISSUE TITLE
Background is different than other Dracula themes, weird blue highlighting issues

### ISSUE THREAD

**Issue by alexbastuba** [dracula/vim#176]
Running vim in a terminal?
- Try adding `set termguicolors` to your vimrc.

I did this, and it turned my entire terminal screen green.
### What happened

I've been excited to try out the Dracula theme, and I love how it looks on Sublime, Terminal.app, and Zsh. I can't say the same for the vim version. For some reason it looks much, much worse than it does on my other editors. I'm not sure if it is because I set my terminal.app and zsh themes to be Dracula too, but when I disable both of those the issues still persist.

My terminal has the proper purple background that is identical to dracula on sublime, but for some reason Vim really doesn't like my dracula. The background is black, but around the edge I can see that it changes back to the proper purple, I believe because it dracula is behaving properly in terminal.app. There is also a strange blue highlighting that occurs, and the text seems bolded in a blurry type of way.

Here's what it looks like:
![image](https://user-images.githubusercontent.com/60586788/79034333-ffb42500-7b69-11ea-9550-a4061d8ad5ab.png)

What's strange is that when I open the same document in a Screen session after splitting panes, the background is fine. I still think that the text looks less clean, but the background is the same as my terminal.app background, or maybe just because it's using the terminal.app background instead: 
![image](https://user-images.githubusercontent.com/60586788/79034380-430e9380-7b6a-11ea-843d-75f6d88cd3bc.png)

I followed the suggestion of adding `set termguicolors` to my vimrc, but it just turned the vim editor all green, and the normalish gnu Screen session had white highlighting. 
![image](https://user-images.githubusercontent.com/60586788/79034506-4b1b0300-7b6b-11ea-961b-e11ebcec86f2.png)
![image](https://user-images.githubusercontent.com/60586788/79034507-5110e400-7b6b-11ea-897c-d4282126441f.png)

Honestly I'm not sure what to do. I've been searching related posts on different forums but can't find any solution, and just want my Vim to look pretty. :(

### What I expected to happen

I expected Dracula to look the same as it has in other editors but as stated above, it hasn't been cooporating.

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**:  VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  7 2020 18:46:28)
- **OS**: macOS
- **Terminal/Terminal Emulator/VTE**: terminal.app / gnu screen (I'm kinda new to all of this and idk if a multiplexor is an emulator too)
- **`TERM` environment variable**: xterm-256color

If having issues with text rendering, please provide the output of `infocmp`
-->

➜  ~ infocmp
	Reconstructed via infocmp from file: /usr/share/terminfo/78/xterm-256color
xterm-256color|xterm with 256 colors,
	am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
	colors#256, cols#80, it#8, lines#24, pairs#32767,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
	dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
	flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
	ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
	ind=^J, indn=\E[%p1%dS,
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
	rmir=\E[4l, rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smm=\E[?1034h, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,

**Comment by benknoble** [comment]
Dont `set termguicolors` unless your terminal supports truecolor. 

For the blue reverse-highlighted words, you are probably looking for the configuration value to disable italic fonts in the highlight (`g:dracula_italic`, I think).

For the background, try the config value `g:dracula_colorterm` (poorly named, I grant you). 

All of this is detailed in `:help dracula`

**Comment by alexbastuba** [comment]
Hey, thanks for the fast reply! I'm loving Dracula by the way - especially the green function highlighting. 

I'll check those settings out, where do I change them? I assume just putting them in .vimrc and setting values to 0? The `:help dracula' feature is well written, thanks for showing me that. I'm pretty new to terminal and I'm still learning.

Why do you think that the background color is off in the first place? What would cause Vim to highlight everything in grey instead of purple? I think I have a pretty stock setup, no other Vim plugins and only stock OhMyZsh, but I would prefer to change whatever is wrong with my system to work with all the features of the color scheme instead of disabling them in the end if possible.

I heard that the syntax highlighting isn't the best in Vim when using Java, which is what my class requires, and I'm considering downloading a java.vim like this : https://github.com/dragfire/Improved-Syntax-Highlighting-Vim

Would this be useful or is the colorscheme already developed for how Vim normally handles syntax highlighting?

~Thank you so much for your help

**Comment by benknoble** [comment]
> Why do you think that the background color is off in the first place? 

It's mostly an approximation issue. The closest color to the "true" RRGGBB background in 256-color space is not always going to be accurate.

> Am I missing out on anything by disabling italics? Why do you think it is causing an issue?

Not at all. The reason they don't work is because your terminal emulator doesn't support them (or isn't configured to support them). The default way of displaying italics without actual italic font support is via a "reverse" coloring: basically, the background gets the highlight. Turning them off lets the foreground get the actual highlight.

> I heard that the syntax highlighting isn't the best in Vim when using Java

It isn't perfect, but it isn't awful. Vim syntax engine is notoriously complicated and in some ways limited (although with the new text-properties feature, we're getting closer to a tree-sitter/parser based syntax-highlighting approach). I've never had an issue with java syntax highlighting, but I would consider looking for a repo that's more currently maintained and more java targeted. The default java syntax is pretty limited...

Dracula itself as a colorscheme defines colors for highlight groups, and most syntax files associate their syntax rules with said highlight groups.
