### ISSUE TITLE
Take new screenshot

### ISSUE THREAD

**Issue by zenorocha** [dracula/vim#177]
Hey @benknoble @dsifford!

Can you update the screenshot to use the new code snippet?

## New Snippet

```js
/*
 * Once upon a time...
 */

class Vampire {
  constructor(props) {
    this.location = props.location;
    this.birthDate = props.birthDate;
    this.deathDate = props.deathDate;
    this.weaknesses = props.weaknesses;
  }

  get age() {
    return this.calcAge();
  }

  calcAge() {
    return this.deathDate - this.birthDate;
  }
}

// ...there was a guy named Vlad

const Dracula = new Vampire({
  location: 'Transylvania',
  birthDate: 1428,
  deathDate: 1476,
  weaknesses: ['Sunlight', 'Garlic']
}); 
```

## Why use this?

* It contains examples of string, number, and array
* It contains examples of single line and multi-line comments
* It contains examples of inheritance and functions
* It's simple, funny, and silly

## Want to use another language?

Feel free to send a pull request to the [template repo](https://github.com/dracula/template) under the `sample` folder.

**Comment by benknoble** [comment]
@dsifford I can take care of this in a bit if you prefer, esp. since I have both vims set up /shrug

**Comment by zenorocha** [comment]
@benknoble do you mind if we keep only the classic Dracula colors on the screenshot? I think that's better since it's what people will get by installing this one.

**Comment by benknoble** [comment]
I *think* they’re only classic; let me know if there’s something wrong...

The “dracula pro” in the Terminal title bar is my Terminal’s theme :)

**Comment by zenorocha** [comment]
Ohhhh got it!

**Comment by zenorocha** [comment]
Here's the live preview, in case you haven't seen it yet: https://draculatheme.com/vim ;)
