### ISSUE TITLE
Background color isn't consistent with the .Xresources theme

### ISSUE THREAD

**Issue by KiviTK** [dracula/vim#179]
### What happened
The vim background color is not the same as the Xresources color
resulting in the vim editor having a different color than the terminal
(and other applications that use my Xresources)

### What I expected to happen
Well, to have the same background color across different dracula themes.
I tried adding `set termguicolors` to my .vimrc, that fixed the background, however it completely removed all other coloring.

### Screenshot
![2020-04-19-185831_825x856_scrot](https://user-images.githubusercontent.com/35783191/79694297-ba7daa80-826f-11ea-90ae-3c9a1b437b95.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: `vim`
- **Vim version**: `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 13:23:00)`
- **OS**: `Linux kaguya 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux`
- **Terminal/Terminal Emulator/VTE**: `st`
- **`TERM` environment variable**: `st-256color`

**Comment by dsifford** [comment]
Your terminal’s background color is controlled by the terminal. Set `let g:dracula_colorterm = 0` before loading the color scheme

**Comment by KiviTK** [comment]
Yes, fixed it, thanks!
