### ISSUE TITLE
Install and use with packages: colors don't look right

### ISSUE THREAD

**Issue by benknoble** [dracula/vim#180]
This is a mail-in from Julian Hapke

> Hi Ben,
> 
> I'm trying to use the dracula vim plugin with the vim 8 package manager. So it cloned the repo into `$HOME/.vim/pack/j-hap/start/` (so there is a dracula subdir in start). I put
> 
> ```
> colorscheme dracula
> syntax on
> ```
> 
> in my `./vim/vimrc` and everything should be fine. Problem is: Colors are still default. It's hard to tell, because the shell is also in dracula, but comments are cyan, which is a big giveaway. Even though `:colors` gives `dracula`
> 
> My understanding is, that these lines from `./autoload/dracula.vim` and `./colors/dracula.vim` overload the default color:
> 
> ```
> let g:dracula#palette.comment   = ['#6272A4',  61]
> 
> let s:comment   = g:dracula#palette.comment
> call s:h('DraculaComment', s:comment)
> hi! link Comment DraculaComment
> ```
> 
> According to the output of `:scriptnames` all necessary files are loaded:
> 
> ```
>   1: ~/.vim/vimrc
>   2: /usr/share/vim/vim82/syntax/syntax.vim
>   3: /usr/share/vim/vim82/syntax/synload.vim
>   4: /usr/share/vim/vim82/syntax/syncolor.vim
>   5: /usr/share/vim/vim82/filetype.vim
>   6: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
>   7: ~/.vim/pack/j-hap/start/dracula/colors/dracula.vim
>   8: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
>   9: /usr/share/vim/vim82/plugin/gzip.vim
>  10: /usr/share/vim/vim82/plugin/logiPat.vim
>  11: /usr/share/vim/vim82/plugin/manpager.vim
>  12: /usr/share/vim/vim82/plugin/matchparen.vim
>  13: /usr/share/vim/vim82/plugin/netrwPlugin.vim
>  14: /usr/share/vim/vim82/plugin/rrhelper.vim
>  15: /usr/share/vim/vim82/plugin/spellfile.vim
>  16: /usr/share/vim/vim82/plugin/tarPlugin.vim
>  17: /usr/share/vim/vim82/plugin/tohtml.vim
>  18: /usr/share/vim/vim82/plugin/vimballPlugin.vim
>  19: /usr/share/vim/vim82/plugin/zipPlugin.vim
>  20: ~/.vim/pack/j-hap/start/dracula/after/plugin/dracula.vim
>  21: ~/.vim/pack/j-hap/start/dracula/autoload/dracula.vim
> ```
> 
> What am I missing? Please help me.
>

**Comment by benknoble** [comment]
I find it odd that `autoload/dracula` is as the end (in my vim, it usually appears right after `colors/dracula`).

Can you show the output of `:messages`? *Usually* with packages (for dracula, at least) you have to defer `:colorscheme dracula` until after `~/.vim/pack/j-hap/start/dracula` is on the runtime path so that the `autoload` stuff gets picked up properly. Ways to do that include

1. Forcing the package to load with `:packadd! dracula`
2. Using a `VimEnter` autocommand
3. Putting `:colorscheme dracula` into `~/.vim/plugin/after_plugins.vim` (or similar)

**Comment by j-hap** [comment]
If I'm just too stupid to install the plugin and there is nothing actually wrong in the code, please let me know :)

Thanks for the help!

**Comment by benknoble** [comment]
@j-hap we want to make sure there's no issue—we want everyone to benefit from dracula :) give the things I mentioned a try, and make sure `:messages` isn't showing an errors. The more information we have, the easier this is to debug.

**Comment by j-hap** [comment]
The :messages output is empty. I tried putting the content of the repository into ~/.vim/pack/j-hap/opt/dracula and explicitly loaded it with packadd! dracula, but that did not change anything. Btw. I'm using vim 8.2 in MSYS2 on Windows 10. I just testet on my laptop with Xubuntu and vim 8.1 and it works... I did nothing differently.

**Comment by benknoble** [comment]
Nah, don't need to put in opt, just `packadd!` it before `colorscheme`ing...

That's odd. I still think the load-order is bizarre here.

What if you try number (3) in my list?

Effectively, you have no `:colorscheme` in your vimrc, but you have `colorscheme dracula` in `~/.vim/plugin/any_name_you_want.vim`

**Comment by j-hap** [comment]
It works now, there were / are several problems. First: The Cygwin / MinTTY terminal of the MSYS2 has $TERM=xterm by default, which does not seem to play well with vim highlights. So when I changed that to "xterm-256color" or "mintty" I had lots of errors on vim start, because of undefined colors. that must be the wrong plugin file order, that you already mentioned. Setting the "colorscheme dracula" fixed that, although in the :scriptnames that file is still between vimrc and ~/.vim/pack/j-hap/start/dracula/colors/dracula.vim

**Comment by benknoble** [comment]
Great! I didn’t think to ask about that—vim sets the amount of available colors based on terminfo which is based on `TERM`. Glad you got it working.
