### ISSUE TITLE
Coloring is off, have checked other issues already

### ISSUE THREAD

**Issue by THe142857** [dracula/vim#182]
### What happened
I downloaded the dracula colorscheme with vim-plug, but the coloring is very off.
### What I expected to happen
the coloring to look like the screenshot or as it looks in CLion
### Screenshot
<img width="670" alt="Screen Shot 2020-04-24 at 12 19 29 AM" src="https://user-images.githubusercontent.com/47944885/80174681-5e918980-85c1-11ea-9e3a-81b69e02ba18.png"> (MacOS Terminal)
<img width="726" alt="Screen Shot 2020-04-24 at 12 19 49 AM" src="https://user-images.githubusercontent.com/47944885/80174683-60f3e380-85c1-11ea-95d2-904534b932ad.png"> (MacVim)
<img width="445" alt="Screen Shot 2020-04-24 at 12 23 00 AM" src="https://user-images.githubusercontent.com/47944885/80174805-c8aa2e80-85c1-11ea-893c-3bd81b29b95b.png"> (.vimrc file)
Sorry if the vimrc file looks weird or anything. I just recently picked up Vim, so I still don't 100% understand what's going on. I tried setting the dracula variables to 0 as I saw in the other issues and :help meu, though they did not change much.
### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: Vim and MacVim
- **Vim version**: 8.2
- **OS**: MacOS Catalina 10.15.3
- **Terminal/Terminal Emulator/VTE**: Terminal.app
- **`TERM` environment variable**: xterm-256color

### Additional Info
I wanted to note that I already checked a few of the other coloring issues and the :help, but none of them seemed to solve the issue. Also, I just wanted to say that Dracula is my favorite colorscheme, so thanks!

If having issues with text rendering, please provide the output of `infocmp`
```
xterm-256color|xterm with 256 colors,
	am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
	colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
	el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
	hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
	il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[<, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, oc=\E]104\007, op=\E[39;49m, rc=\E8,
	rep=%p1%c\E[%p2%{1}%-%db, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
	rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l, rmkx=\E[?1l\E>,
	rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m,
	rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
	smcup=\E[?1049h\E[22;0;0t, smir=\E[4h, smkx=\E[?1h\E=,
	smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
	u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?%[;0123456789]c,
	u9=\E[c, vpa=\E[%i%p1%dd,
```

**Comment by benknoble** [comment]
The only thing that looks odd to me is the color of the line numbers in the last screenshot. Other than that, seems like business as usual?

It does help to use the Dracula theme for your terminal if you're in terminal vim.

**Comment by THe142857** [comment]
<img width="776" alt="Screen Shot 2020-04-24 at 5 25 06 PM" src="https://user-images.githubusercontent.com/47944885/80258199-a14e7280-8650-11ea-8197-561ef65de3a6.png"> (Vim Terminal)
<img width="707" alt="Screen Shot 2020-04-24 at 5 25 32 PM" src="https://user-images.githubusercontent.com/47944885/80258204-a3183600-8650-11ea-93a6-e4d9ef02fe55.png"> (CLion)

I used CLion for a bit, and here is what it looks like on there. It's definitely still useable as it is in Vim currently, though it seems to missing or generating incorrectly quite a few colors

**Comment by benknoble** [comment]
Ah, you want vim to look like CLion. CLion is honestly doing quite a bit; vim's syntax highlighting can be a finicky beast, and it's very difficult to get full compatibility across all editors.

@dsifford tossed out the idea of a spec at one point, but it's hard to get even that perfectly. Ultimately I'm just not sure what you're after is possible (or, it is, but I'd rather you customize your vim to look like that—I'm happy with the defaults.)

Fortunately, such a thing is doable if you want to customize, e.g., `~/.vim/after/syntax/c.vim` and highlight whatever you want however you want.

**Comment by dsifford** [comment]
@benknoble the spec merged now! And yeah, CLion is non-compliant.

https://spec.draculatheme.com/

The C languages have pretty abysmal default highlighting because those languages can get quite complex.

The following plugins seem interesting for C (and friends) highlighting. The syntax groups are generated by clang, which is probably much more accurate...

- https://github.com/arakashic/chromatica.nvim
- https://github.com/bbchung/clighter8
- https://github.com/bbchung/Clamp

**Comment by THe142857** [comment]
Ah ok I see. I'll take a look and thanks for the quick responses!
