### ISSUE TITLE
How did we get the approximate term (8-bit) colors for the RGB codes?

### ISSUE THREAD

**Issue by benknoble** [dracula/vim#183]
I'm working with @zenorocha on the dracula pro version of the vim theme (woohoo!).

I realized, though, that I had no idea how to accurately convert `#RRGGBB` to a 256-color approximate color, which we need to do.

/cc @dsifford if you know, I'd love some resources or help on this.

**Comment by dsifford** [comment]
Can't recall off the top of my head. IIRC there was a library or website that I just plugged the values in and it spit back the approximations.

**Comment by benknoble** [comment]
Hm, ok. I had implemented this function at one point (I tried a couple libraries, but none of them lined up with what we had for everything), but I never tested to see if it was the approximation:

```
function s:hex_string_to_nr(hex) abort
  let result = 0
  let power = 0
  for char in split(a:hex, '\zs')
    let num = get({
          \ '0': 0,
          \ '1': 1,
          \ '2': 2,
          \ '3': 3,
          \ '4': 4,
          \ '5': 5,
          \ '6': 6,
          \ '7': 7,
          \ '8': 8,
          \ '9': 9,
          \ 'A': 10,
          \ 'B': 11,
          \ 'C': 12,
          \ 'D': 13,
          \ 'E': 14,
          \ 'F': 15,
          \  }, char, 0)
    let result += float2nr(pow(16, power)) * num
    let power += 1
  endfor
  return result
endfunction

function s:rgb_to_8_bit(color) abort
  let l:hex_digits = substitute(a:color, '\X', '', 'g')
  let [r, g, b] = map(split(l:hex_digits, '..\zs'), 's:hex_string_to_nr(v:val)')
  " taken from https://stackoverflow.com/a/12808927/4400820
  return r * 6/256 * 36 + g * 6/256 * 6 + b * 6/256
endfunction
```

The idea was just to use `["#RRGGBB", s:rgb_to_8_bit("#RRGGBB")]`—though as I said, I never tried it.

**Comment by dsifford** [comment]
I opted to not go with the function because the values are static and won't really ever change so it saved some precious milliseconds from execution time.

**Comment by benknoble** [comment]
I agree—just trying to figure out what the calculation on the values was. I'll try this out again slightly differently and test the values (or maybe try some linear regression... hmm.).

**Comment by benknoble** [comment]
Closing this since @zenorocha ended up using https://www.npmjs.com/package/color-convert and is probably adding a column to the color-palette information.

**Comment by zenorocha** [comment]
I just added the ANSI 16 and ANSI 256 color codes on https://draculatheme.com/contribute.

**Comment by dsifford** [comment]
Do you guys know if these new colors match the ones we have both here in the vim repo (and because I'm lazy, in the vscode repo)?

**Comment by benknoble** [comment]
Sorry for the late reply (star wars day celebration gone long 🤔 ?); I put this together and noticed some discrepancies:

```
Site          #         vim-code   #
Foreground    231       fg         253
_             _         bglighter  238
_             _         bglight    237
Background    59        bg         236
_             _         bgdark     235
_             _         bgdarker   234
Comment       103       comment    61
Current-Line  60        selection  239
_             _         subtle     238
Cyan          159       cyan       117
Green         120       green      84
Orange        222       orange     215
Pink          212       pink       212
Purple        183       purple     141
Red           210       red        203
Yellow        229       yellow     228
```

I *think*, but am not sure, that the vim column is assuming the terminal's colors are set appropriately?

**Comment by dsifford** [comment]
May the fourth be with you! :bow: :man_astronaut: 

Honestly, I'm not sure. It very well could be a bug. If you have the bandwidth to look into this further and can come up with a solve if it is a bug, then I'm all for that.

**Comment by benknoble** [comment]
Alright, so I'll provide two screenshots and we can decide if the difference matters.

In each one, I have alacritty on the left, with the palette set to a dracula-pro variant; on the right, Terminal.app with the same. I turned off `termguicolors` in alacritty (Terminal.app doesn't support it). They are both viewing the same file.

The first contains the original colors (right-hand column of the table above):
<img width="1280" alt="original_colors" src="https://user-images.githubusercontent.com/22802209/88079997-750d9980-cb4c-11ea-96cf-f1b0b775cd42.png">

The second is after modifying `autoload/dracula.vim` to use the site colors (left-hand column of the table):
<img width="1280" alt="site_colors" src="https://user-images.githubusercontent.com/22802209/88080044-85be0f80-cb4c-11ea-9b04-4baf354a7e66.png">

I haven't had time to see what happens when the terminal palette is different, or closer to the xterm standard (whatever that is)

**Comment by benknoble** [comment]
I should also note that I didn't have cursorline enabled or the dracula bg enabled in either of those

**Comment by dsifford** [comment]
I feel like I like the first one better?

Particularly with respect to the orange color which looks more yellow in the second one.

**Comment by benknoble** [comment]
/shrug to be honest I see the difference... but I'm not sure how much I care about it yet... I've been using the first for so long that at this point...
