### ISSUE TITLE
Installation Issues using Website Instructions

### ISSUE THREAD

**Issue by salt-mountain** [dracula/vim#184]
Big fan of the Dracula theme. Where I can install it, I do. My journey with vim is relatively young but I'm trying to learn and make progress :)

### What happened
I followed the installation instructions on the [website](https://draculatheme.com/vim) following the first section, using the default instructions using Vim 8's packages. I cloned the Dracula repository into `/Users/saltmountain/.vim/pack/themes/start/dracula`

My .vimrc file looks as follows
```
" Dracula Color Theme. 
packadd! dracula
syntax enable
```

What happens instead is that I get an error about a directory not being found in my packpath
```
Error detected while processing /Users/saltmountain/.vimrc:
line    9:
E919: Directory not found in 'packpath': "pack/*/opt/dracula"
Press ENTER or type command to continue
```

Additionally, if I add a `colorscheme dracula` to the end of my `Dracula` block in my `.vimrc` file, I get several lines of output of undefined variables.

### What I expected to happen
vim to load the dracula color scheme correctly.

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.0 (2016 Sep 12, compiled Jun 19 2019 19:08:44). Included patches: 1-503, 505-680, 682-1283, 1365.
- **OS**:  OS X Catalina 10.14.6
- **Terminal/Terminal Emulator/VTE**: iTerm2
- **`TERM` environment variable**:`xterm-256color`

I feel like I'm probably close and just missing something crucial to finish the installation process.

**Comment by benknoble** [comment]
Is there any chance you can update to 8.1 or 8.2? I believe it will work then (and I’m curious to know). 

If not, I _think_ the issue is that when packages were first introduced `packadd!` only affected `opt` directories (this may still be true, but it’s been a while since I loaded dracula this way). The docs on `pacakdd` can be a bit murky. 

Things to try:

1. Place dracula in `/Users/saltmountain/.vim/pack/themes/opt/dracula`, and I’ll update the instructions
2. Use one of the “other” (slightly more advanced) methods for loading dracula. Try 1 first.

**Comment by salt-mountain** [comment]
> Place dracula in /Users/saltmountain/.vim/pack/themes/opt/dracula, and I’ll update the instructions

This seems to have worked. No errors

**Comment by salt-mountain** [comment]
> Is there any chance you can update to 8.1 or 8.2? I believe it will work then (and I’m curious to know).

I'm using the OS X default built-in vim version. I'll try using Homebrew to get the latest version from there and try the installation instructions again.

> Place dracula in /Users/saltmountain/.vim/pack/themes/opt/dracula, and I’ll update the instructions

This worked with the default OS X vim installation. I didn't get any errors. I do have some blue highlighting issues, which I think I saw on another issue about being about italics, but I can tackle that separately.

**Comment by salt-mountain** [comment]
> I'll try using Homebrew to get the latest version from there and try the installation instructions again.

``` 
Vi IMproved 8.2 (2019 Dec 12, compiled Apr 29 2020 01:33:22)
macOS version
Included patches: 1-654
Compiled by Homebrew
```
Works with the Homebrew Install ! 

I dont know how painful it would be to maintain two separate sets of instructions, it would at least be annoying. Maybe just a call-out for OS X users to use the Homebrew vim as opposed to the built-in one provided by Apple.

Thanks for your help @benknoble !

**Comment by benknoble** [comment]
Np! I'll add a note that older vims (8.0) may need `opt`
