### ISSUE TITLE
Missing Colors JS

### ISSUE THREAD

**Issue by ztroop** [dracula/vim#185]
### What Happened
Color in `javascript` is lacking. Color looks complete while viewing `rust` source files. Color looks mostly complete while viewing `python` source files. I should mention I'm also using the plugin `ale`, a code linting engine.
### Screenshots
JavaScript
![js example](https://user-images.githubusercontent.com/5018339/80930409-68fe1100-8d81-11ea-875e-ebf6f0f03ddd.png)
Rust
![rust example](https://user-images.githubusercontent.com/5018339/80930585-81226000-8d82-11ea-9dbc-5dda34f01740.png)
Python
![python example](https://user-images.githubusercontent.com/5018339/80930590-867faa80-8d82-11ea-944d-29df3923467a.png)
*note: the orange prefix character is a linting indicator*

### Machine Info
`vimrc`:
```
execute pathogen#infect()
syntax on

let g:dracula_colorterm = 0
colorscheme dracula
filetype plugin indent on
set number
set nowrap
```
`vim`: 2:8.0.1453-1ubuntu1.3
`os`: Ubuntu 18.04
`$TERM`: xterm-256color

**Comment by dsifford** [comment]
This looks to just that you dislike the default syntax highlighting for javascript. The nice part about vim is that you don't need to use that one. Search for "vim javascript syntax" on github or google and you'll find dozens of alternatives.

**Comment by benknoble** [comment]
Just to follow-up/clarify Derek's comments—the syntax-file that vim ships with for javascript is notoriously incomplete. pangloss/vim-javascript is one of the most popular replacements.

**Comment by ztroop** [comment]
Just to be clear, the `Vampire` class example is nearly identical to the one that's shown in the `README.md`. Despite highlighting syntax challenges around JS, the result is _not consistent_ with what you're showing in your documentation.

**Comment by benknoble** [comment]
The screenshot is my personal vim with pangloss/vim-javascript providing the syntax definitions and dracula the colors. Have you tried using that syntax plugin?

**Comment by ztroop** [comment]
I have not tried that syntax plugin, perhaps we should mention that below the screenshot?

**Comment by dsifford** [comment]
@ztroop sounds like a reasonable suggestion. 

@benknoble could you take care of that when you get time?
