### ISSUE TITLE
Support GUI popup

### ISSUE THREAD

**Issue by PitcherTear22** [dracula/vim#188]
### What happened
      Background of the GUI popup is the same as default (terminal popups are themed properly)
![Screenshot from 2020-05-13 17-31-00](https://user-images.githubusercontent.com/36493671/81810060-ea9f2d00-953f-11ea-9484-6378595cca19.png)

### What I expected to happen
      GUI popups themed properly like [vim-codedark](https://github.com/tomasiser/vim-code-dark)
![Screenshot from 2020-05-13 17-29-56](https://user-images.githubusercontent.com/36493671/81810126-0efb0980-9540-11ea-894b-78c6831231ec.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**:[Neovim-GTK](https://github.com/daa84/neovim-gtk)
- **Vim version**: NVIM v0.5.0-478-g42b441738
- **OS**:Linux ga-h100m-s2 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux (Arch Linux)
- **Terminal/Terminal Emulator/VTE**:N/A
- **`TERM` environment variable**:N/A

**Comment by dsifford** [comment]
I believe this highlight is handled by GTK itself and not neovim.

See https://github.com/neovim/neovim/issues/9026#issuecomment-423502428 for a similar issue with QT neovim.

See https://github.com/daa84/neovim-gtk/wiki/Configuration#options for a GTK specific way of disabling this.

**Comment by PitcherTear22** [comment]
> See https://github.com/daa84/neovim-gtk/wiki/Configuration#options for a GTK specific way of disabling this.

Do you mean disabling the GUI popup?

**Comment by dsifford** [comment]
Correct.

**Comment by PitcherTear22** [comment]
> Correct.

Bruh

**Comment by PitcherTear22** [comment]
@dsifford Funnily it works in a qt/go gui (goneovim)

**Comment by dsifford** [comment]
Happy to merge a PR if you have a solve for this that doesn't depend on the existence of GTK or QT. 

We already specify the highlight groups for `PMenu` which are the only popup menu groups we can target in neovim.

**Comment by PitcherTear22** [comment]
Sorry, I'm not trying to attack you
