### ISSUE TITLE
how to install dracula theme on spacevim?

### ISSUE THREAD

**Issue by spazmantiz** [dracula/vim#190]

**Comment by benknoble** [comment]
I’m not a spacevim user, and I don’t think @dsifford is either. Does the spacevim project have documentation on how to install custom plugins or packages?

**Comment by dsifford** [comment]
@benknoble https://spacevim.org/documentation/#custom-configuration

Looks like it's a dein wrapper under the hood.

**Comment by benknoble** [comment]
Welp, looks like best thing to do is add dracula to those custom plugins?

**Comment by spazmantiz** [comment]
> Welp, looks like best thing to do is add dracula to those custom plugins?

yes please, i want easy install

**Comment by dsifford** [comment]
Follow instructions on this page: https://spacevim.org/layers/colorscheme/

**Comment by spazmantiz** [comment]
i manage to install it by editing my **HOME/.Spacevim.d/init.toml** using this command
[[custom_plugins]]
  name = "dracula/vim"
[options]
  colorscheme = "dracula"

**Comment by spazmantiz** [comment]
should i close it?

**Comment by benknoble** [comment]
(Hope nobody minds, but I cleaned up the solution comment formatting)

**Comment by spazmantiz** [comment]
i think you guys should also add guide to install dracula for vim distributions
