### ISSUE TITLE
listchars not visible when cursorline is enabled.

### ISSUE THREAD

**Issue by carlogravador** [dracula/vim#192]
### What happened
listchars(spaces, tabs) on a line are not visible when cursorline is active on that line. Also When the cursor is pointing on a listchar, it also becomes not visible

### What I expected to happen
Is it possible to change the colors of listchars and invert the color when cursorline or the cursor is on that position

### Screenshot
In this screenshot, on the 1st line, trailing spaces is visible and the colors are perfect for the theme
![image](https://user-images.githubusercontent.com/29529072/83220090-a6996280-a1a4-11ea-8c59-6ccd794fd9ec.png)
But on the second line, my cursor is on the first column of the line, but is not visible, also the trailing spaces are not visible because it blends with the cursorline color. I,m using indentline plugin to show indents.

### Machine Info
Linux probook 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Vim type**:NeoVim
- **Vim version**: v0.5.0-529-g8c588246a
- **OS**: Ubuntu 20.04
- **Terminal/Terminal Emulator/VTE**:GNOME Terminal 3.36.1.1
- **`TERM` environment variable**: xterm-256color

**Comment by benknoble** [comment]
I don't know about solving this, but this is because `listchars` uses `SpecialKey` for trailing whitespace, which links to `DraculaSubtle` (`ctermfg=60`). `CursorLine` has `ctermbg=60`, so they blend.

As I said, I don't know about an official solution to this, but you could always do

```
autocmd ColorScheme dracula hi! CursorLine ...
```

to use your own `CursorLine` color

**Comment by carlogravador** [comment]
Thank's for the answer, I've managed to achieve what I want by changing the colors of listchars.

```vimscript
highlight SpecialKey ctermfg=... guifg=...
highlight Whitespace ctermfg=... guifg=...
```
![image](https://user-images.githubusercontent.com/29529072/83324322-1851d900-a297-11ea-9a0b-56523b8cc6d7.png)

**Comment by benknoble** [comment]
Could you share the value you used? I'm wondering if we should consider a change on this (I for one wouldn't be opposed to some of these characters being a little more visible; the output in `:map` with special characters for example is a bit hard to read at times).
