### ISSUE TITLE
highlighting in vim-asciidoctor not working

### ISSUE THREAD

**Issue by hhoeflin** [dracula/vim#194]
### What happened
I am using the dracula colorscheme with the [vim-asciidoctor](https://github.com/habamax/vim-asciidoctor) extension. I am having the issue that with the dracula colorscheme, various highlights do not work (such as headings). When switching to a different colorscheme (such as solarized8), the highlights of headings works.

### What I expected to happen
Heading highlights should work

### Screenshot
With dracula colorscheme
![image](https://user-images.githubusercontent.com/2385506/83356610-81088680-a367-11ea-978b-3c4e9481e718.png)

With solarized8
![image](https://user-images.githubusercontent.com/2385506/83356626-a8f7ea00-a367-11ea-8469-a609aef3d7b5.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: neovim
- **Vim version**: 0.4.3
- **OS**: CentOS7
- **Terminal/Terminal Emulator/VTE**: MobaXterm
- **`TERM` environment variable**: screen-256color

### Additional Info
tmux 1.8, pid 106884, started Wed May 20 08:27:55 2020
socket path /tmp/tmux-50238/default, debug level 0
system is Linux 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64
configuration file is ###################### redacted
protocol version is 7

Clients:
 0: /dev/pts/11 (6, 8): 0 [282x73 screen-256color bs=10 class=0] [flags=0x4001/0x38, references=0]

Sessions: [14]
 0: 0: 7 windows (created Wed May 20 08:27:55 2020) [282x72] [flags=0x0]
	## details redacted

Terminals:
screen-256color [references=1, flags=0x1]:
 1: acsc: (string) ++,,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~
 0: AX: (flag) true
 2: bel: (string) \007
 3: blink: (string) \033[5m
 4: bold: (string) \033[1m
 5: Cc: [missing]
 6: civis: (string) \033[?25l
 7: clear: (string) \033[H\033[J
 8: cnorm: (string) \033[34h\033[?25h
 9: colors: (number) 256
10: Cr: [missing]
11: Cs: [missing]
12: csr: (string) \033[%i%p1%d;%p2%dr
13: Csr: [missing]
14: cub: (string) \033[%p1%dD
15: cub1: (string) \010
16: cud: (string) \033[%p1%dB
17: cud1: (string) \012
18: cuf: (string) \033[%p1%dC
19: cuf1: (string) \033[C
20: cup: (string) \033[%i%p1%d;%p2%dH
21: cuu: (string) \033[%p1%dA
22: cuu1: (string) \033M
23: dch: (string) \033[%p1%dP
24: dch1: (string) \033[P
25: dim: [missing]
26: dl: (string) \033[%p1%dM
27: dl1: (string) \033[M
28: E3: [missing]
29: ech: [missing]
30: el: (string) \033[K
31: el1: (string) \033[1K
32: enacs: (string) \033(B\033)0
33: fsl: (string) \007
34: home: (string) \033[H
35: hpa: [missing]
36: ich: (string) \033[%p1%d@
37: ich1: [missing]
38: il: (string) \033[%p1%dL
39: il1: (string) \033[L
40: invis: [missing]
41: is1: [missing]
42: is2: (string) \033)0
43: is3: [missing]
44: kcbt: (string) \033[Z
45: kcub1: (string) \033OD
46: kcud1: (string) \033OB
47: kcuf1: (string) \033OC
48: kcuu1: (string) \033OA
49: kDC: [missing]
50: kDC3: [missing]
51: kDC4: [missing]
52: kDC5: [missing]
53: kDC6: [missing]
54: kDC7: [missing]
55: kdch1: (string) \033[3~
56: kDN: [missing]
57: kDN3: [missing]
58: kDN4: [missing]
59: kDN5: [missing]
60: kDN6: [missing]
61: kDN7: [missing]
62: kend: (string) \033[4~
63: kEND: [missing]
64: kEND3: [missing]
65: kEND4: [missing]
66: kEND5: [missing]
67: kEND6: [missing]
68: kEND7: [missing]
69: kf1: (string) \033OP
70: kf10: (string) \033[21~
71: kf11: (string) \033[23~
72: kf12: (string) \033[24~
73: kf13: [missing]
74: kf14: [missing]
75: kf15: [missing]
76: kf16: [missing]
77: kf17: [missing]
78: kf18: [missing]
79: kf19: [missing]
80: kf2: (string) \033OQ
81: kf20: [missing]
82: kf3: (string) \033OR
83: kf4: (string) \033OS
84: kf5: (string) \033[15~
85: kf6: (string) \033[17~
86: kf7: (string) \033[18~
87: kf8: (string) \033[19~
88: kf9: (string) \033[20~
89: kHOM: [missing]
90: kHOM3: [missing]
91: kHOM4: [missing]
92: kHOM5: [missing]
93: kHOM6: [missing]
94: kHOM7: [missing]
95: khome: (string) \033[1~
96: kIC: [missing]
97: kIC3: [missing]
98: kIC4: [missing]
99: kIC5: [missing]
100: kIC6: [missing]
101: kIC7: [missing]
102: kich1: (string) \033[2~
103: kLFT: [missing]
104: kLFT3: [missing]
105: kLFT4: [missing]
106: kLFT5: [missing]
107: kLFT6: [missing]
108: kLFT7: [missing]
109: kmous: (string) \033[M
110: knp: (string) \033[6~
111: kNXT: [missing]
112: kNXT3: [missing]
113: kNXT4: [missing]
114: kNXT5: [missing]
115: kNXT6: [missing]
116: kNXT7: [missing]
117: kpp: (string) \033[5~
118: kPRV: [missing]
119: kPRV3: [missing]
120: kPRV4: [missing]
121: kPRV5: [missing]
122: kPRV6: [missing]
123: kPRV7: [missing]
124: kRIT: [missing]
125: kRIT3: [missing]
126: kRIT4: [missing]
127: kRIT5: [missing]
128: kRIT6: [missing]
129: kRIT7: [missing]
130: kUP: [missing]
131: kUP3: [missing]
132: kUP4: [missing]
133: kUP5: [missing]
134: kUP6: [missing]
135: kUP7: [missing]
136: Ms: [missing]
137: op: (string) \033[39;49m
138: rev: (string) \033[7m
139: ri: (string) \033M
140: rmacs: (string) \017
141: rmcup: (string) \033[?1049l
142: rmkx: (string) \033[?1l\033>
143: setab: (string) \033[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m
144: setaf: (string) \033[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m
145: sgr0: (string) \033[m\017
146: sitm: [missing]
147: smacs: (string) \016
148: smcup: (string) \033[?1049h
149: smkx: (string) \033[?1h\033=
150: smso: (string) \033[3m
151: smul: (string) \033[4m
152: tsl: (string) \033]0;
153: vpa: [missing]
154: xenl: (flag) true
155: XT: (flag) true

Jobs:

**Comment by benknoble** [comment]
Can you check the syntax groups? It looks from the plugin like most of their syntax groups are properly linked to standard highlight groups, so I’m surprised about this.

**Comment by hhoeflin** [comment]
How can I check the syntax groups?

**Comment by benknoble** [comment]
There are plugins such as my own synstax or tpope’s scriptease (both on GitHub). And you can usually follow the chain of links, so if you get `xyz` for the header, you can run `:hi xyz` to see if it’s linked. Etc.

**Comment by hhoeflin** [comment]
Thanks - tracking this down further, I think it is related to my terminal not being able to do bold and italic. I had not noticed this before, but likely this is the issue. Sorry for bothering you. Closing.
