### ISSUE TITLE
Typescript syntax highlighting broken when first loading

### ISSUE THREAD

**Issue by bdielman** [dracula/vim#199]
### What happened

After upgrading to the latest version, I saw that it includes support for the `vim-jsx-pretty` plugin. I've used that with other colorschemes and was happy to see official support in Dracula. I have noticed some strange behavior with regards to `.tsx` files however.

When first loading a `.tsx` file the syntax highlighting isn't right. The component tags are green and the html elements are displayed without the Dracula pink: 

<img width="475" alt="Screen Shot 2020-07-08 at 9 49 33 PM" src="https://user-images.githubusercontent.com/94547/86988281-e2d9be80-c165-11ea-9f36-9e8442bb3db5.png">

With the file above open, if I open any file with a `.js` extension, the Typescript file will refresh with the correct colors applied:

<img width="465" alt="Screen Shot 2020-07-08 at 9 50 14 PM" src="https://user-images.githubusercontent.com/94547/86988362-0e5ca900-c166-11ea-97a8-5ddbc1e382af.png">

Keep in mind, if I open a `.js` file first this issue doesn't happen. For background, I'm using the following plugins for JS and Typescript:

_HerringtonDarkholme/yats.vim
MaxMEllon/vim-jsx-pretty
pangloss/vim-javascript_

### What I expected to happen

Opening a Typescript file should render the colors correctly without a Javascript file being open.

### Machine Info
- Terminal Vim
- 8.2.1150
- MacOS 10.15.5
- iTerm2

**Comment by benknoble** [comment]
@dsifford  could this be related to the recent PR?

**Comment by dsifford** [comment]
@benknoble Most likely. 

Thoughts @renatoagds?

**Comment by bdielman** [comment]
I believe it's related to the vim-jsx-pretty plugin in some way. Swapping that plugin out with something like mxw/vim-jsx fixes the issue. I remember seeing a related issue regarding typescript syntax highlighting and polyglot which uses vim-jsx-pretty.

That being said, vim-jsx-pretty does a better job of highlighting (save for the current issue) and is supported so I'm hopeful there's a fix.

**Comment by renatoagds** [comment]
@dsifford @bdielman I got a fix in #200 , can you test it?

The problem was related with `current_syntax` that `vim-jsx-pretty` changes for `typescript.tsx`.

In the latest PR I forgot to add a support in `typescriptreact.vim`

**Comment by dsifford** [comment]
Merged.

Thanks all 👍

**Comment by bdielman** [comment]
@renatoagds @dsifford @benknoble  - Fixed! Thanks for the quick turnaround!
