### ISSUE TITLE
set termguicolors shows all characters in white.

### ISSUE THREAD

**Issue by lucasmsoares96** [dracula/vim#201]
### What happened
set termguicolors shows all characters in white. Works normally in other color schemes.

### What I expected to happen
I expected the colored words to appear.

### Screenshot
![termguicolors](https://user-images.githubusercontent.com/60808407/87228480-ea70b180-c377-11ea-92c3-147efdeb309d.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.2
- **OS**:  Linux gentoo -- 17.1  5.7.7-gentoo-x86_64 -- GNU/Linux
- **Terminal/Terminal Emulator/VTE**: Simple Terminal (Suckless)
- **`TERM` environment variable**: st-256color

**Comment by benknoble** [comment]
Well, does your terminal emulator support 24-bit color? If not, setting `'termguicolors'` is bound to fail (sometimes even more disastrously). I don't know much about st, so you might need to check with its reference material. It could also be a matter of configuring the terminfo for your `TERM` properly

**Comment by dsifford** [comment]
Give this a look as well and let us know if any of these things solve your issue...

https://wiki.archlinux.org/index.php/St#Troubleshooting

**Comment by lucasmsoares96** [comment]
> Well, does your terminal emulator support 24-bit color? If not, setting `'termguicolors'` is bound to fail (sometimes even more disastrously). I don't know much about st, so you might need to check with its reference material. It could also be a matter of configuring the terminfo for your `TERM` properly

ST supports truecolor.
The set termguicolors works with the gruvbox color scheme.

**Comment by lucasmsoares96** [comment]
> Give this a look as well and let us know if any of these things solve your issue...
> 
> https://wiki.archlinux.org/index.php/St#Troubleshooting

Test the solutions but nothing worked.

**Comment by lucasmsoares96** [comment]
But it works normally with xterm.

**Comment by lucasmsoares96** [comment]
I managed to solve them with the commands below:

`
if exists('+termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
`
