### ISSUE TITLE
var and let keywords are not highlighted

### ISSUE THREAD

**Issue by LyapaPikka** [dracula/vim#202]
### What happened
Keywords `var` and `let` doesn't highlighted.

### What I expected to happen
Above keywords should be highlighted, like in Sublime, for example.

### Screenshot
![var_doesnt_highlighted](https://user-images.githubusercontent.com/52799939/87229963-fc794100-c3c5-11ea-92d4-5898c91d4708.jpg)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: gvim
- **Vim version**: 8.2
- **OS**: Microsoft Windows [Version 10.0.18363.900], 64 bit

**Comment by benknoble** [comment]
Are you using any syntax plugins for javascript? The default is rather bad--most people we see use pangloss/vim-javascript, at least as a base.

**Comment by LyapaPikka** [comment]
After installing pangloss / vim-javascript it became much better. The problem is resolved. Thank you.
![problem_solved](https://user-images.githubusercontent.com/52799939/87241277-dcd03000-c43a-11ea-9e49-28d7fadc002f.jpg)
