### ISSUE TITLE
Error detected while processing ~/.vim/pack/themes/start/dracula/colors/dracula.vim

### ISSUE THREAD

**Issue by tophermckee** [dracula/vim#205]
### What happened
dracula does not install properly?
### What I expected to happen
dracula to run correctly
### Screenshot
![image](https://user-images.githubusercontent.com/65197302/88442777-64268780-cddb-11ea-9ee2-46317ba5af45.png)

### Machine Info
Intel i7-8700
- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.1
- **OS**: Pop OS 20.04
- **Terminal/Terminal Emulator/VTE**: Terminal
- **`TERM` environment variable**:

**Comment by benknoble** [comment]
🤔Hm... I know I've seen that error message before. Need to track it down. In the meantime, could you give us some more information about your installation method ? It almost looks like there is an issue processing the line continuations.

**Comment by tophermckee** [comment]
Yep no problem. I installed using the directions on the Dracula website. These errors seemed to be pointing straight to the GitHub clone, which really threw me.

**Comment by benknoble** [comment]
It looks like there are more errors at the top ; can you copy paste the full error messages?

**Comment by tophermckee** [comment]
Welp I opened up Linux again to copy it, but it won't show the error anymore. And yet, the dracula theme doesn't work when I open vim. I'm gonna close this so yall can move on to better things. Dracula shows randomly depending on how I open vim. `sudo vim` shows dracula, but opening with `vim [file_name]` normally doesn't.

**Comment by benknoble** [comment]
Hm. Could be a file permissions thing or something. Generally ` sudo vim` is discouraged because it can do that--I've found `sudoedit` works better with `EDITOR` exported. 

At any rate, we will be happy to help you resolve this if you like!

**Comment by tophermckee** [comment]
Fair enough yeah I've gotten past the error somehow. I am, however, curious why it looks like this:

![image](https://user-images.githubusercontent.com/65197302/88471067-12a8f600-ceca-11ea-9380-07db82487ea5.png)

This might help figure out what the issue is. I've also gotten vundle up and running so maybe I'll try that direction.

**Comment by tophermckee** [comment]
Okay hang on a sec haha I got it a little better using vundle. String literals still aren't highlighted. Is this just a limitation of vim?

![image](https://user-images.githubusercontent.com/65197302/88471324-dc6d7580-cecd-11ea-9199-318a8b6665a3.png)

**Comment by tophermckee** [comment]
Okay wanna put a wrap on this for you. Installing with Vundle worked almost perfectly. For some reason, remove the `, { 'name': 'dracula' }` from the line made it work without error. We'll see if this becomes a long term issue. I'm using another bundle to highlight string literals. Love this theme and I appreciate your help (: not gonna lie, I was gonna abandon learning vim if I couldn't use a functional theme.

![My garbage code](https://user-images.githubusercontent.com/65197302/88484472-356ff480-cf34-11ea-850e-33e8c6e432d8.png)

**Comment by benknoble** [comment]
FWIW, what you're referring to as string-literals I would refer to as interpolated strings; strings are generally yellow in dracula (and we make no special efforts to highlight inside them, so plugin is probably needed there—out of curiosity, which one are you using?).

That is odd that removing the naming was necessary. But glad you were able to get it to work!

**Comment by tophermckee** [comment]
cool thanks! I'm always learning new stuff
[https://github.com/vim-python/python-syntax](Here's) the plugin I'm using and it's likewise installed through vundle.

I really appreciate your time (:
