### ISSUE TITLE
[request] Dim lisp brackets

### ISSUE THREAD

**Issue by p00f** [dracula/vim#207]
https://github.com/srcery-colors/srcery-vim dims lisp brackets, can this be added to dracula?

(https://github.com/srcery-colors/srcery-vim#configuration)
(https://raw.githubusercontent.com/srcery-colors/srcery-assets/master/vim/lisp.png)

**Comment by benknoble** [comment]
I'm not sure about adding this to dracula directly, but one solution is this:

```vim
" ~/.vim/after/syntax/clojure.vim
if ! dracula#should_abort('clojure') || ! dracula_pro#should_abort('clojure')
  hi link clojureParen DraculaSubtle
endif
```

and

```vim
" ~/.vim/after/syntax/lisp.vim
" My lispParen group introduced in the runtime update prior to this patch
if ! has("patch-8.1.1715")
  if ! get(g:, 'lisp_rainbow', v:false)
    " override to make customizing parens easier
    syn region lispList matchgroup=lispParen start="(" skip="|.\{-}|" matchgroup=lispParen end=")" contains=@lispListCluster

    " Default behavior
    hi def link lispParen Delimiter
  endif
endif

if ! dracula#should_abort('lisp') || ! dracula_pro#should_abort('lisp')
  hi link lispParen DraculaSubtle
endif
```

And you can spot the pattern for other lisp dialects (e.g., for scheme/racket, the correct group is `schemeParentheses`)

**Comment by benknoble** [comment]
You could also theoretically use an autocommand on the colorscheme, if you're not sure to have dracula installed. But I think  a try/catch or a `:silent!` might be better then.

**Comment by p00f** [comment]
Thanks, i'll try this

**Comment by p00f** [comment]
Thanks, it works for clojure

Can you please explain what
```vim
  if ! get(g:, 'lisp_rainbow', v:false)
    " override to make customizing parens easier
    syn region lispList matchgroup=lispParen start="(" skip="|.\{-}|" matchgroup=lispParen end=")" contains=@lispListCluster

    " Default behavior
    hi def link lispParen Delimiter
  endif
``` 
does?

Also, how do I find the highlight group for other lisps?

**Comment by p00f** [comment]
Thanks, it works for clojure

Can you please explain what
```vim
  if ! get(g:, 'lisp_rainbow', v:false)
    " override to make customizing parens easier
    syn region lispList matchgroup=lispParen start="(" skip="|.\{-}|" matchgroup=lispParen end=")" contains=@lispListCluster

    " Default behavior
    hi def link lispParen Delimiter
  endif
``` 
does?

Also, how do I find the highlight group for other lisps?

**Comment by benknoble** [comment]
That code block was necessary before a patch I wrote for the lisp syntax file was added to vim. The patch defines the syntax item `lispParen` much as you see here; there's an extra guard to avoid doing that if you set the `lisp_rainbow` variable (which is a default feature of the lisp syntax file), since at that point you need the rainbow pieces and not my `Delimiter` override. 

> Also, why is `clojureParen` case-insensitive?

Not sure what you mean?

**Comment by p00f** [comment]
>That code block was necessary before a patch I wrote for the lisp syntax file was added to vim. The patch defines the syntax item lispParen much as you see here; there's an extra guard to avoid doing that if you set the lisp_rainbow variable (which is a default feature of the lisp syntax file), since at that point you need the rainbow pieces and not my Delimiter override.

:+1:
>Not sure what you mean?

it works even if i write `cLoJuRePaReN` instead of `clojureParen`

**Comment by benknoble** [comment]
Just found this buried in the help for syntax:

> Note that highlight group names are not case sensitive.  "String" and "string"
can be used for the same group.

**Comment by p00f** [comment]
can i increase the visibility slightly? currently it matchesthe visibility of `listchar`s

sorry for all the trouble

**Comment by p00f** [comment]
> Just found this buried in the help for syntax:
> 
> > Note that highlight group names are not case sensitive.  "String" and "string"
> > can be used for the same group.

oh

**Comment by benknoble** [comment]
You could use any highlight group you want; I just picked `DraculaSubtle` because that's what I use (I ripped this right from my config). I like it that dim, but YMMV 🤷‍♂️

**Comment by p00f** [comment]
How would I do that?
Changing it simply turns them normal white

ie
```vim
"~/.local/share/nvim/site/after/syntax/fennel.vim
if ! dracula#should_abort('fennel')
  hi link fennelParen guifg=#000000
endif
```
results in 
![image](https://user-images.githubusercontent.com/36493671/91643215-d3cd0980-ea4e-11ea-89a9-1e0441b9ebe1.png)

**Comment by benknoble** [comment]
Well, `hi link` uses an existing highlight group. You need `hi` (or possibly `hi!`) to use completely new attributes.

**Comment by p00f** [comment]
Thank you so much
