### ISSUE TITLE
digraphs hard to read

### ISSUE THREAD

**Issue by dubst3pp4** [dracula/vim#210]
### What happened

When using `:digraphs` the listed special characters are in dark grey and thus very hard to read.

### What I expected to happen

The usage of a more lighter color for the special characters.

### Screenshot

![Bildschirmfoto von 2020-10-06 11-00-53](https://user-images.githubusercontent.com/2373731/95181326-6d60a700-07c3-11eb-9d95-b3086d04cbfd.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: gvim
- **Vim version**: 8.2 Patch 1-1767
- **OS**: Linux 5.4.0-48-generic 52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dubst3pp4** [comment]
I think the syntax group is `SpecialKey` - I had the same issue with another color scheme (see https://github.com/haishanh/night-owl.vim/commit/18b6261656e6909ea93026de7eecdbe68686c3a9).

**Comment by benknoble** [comment]
I agree this is hard to read; same issue exists for the output of `:map` family, IIRC. 

Open to suggestions... @dsifford ?

**Comment by dsifford** [comment]
These show up red for me...

![image](https://user-images.githubusercontent.com/5240018/95208841-a266fc80-07b7-11eb-9ed7-059fc5d7f14c.png)

**Comment by dubst3pp4** [comment]
@dsifford that's strange. When I execute `:highlight SpecialKey` I get the following:
```
SpecialKey     xxx term=bold ctermfg=81 guifg=Cyan
                   links to DraculaSubtle
```
I don't know what this means exactly...

**Comment by dsifford** [comment]
I'm using neovim. Not sure if they treat digraphs differently.

**Comment by benknoble** [comment]
@dsifford they do; we saw this come up once before I think.

`colors/dracula.vim` roughly line 250:
```
" Neovim uses SpecialKey for escape characters only. Vim uses it for that, plus whitespace.
if has('nvim')
  hi! link SpecialKey DraculaRed
  hi! link LspDiagnosticsUnderline DraculaFgUnderline
  hi! link LspDiagnosticsInformation DraculaCyan
  hi! link LspDiagnosticsHint DraculaCyan
  hi! link LspDiagnosticsError DraculaError
  hi! link LspDiagnosticsWarning DraculaOrange
  hi! link LspDiagnosticsUnderlineError DraculaErrorLine
  hi! link LspDiagnosticsUnderlineHint DraculaInfoLine
  hi! link LspDiagnosticsUnderlineInformation DraculaInfoLine
  hi! link LspDiagnosticsUnderlineWarning DraculaWarnLine
else
  hi! link SpecialKey DraculaSubtle
endif
```

**Comment by dsifford** [comment]
Ah, gotcha...

Is `SpecialKey` what is used for listchars in regular vim? That would have been the reason why it was linked to the subtle color IIRC.

Because whitespace should definitely not overpower the color of code.

**Comment by benknoble** [comment]
Yeah `listchars` gets `SpecialKey`, unfortunately. `DraculaRed` isn't terrible for trailing whitespace, but that's not the only thing it gets used for. I wonder if we can fix this in vim. What does neovim use for listchars?

**Comment by benknoble** [comment]
Just found this:
```
<	The "NonText" highlighting will be used for "eol", "extends" and
	"precedes".  "SpecialKey" for "nbsp", "space", "tab" and "trail".
	|hl-NonText| |hl-SpecialKey|
```
So NonText is relevant too

**Comment by benknoble** [comment]
Hi @dubst3pp4, I'm looking for feedback on #252 which should help solve this problem. Any thoughts, positive or negative?
