### ISSUE TITLE
Background color problem with Hyper

### ISSUE THREAD

**Issue by lipenodias** [dracula/vim#211]
I have problem with background color of Dracula theme for VIM when use the Hyper

my vimrc file on ~

felipe@lipe-linux:~$ cat .vimrc
set termguicolors
packadd! dracula
syntax enable
colorscheme dracula

my .vim folder

felipe@lipe-linux:~$ ls -l .vim/pack/themes/opt/dracula/
total 556
drwxrwxr-x 4 felipe felipe   4096 out 15 11:42 after
drwxrwxr-x 4 felipe felipe   4096 out 15 11:42 autoload
drwxrwxr-x 2 felipe felipe   4096 out 15 11:42 colors
drwxrwxr-x 2 felipe felipe   4096 out 15 11:42 doc
-rw-rw-r-- 1 felipe felipe   2062 out 15 11:42 INSTALL.md
-rw-rw-r-- 1 felipe felipe   1080 out 15 11:42 LICENSE
-rw-rw-r-- 1 felipe felipe   1189 out 15 11:42 README.md
-rw-rw-r-- 1 felipe felipe 539018 out 15 11:42 screenshot.png

Attachment to comparison print with VIM directly from the terminal and Hyper VIM

![2020-10-15_12-55](https://user-images.githubusercontent.com/64644915/96155758-aea13700-0ee6-11eb-831b-51f75390456f.png)

**Comment by benknoble** [comment]
Sorry, what's Hyper Vim? I'm aware of a terminal emulator named Hyper; is that what you mean?

In any case, see `:help dracula-configuration` for information about `g:dracula_colorterm`, which you may want to set to `0`.

**Comment by lipenodias** [comment]
> Sorry, what's Hyper Vim? I'm aware of a terminal emulator named Hyper; is that what you mean?
>  yes is Hyper --> hyper.is/
> In any case, see `:help dracula-configuration` for information about `g:dracula_colorterm`, which you may want to set to `0`.
Do where I find this configuration?

**Comment by benknoble** [comment]
> Do where I find this configuration?

You just need to `let` the variable *before* you call `colorscheme dracula`. Your vimrc would be a typical place for it:

```
set termguicolors
packadd! dracula
syntax enable
let g:dracula_colorterm = 0
colorscheme dracula
```

**Comment by lipenodias** [comment]
> > Do where I find this configuration?
> 
> You just need to `let` the variable _before_ you call `colorscheme dracula`. Your vimrc would be a typical place for it:
> 
> ```
> set termguicolors
> packadd! dracula
> syntax enable
> let g:dracula_colorterm = 0
> colorscheme dracula
> ```

Its working!!! Thanks!!!
