### ISSUE TITLE
no function name highlight.

### ISSUE THREAD

**Issue by lucasmsoares96** [dracula/vim#214]
### What happened
My vim colors don't match that of the dracula theme image.

### What I expected to happen
I expected the colors of the image on the dracula theme website to be the same as the colors in my vim.

### Screenshot

on the left is the image of the dracula repository and on the right is my vim.
![image](https://user-images.githubusercontent.com/60808407/96947056-725a7180-14b8-11eb-9f28-eaa0db7225f8.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: neovim
- **Vim version**: NVIM v0.5.0-718-g090551a80
- **OS**: Linux ArchLinux 5.8.14-arch1-1
- **Terminal/Terminal Emulator/VTE**: st (suckless simple terminal)
- **`TERM` environment variable**: st-256color

**Comment by dsifford** [comment]
Default javascript syntax is extremely basic.

Try installing https://github.com/pangloss/vim-javascript

**Comment by lucasmsoares96** [comment]
> Default javascript syntax is extremely basic.
> 
> Try installing https://github.com/pangloss/vim-javascript

Perfect!! Thank you.
