### ISSUE TITLE
Neovim terminal colors?

### ISSUE THREAD

**Issue by Moshem123** [dracula/vim#220]
### What happened
I think it'd be cool to add neovim's terminal_colors:
```
let g:terminal_color_0 = ????
let g:terminal_color_1 = ????
let g:terminal_color_2 = ????
let g:terminal_color_n = ????
```
Based on `has('nvim')`.
Thanks

**Comment by dsifford** [comment]
Already exists! :stuck_out_tongue_closed_eyes: 

See https://github.com/dracula/vim/blob/ba00ac0432541811955e50b8420c25b22762c7c9/colors/dracula.vim#L56-L60
