### ISSUE TITLE
Syntax highlighting is wildly different depending on where I open vim and what I open

### ISSUE THREAD

**Issue by multiMhine4** [dracula/vim#221]
### What happened
I installed the dracula plugin into my .vimrc file, set colorscheme dracula, but then
when I open a ***.tex file with vim, a couple of colours seem to be missing in the 
syntax highlighting (like green and yellow). The colours are as close to what it should
be only when I open the .vimrc file, and that's it.

I tried using vim in other ways:

1. nvim: Before configuring the init.vim file as required by :h nvim-from-vim, the 
highlighting was immediately better. But after configuring it, it immediately went
back the normal worse state.

2. macvim: Opening the ***.tex file still gives the same colours, but opening .vimrc
gives the _exact_ colours as  promised in the dracula colorscheme. 

### What I expected to happen
I expected the syntax highlighting to have all the colours of the dracula colorscheme
when opening files. I don't know whether the vim startup menu is affected, because
it only ever showed white and darkblue text.

### Screenshot
Highlighting in the tex file using Terminal.app with vim (same with nvim after init.vim, and macvim)
<img width="1440" alt="Screenshot 2020-12-21 at 9 06 08 PM" src="https://user-images.githubusercontent.com/61251201/102780111-5b5cd080-43d0-11eb-9489-3183de9b8cdb.png">

Highlighting in the tex file using Terminal.app with nvim (before init.vim)
<img width="1440" alt="Screenshot 2020-12-21 at 9 08 08 PM" src="https://user-images.githubusercontent.com/61251201/102780333-b0004b80-43d0-11eb-83ac-57f3502b3f81.png">

.vimrc in macvim 
<img width="413" alt="Screenshot 2020-12-21 at 9 04 37 PM" src="https://user-images.githubusercontent.com/61251201/102780024-32d4d680-43d0-11eb-80e9-6dfec2d5f34d.png">

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: vim / neovim
- **Vim version**: 8.2.850      
- **OS**: Darwin TimTims-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64
- **Terminal/Terminal Emulator/VTE**: Terminal.app
- **`TERM` environment variable**: xterm-256color

**Comment by multiMhine4** [comment]
I think I accidentally solved the problem. It was likely a conflict between the Terminal colors and the vim colorscheme, both of which I tried to set to dracula. If I just use the default colorscheme while using dracula for the Terminal, everything goes perfectly

**Comment by benknoble** [comment]
The first screenshot looks more or less correct (though if the blue-standout annoys you, see `:help dracula_italic`).

The second screenshot is actually just `:colorscheme default` with `set background=dark`, so it's a red-herring.

The vimrc also looks correct.

---

At the end of the day, it's a mix of how the syntax highlighting is defined and what groups dracula links specially. Some syntaxes have more than others. Here's a random shot of a tex file with some more color:

![Capture d’écran 2020-12-21 à 10 41 30](https://user-images.githubusercontent.com/22802209/102794252-1b1e3380-4379-11eb-92f9-3cd51ce4e12d.png)

I am using the Terminal.app dracula palette (or at least some variant of it), which I also maintain.
