### ISSUE TITLE
color support in .vue files

### ISSUE THREAD

**Issue by AdamBD** [dracula/vim#223]
Hi there,

Here is an example from a .vue file in a project of mine:
![image](https://user-images.githubusercontent.com/1134525/103107052-77b47380-4643-11eb-9657-3c2c71c6ef78.png)

Is this how JS is supposed to be colored with dracula? Its rather hard to distinguish object properties from function declarations etc. (Though those are admittedly object properties here)

wondering if there is a way to adjust this?

**Comment by dsifford** [comment]
Hi @AdamBD.

I think this issue is due to the fact that the default javascript syntax kinda sucks in vim. 

Try installing https://github.com/pangloss/vim-javascript and let me know if that resolves your issue.

**Comment by benknoble** [comment]
Possibly related issues: https://github.com/dracula/vim/issues?q=is%3Aissue+js+is%3Aclosed

**Comment by AdamBD** [comment]
@dsifford brilliant! thank you very much :)
