### ISSUE TITLE
Tweaking the theme slightly?

### ISSUE THREAD

**Issue by FrankDMartinez** [dracula/vim#228]
Hi,

Dracula is a really good theme; thanks for making it. For my own personal tastes, there are couple of tiny tweaks I would like to make to my copy. Is there a guide how to do so in a way, should I copy this theme to another computer, those tweaks will come along with?

I might have missed this in the documentation and, if I did, I do apologize.

Thanks in advance.

**Comment by benknoble** [comment]
Well, an easy way is to add something like

```vim
augroup dracula_customization
  autocmd!
  " autocmds...
augroup END
```

with autocommands like

```vim
autocmd ColorScheme dracula highlight CursorLine cterm=underline term=underline
```

or whatever customization you want to do. This can be done in your vimrc, for example (cf. `:help dracula-customization` and `:help :highlight`).

---

If you want to got deeper, I would just fork the source

**Comment by benknoble** [comment]
Closing unless there are further questions.
