### ISSUE TITLE
Black highlighting on text outside of window

### ISSUE THREAD

**Issue by JohnClient** [dracula/vim#229]
I am using the dracula colorscheme on vim on ubuntu. When I load an existing file any text that doesn't initially fit into the window will have a strange black highlight on any space without a character. I only have one colorscheme enabled and it definitely is an issue with this colorscheme. It is annoying as opposed to unusuable but would really appreciate a fix.
I've attached a screenshot of what this looks like.
![draculacsissue ](https://user-images.githubusercontent.com/80011800/109966989-cab44200-7ce8-11eb-997b-7b700e6cc215.png)

**Comment by benknoble** [comment]
You might need to toggle on or off `g:dracula_colorterm` before loading the colorscheme.

It could also be an issue with `$TERM` or `:highlight Normal`.

**Comment by benknoble** [comment]
Closing this; if unresolved, please let us know.
