### ISSUE TITLE
Treesitter settings cannot be adjusted in init.vim

### ISSUE THREAD

**Issue by inventionate** [dracula/vim#231]
### What happened

I'm using the recently merged Treesitter support (#230). Thanks for that! Unfortunately, I can't change the colours in my init.vim. `highlight link TSError Normal` is unfortunately overwritten. I think this is especially annoying in the case of the live syntax errors. 

The problem has also been discussed elsewhere: https://github.com/nvim-treesitter/nvim-treesitter/issues/119

### What I expected to happen / possible solution

The solution is to use 'hi default link TSError ErrorMsg' instead of, for example, 'hi! link TSError ErrorMsg' (see https://github.com/nvim-treesitter/nvim-treesitter/pull/121). I would therefore advocate adapting all settings accordingly so that users can simply adapt them to their own needs.

### Screenshot

<img width="837" alt="Bildschirmfoto 2021-03-08 um 11 33 52" src="https://user-images.githubusercontent.com/872787/110310821-44a73c80-8003-11eb-94e5-3beb4923a66b.png">

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: neovim
- **Vim version**: v0.5.0-dev+nightly-507-gc12ea02e0
- **OS**: Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- **Terminal/Terminal Emulator/VTE**: iTerm2
- **`TERM` environment variable**: xterm-256color

**Comment by benknoble** [comment]
Perhaps a better option is for your customization to be applied when the colorscheme changes: for that, use an autocommand.

```vim
augroup my_treesitter_overrides
  autocmd!
  autocmd ColorScheme dracula highlight …
augroup END
```

(Use `*` instead of `dracula` if you prefer.)

**Comment by inventionate** [comment]
Thank you very much for your fast answer! Unfortunately, the autocommand solution does not seem to work. I cannot change TSError.

**Comment by dsifford** [comment]
@inventionate can you paste your snippet that you tried?

**Comment by benknoble** [comment]
I'm also not sure we should `:highlight default` those groups; that could cause unexpected issues elsewhere (e.g., other plugins)

**Comment by inventionate** [comment]
I tried many different commands inside the augroup, e. g.:

```vim 
  autocmd ColorScheme dracula highlight TSError guibg=#282A36 guifg=#282A36
```
```vim 
autocmd ColorScheme dracula highlight link TSError Normal
```

```vim 
autocmd ColorScheme dracula highlight TSError guibg=NONE guifg=NONE
```

Maybe I missed something?

**Comment by dsifford** [comment]
@inventionate add an exclamation mark after the word highlight.... (i.e. `highlight!`)

**Comment by inventionate** [comment]
Sorry that I haven't mentioned every try ;-) I already added an exclamation mark for different attempts, but no luck.

**Comment by dsifford** [comment]
can you try not doing the autocmd approach and just adding the highlight call after you load the colorscheme?

difficult to help repro since I don't have the git version of neovim installed

**Comment by benknoble** [comment]
I'm shocked that none of those worked. Can you use `*` instead of `dracula` and do the various `!`/after/etc. tests? I know it's a long-shot, but that kind of thing works fine for me when I adjust, say `Comment` or some other group.

Also, _maybe_, `:verbose highlight TSError` will have something interesting?

**Comment by DerekStride** [comment]
Thanks for the descriptive issue @inventionate, I admit that the experience provided by linking `TSError` to `ErrorMsg` is not ideal, I've put up a change to undo that in #232.

However, I suspect from this thread that your configuration may have some other bug. I was able to add `highlight link TSError Normal` to my `init.vim` and have the change apply correctly. In the mean time #232 should be a bandaid to remove the poor default experience.

**Comment by inventionate** [comment]
First of all, thank you very much for the changes! I think this is a much better default configuration.

Unfortunately, I can not detect a misconfiguration in my case. I recompiled Neovim and the Treesitter packages again and just loaded the following minimal example as init.vim. When I use the Dracula theme before the merge, the highlighting setting is ignored, i. e. the image above is still current.

```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

call plug#end()

lua << EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "php"
    },
    highlight = {
        enable = true
    },
    indent = {
        enable = true
    }
}
EOF

color dracula

highlight link TSError Normal
```

**Comment by DerekStride** [comment]
I've done some further debugging and the issue from the example `init.vim` file you gave above is because of the dracula config for treesitter exists in the `after/` directory and is appended to the end of the `runtimepath`. This is an excerpt from the help docs for `:highlight-link`.

```md
- As soon as you use a ":highlight" command for a linked group, the link is removed.
```

This means that which link command is run last is the winner. So we need the customization from the above example to run after the dracula config otherwise it will be overridden by the `after` hook. The below additions  to your example `init.vim` file fixed the issue for me.

```vim
"~/.config/nvim/init.vim
set rtp+=~/.dotfiles/nvim/runtime/after
```

```vim
"~/.dotfiles/nvim/runtime/after/plugin/derek.vim
hi! link TSError Normal
```

**Comment by inventionate** [comment]
Yes, that works. Many thanks! But it also means that an override is a bit more involved and can't simply be set in init.vim. Anyway, the default settings are now suitable, so it isn't needed ;-) Thanks again! I close the issue now.

**Comment by benknoble** [comment]
Would it not work to put it in the equivalent of `~/.vim/after/plugin/treesitter.vim`, which is already on the runtimepath and should be last? That is, no need to create an extra special directory
