### ISSUE TITLE
Stausline is still gruvbox

### ISSUE THREAD

**Issue by etrigan63** [dracula/vim#233]
### What happened
Installed dracula theme in Spacevim/Neovim. Body is themed but stausline is still gruvbox.
### What I expected to happen
Stausline is dracula themed.
### Screenshot
https://i.imgur.com/MuNp3iY.png
### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**:neovim
- **Vim version**:0.4.4
- **OS**: Linux ironforge 5.11.4-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 07 Mar 2021 18:00:52 +0000 x86_64 GNU/Linux
- **Terminal/Terminal Emulator/VTE**: kitty
- **`TERM` environment variable**: screen-256color

**Comment by benknoble** [comment]
Looks like airline? AFAIK you have to change the airline theme separately; we do actually ship with one.

**Comment by etrigan63** [comment]
Not that I know of. It says "statusline" in the config file.

**Comment by dsifford** [comment]
Ya this is definitely a configuration issue if you use airline.

**Comment by benknoble** [comment]
Well, I don't know much about spacevim. But again, I suspect it's airline or a similar statusline plugin, and you'll need to configure it (somehow, perhaps ask those folks?) to use dracula. We do provide a couple of themes for popular status lines (airline and lightline, I believe).

(FWIW Seasoned vimmers recommend making your own config, so that you understand it.)

**Comment by etrigan63** [comment]
thedelchop has a dracula-vim project here that has the statusline but I have no idea how to use it as it seems to have been adopted by you guys.

**Comment by benknoble** [comment]
Perhaps you need to try `:AirlineTheme dracula` or similar. I'll leave this open pending a response

**Comment by urienix** [comment]
@benknoble it works for me

only add `let g:airline_theme = 'dracula'` to `.vimrc`
![image](https://user-images.githubusercontent.com/20466553/148664270-f360343f-59d0-4411-9fc0-f9a5eebfd4de.png)
