### ISSUE TITLE
Can we make texRefZone Special again?

### ISSUE THREAD

**Issue by benknoble** [dracula/vim#235]
### What happened

I'm editing a LaTeX document, and all the `\cite` commands are the same color as the body text. This has been true for a while (the relevant commit is 72a0d0d584e2b64dd7cd44047688d470e6e39f8f from 2018).

### What I expected to happen

I'm pretty used to the commands being a different highlighting, so:
```latex
\section{Highlighted}
\cite{not_highlighted} % in vim, but in GitHub it is
```

Just requires to remove the `hi! link texRefZone` in `after/syntax/tex.vim`; the default syntax sets it to `Special`.

### Screenshot

<img width="521" alt="Capture d’écran 2021-03-18 à 09 39 26" src="https://user-images.githubusercontent.com/22802209/111635492-ebdb5f00-87cd-11eb-993c-a41c02bc65b4.png">

vs.

<img width="521" alt="Capture d’écran 2021-03-18 à 09 39 37" src="https://user-images.githubusercontent.com/22802209/111635506-f0077c80-87cd-11eb-9b94-20589e975351.png">

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: `vim`
- **Vim version**: 8.2.2300
- **OS**: macOS
- **Terminal/Terminal Emulator/VTE**: Alacritty
- **`TERM` environment variable**: tmux-256color

### Additional Info

`tmux info` shouldn't be relevant, but will include if necessary

**Comment by dsifford** [comment]
Assuming this only impacts LaTeX? If so, go for it.
