### ISSUE TITLE
Active split tab highlight is misleading

### ISSUE THREAD

**Issue by clobrano** [dracula/vim#239]
### What happened
When opening a buffer in a split, the highlighted "tab" is not the one of the buffer with the focus

### What I expected to happen
The buffer's tab with focus has a color/style that makes it more visible than any other open buffer.

### Screenshot
In this screenshot, the buffer on the right side (LICENCE) has the focus, however it's the buffer's tab on the left side (dracula.vim) that looks highlighted, which seems a bit misleading to me.

![image](https://user-images.githubusercontent.com/2883614/113834947-b18d2e00-978b-11eb-9422-725616301a69.png)

### Machine Info
- neovim 0.4.3
- Ubuntu 20.04
- Gnome Terminal
- TERM=screen-256color

- **Vim type (`vim`/`gvim`/`neovim`)**:
- **Vim version**:
- **OS**:
- **Terminal/Terminal Emulator/VTE**:
- **`TERM` environment variable**:

**Comment by benknoble** [comment]
How is your tabline setup? The statusline is quite clear on which buffer is active; but your tabline is showing buffers/splits, rather than tabs? Unless in fact you have multiple tabs open (`gt`).

**Comment by clobrano** [comment]
I didn't think this was due to a combination of plugins. I use [buftabline](https://github.com/ap/vim-buftabline) to show buffers in the tabline and it uses PmenuSel for the non-focused buffer split, which is unfortunate because it looks way more "selected" than in-focus buffer split, but it is not a dracula's problem.

Thanks for the quick reply :)

**Comment by benknoble** [comment]
Heh, yeah, it's called `PMenuSel`—it has "selected" in the name. Probably a bad choice on the part of the plugin.
