### ISSUE TITLE
Vim Color Scheme not working on MacOS Terminal (while using VIM)

### ISSUE THREAD

**Issue by zuluworm** [dracula/vim#246]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

I followed the directions to load the dracula package but the theme is not showing as depicted in the screenshot when using VIM to edit a .JS file.  I am using VIM 8 on the MacOS terminal (Version 2.11 (440)) using BigSur 11.2.3.  Please see below the screenshot as well as my .vimrc file:

packadd! dracula
syntax enable
let g:dracula_italic = 0
colorscheme dracula

<img width="770" alt="Screen Shot 2021-04-20 at 9 03 52 AM" src="https://user-images.githubusercontent.com/76982454/115400712-9bce2e80-a1b7-11eb-9fdf-e51db9eda497.png">

**Comment by benknoble** [comment]
This isn't Terminal specific, I don't think, especially with that transparent background.

Note the following in the vim readme:
> Screenshot taken with the [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) syntax plugin for javascript.

**Comment by zuluworm** [comment]
> This isn't Terminal specific, I don't think, especially with that transparent background.
> 
> Note the following in the vim readme:
> 
> > Screenshot taken with the [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) syntax plugin for javascript.

Ben, Im a bit confused, do I need to install both dracula and pangloss together?

**Comment by benknoble** [comment]
Pangloss's JS plugin is optional, but provides better syntax rules. We provide highlighting definitions, which are orthogonal. 

If you want something like the screenshot, you'll need both, as we won't incorporate syntax rules here. But it's not necessary if you're comfortable with the default JS syntax rules or use a different plugin for them.
