### ISSUE TITLE
Strange pink highlight in some words - is this by design?

### ISSUE THREAD

**Issue by gregth** [dracula/vim#248]
### What happened
Some words in vim appear highlighted with pink color. For example, when using Tagbar plugin for `go` language outline, or at the intro screen of VIM. 

### What I expected to happen
This highlight is irritating, is this a bug or just a design decision?

### Screenshot
At right bottom is the Tagbar with the pink highlights:
![image](https://user-images.githubusercontent.com/8137385/117427645-eaa4f380-af2d-11eb-8ebc-e05c9e23ff6b.png)

Another case, at the vim intro screen:
![image](https://user-images.githubusercontent.com/8137385/117428675-f47b2680-af2e-11eb-8772-5fd4bd299468.png)

The following screenshot is what I get when I run vim without loading plugins, which means with Dracula for vim disabled (still I have Dracula theme for my gnome-terminal enabled): 

![image](https://user-images.githubusercontent.com/8137385/117427938-39eb2400-af2e-11eb-8f73-f8ba94b30411.png)

### Machine Info
Linux Dellis 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: VIM - Vi IMproved 8.0
- **OS**: Ubuntu 18.04
- **Terminal/Terminal Emulator/VTE**: gnome-terminal
- **`TERM` environment variable**: screen

**Comment by benknoble** [comment]
Hmm, looks like the `SpecialKey` might be off--do you change that in your config? Could another plugin? Try `:verbose highlight SpecialKey`

**Comment by benknoble** [comment]
Unfortunately for the moment, this is "intended"… due to a quirk (I'll try to dig up issue references) that neovim & vim use (slightly) different highlight groups for trailing whitespace, which we would like to be more subtle. Vim uses SpecialKey, which *also* get's used for stuff like `<CR>`/etc. (the output of `:map` is also not-fun if you have special keys). NeoVim, IIUC, uses a different group, so we can style the trailing whitespace separately from the special keys. I *think* @dsifford uses NeoVim and can give more context on this.

If you really don't like it, one simple fix is
```vim
augroup dracula_custom
  autocmd!
  autocmd ColorScheme dracula highlight link SpecialKey DraculaPink
augroup END
```
(or whatever your preferred color is)

**Comment by dsifford** [comment]
@benknoble Neovim uses `SpecialKey` exclusively for non-printable characters and `Whitespace` for any other whitespace character highlighting (i.e. the `listchars`)

**Comment by benknoble** [comment]
@dsifford I would like to revisit the issues I linked above at some point (I think #210 is the most relevant). To me it's worth making vim's listchars stuff a little more visible if it makes other UI elements that use the same group easier to deal with. (And, note, vim doesn't use just `SpecialKey` but `NonText` for certain elements)

**Comment by dsifford** [comment]
Definitely open to making those changes. Happy to put our heads together if you want to get a PR started.

**Comment by benknoble** [comment]
Hi @gregth, I'm looking for feedback on #252, which should help ameliorate that "hard to read grey" in some places. Any thoughts, positive or negative?

**Comment by benknoble** [comment]
I think this is resolved, so I'll close it for now. Let us know if it is not resolved.

**Comment by gregth** [comment]
@benknoble I apologize, I missed the notification for your mention. 
I just pull the latest master commits, and the fix seems good!

Thank you for working on this!
