### ISSUE TITLE
What is the font in screenshot.png?

### ISSUE THREAD

**Issue by mysteryjeans** [dracula/vim#249]
What is the font in [screenshot.png](https://github.com/dracula/vim/blob/master/screenshot.png)?

**Comment by benknoble** [comment]
I'm fairly certain it's Victor Mono (I took the shot but I don't remember when I switched to that font). I actually have italic comments, not shown in that screenshot.

**Comment by mysteryjeans** [comment]
I setting VictorMono Nerd Font Complete which as available as AUR in arch, it does look amazing. However I am not seeing class names or variable types being highlighted, is it suppose to look like that or ale linter isn't working?

![2021-05-09-004133_1600x900_scrot](https://user-images.githubusercontent.com/1826883/117551547-0c9e9300-b060-11eb-8ad6-a4cd38ce3abd.png)

**Comment by benknoble** [comment]
Unrelated to ale or us: the default c# syntax is kind of "meh". It gets better if you use OmniSharp, but that may or may not be worth it. https://github.com/OmniSharp/omnisharp-vim

**Comment by benknoble** [comment]
Here's the config I used in `~/.vim/after/plugin/config/omnisharp.vim` to use mono and co-operate with ALE (I don't remember what the stdio var is for)

```
if !exists('g:OmniSharp_loaded')
  finish
endif

let g:OmniSharp_server_stdio = 1
let g:OmniSharp_open_quickfix = 0
let g:OmniSharp_server_use_mono = 1

if exists('g:ale_linters')
  let g:ale_linters.cs = extend(
        \ get(
          \ g:ale_linters,
          \ 'cs',
          \ []),
        \ ['OmniSharp'])
endif
```
