### ISSUE TITLE
vim dracula not consistent with IDE

### ISSUE THREAD

**Issue by XDinEuro** [dracula/vim#250]
c++ code not fully colored.

I am using vim dracula for a long time and I really enjoy it. Recently I found out that the dracula in vs code is a bit different from in vim.

For example that same c++ code, 
in vim  functions are not highlighted with green color, and classes are not blue. 
![Screenshot from 2021-05-10 15-50-26](https://user-images.githubusercontent.com/51153761/117670090-dcfaa280-b1a7-11eb-8aa9-5320d40633c1.png)

But in vscode it does.
![Screenshot from 2021-05-10 15-48-57](https://user-images.githubusercontent.com/51153761/117670075-db30df00-b1a7-11eb-8a40-81bba85740be.png)

I am just using normal shell.

**Comment by dsifford** [comment]
@XDinEuro This is not an issue with the theme. Instead it's an issue with the syntax.

Vim is not equipped by default with a robust c/c++ syntax rules. If you feel the need to have those, you should be able to find some implemented as third-party plugins.

If you're not able to find any that you like for regular vim, the next version of neovim is shipping with a tree-sitter syntax parser, which will absolutely be able to highlight like vscode (actually, better).

Hope that helps.
