### ISSUE TITLE
[request] add documentation for configuration options

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [dracula/vim#261]
### Issue
There are certainly many ways to configure the Dracula theme, for example altering the text styles (bold, italic, underline).
However, they can only be found by digging through the theme's source files.

### Why
For beginners to Vim (or the Vim script, like me), this might pose a challenge, as they might not know where to look to configure this theme.

Perhaps adding documentation for configuration to the README / website would help to reduce the problem?

**Comment by dsifford** [comment]
@g-e-o-m-e-t-r-i-c All of the configuration settings should already be documented in the [doc/dracula.txt](https://github.com/dracula/vim/blob/master/doc/dracula.txt) file.

This is the canonical way of documenting vim plugins and can be accessed in vim simply by entering `:help dracula.vim`.

**Comment by benknoble** [comment]
Adding a pointer to the `:help` in the README would be a welcome contribution/PR. As dsifford points out, it's all already documented, so I'm going to close this.
