### ISSUE TITLE
Unexpected behavior when using Dracula theme with Neovim

### ISSUE THREAD

**Issue by helderburato** [dracula/vim#263]
### What happened

I installed the package following the README.md, but I have the following behavior when source my vim configs:

![vim-dracula](https://user-images.githubusercontent.com/862575/134241984-65b549eb-ff5b-4243-95fb-2c32eb3c9226.gif)

### What I expected to happen

I would like to have the correct theme, I think is the one that appears after source vim configs.

### Machine Info

- **Vim type**: neovim
- **Vim version**: NVIM v0.5.0
- **OS**: macOS
- **Terminal/Terminal Emulator/VTE**: Alacritty
- **`TERM` environment variable**: screen-256color

### Additional Info

My theme configurations for Neovim:
- [Neovim Config](https://github.com/helderburato/dotfiles/blob/main/nvim/.config/nvim/init.vim)

**Comment by helderburato** [comment]
Update: After I updated the theme to load after the call plugins end:
```
call plug#end()

" Theme
let g:dracula_italic = 0
if (has("termguicolors"))
  set termguicolors
endif
colorscheme dracula
```

After that, the colors look like:
<img width="1059" alt="Screenshot 2021-09-22 at 09 28 06" src="https://user-images.githubusercontent.com/862575/134309498-8ea5fd50-1a45-4d10-8a61-4b63f3ff5ca0.png">

Is this right? I was checking with the repository screenshot and the methods colors don't match.

Repository screenshot:
![VIM Dracula](https://raw.githubusercontent.com/dracula/vim/master/screenshot.png)

**Comment by helderburato** [comment]
VIM screenshot:
<img width="842" alt="Screenshot 2021-09-22 at 10 10 54" src="https://user-images.githubusercontent.com/862575/134316229-362e5447-e3d8-4541-957d-2a059d82c0d3.png">
:

VSCode screenshot:
<img width="744" alt="Screenshot 2021-09-22 at 10 11 56" src="https://user-images.githubusercontent.com/862575/134316334-d55a1b44-b4ba-49ad-a2e0-83d460c2572c.png">

---

@zenorocha @benknoble @dsifford could you help me to understand these differences between editors?

**Comment by helderburato** [comment]
Thanks for the reply @benknoble, I really didn't know about that. 
I'm using https://github.com/sheerun/vim-polyglot to the syntax support on Neovim.

I closed the other issues because it's related only to the Vim.

**Comment by benknoble** [comment]
I'm not 100% sure what's going on, but it's possible the tree-sitter is interfering.

Other comments:
- `TERM=screen-256color` seems odd to me. I have a `tmux-256color` profile that I use with tmux (and of course an alacritty profile for outside of that).
- You shouldn't have to explicitly `:source` stuff in `~/.vim/plugin`. See `:help startup` and `:help load-plugins`. There's also `:runtime`. cf. https://vi.stackexchange.com/q/9250/10604

Without more information about what's changing the colors, it's hard to do much. You could try the tips in [How to debug my vimrc](https://vi.stackexchange.com/q/2003/10604).

**Comment by helderburato** [comment]
@benknoble I didn't catch the last comment:
```
You shouldn't have to explicitly :source stuff in ~/.vim/plugin. See :help startup and :help load-plugins. There's also :runtime. cf. vi.stackexchange.com/q/9250/10604
```

What did you mean? Just to understand and update my configs. I'll check how to debug my configs as well.

**Comment by benknoble** [comment]
I was referring to parts of your vimrc (or init.vim or whatever it is). Anything in the plugin directories on the runtime path is automatically sourced after the vimrc.

**Comment by helderburato** [comment]
I changed all my configs, everything loading from the `init.vim`, but still with the same behavior.

You can look at my config [here](https://github.com/helderburato/dotfiles/blob/main/nvim/.config/nvim/init.vim).

**Comment by benknoble** [comment]
Still not sure what's happening, but did you try that debug link? Essentially you want to binary search by cutting half away at a time. You can also use other things (_e.g._, `vim --clean`) to see if that reproduces the problem, though then you'll have to do more steps to actually load the colorscheme

**Comment by dsifford** [comment]
If the error only shows up when you source the file, then why source the file? I honestly don't understand the problem here.

I, too, use neovim, alacritty, and tmux. No issue on my end.

**Comment by helderburato** [comment]
I’ll try it @benknoble.

——

> If the error only shows up when you source the file, then why source the file? I honestly don't understand the problem here.
> 
> I, too, use neovim, alacritty, and tmux. No issue on my end.

That’s what I’m been doing, but I just trying to figure out why it happens.

Could you share your dotfiles link? @dsifford

**Comment by dsifford** [comment]
[https://github.com/dsifford/.dotfiles](https://github.com/dsifford/.dotfiles)

**Comment by benknoble** [comment]
I also source my vimrc occasionally, but I actually have the `:colorscheme` bit in a `plugin` file, so it doesn't run more than once. Course, it's odd that it's not idempotent in some sense.

**Comment by helderburato** [comment]
Do you split your theme into something like “plug-in/theme.vim” to load just one time? @benknoble 

My theme is loaded like that but in a theme.lua file.

**Comment by benknoble** [comment]
https://github.com/benknoble/Dotfiles/blob/master/links/vim/plugin/plugin_load.vim

**Comment by helderburato** [comment]
Thanks for all your help @benknoble and @dsifford!

I made some updates in my config, based on your dotfile's and now it works fine. :D

If you would like to give any feedback or tips for improvements, It's public [here](https://github.com/helderburato/dotfiles/tree/main/nvim/.config/nvim).

I'll close the issue, considering the problem has already been solved.
