### ISSUE TITLE
Dracula doesn't recognize well the syntax in Neovim 0.5.1

### ISSUE THREAD

**Issue by aryklein** [dracula/vim#264]
Dracula theme for Vim doesn't recognize all the syntax and bolds as it's expected. That doesn't happen with the same Neovim setup in gruvbox. If I just switch in live `colorscheme` to gruvbox (community) it works fine.

You will notice what I mentioned in the following screenshots.

- Jinja: check the variables `{{ variable }}`
- Bash: variables are mixed with equals (line 23-24), string in between backticks (line 18), for loop, etc.

### Screenshot

![Screenshot from 2021-10-14 11-43-42](https://user-images.githubusercontent.com/8699850/137365818-f91ee176-3b30-4c54-a320-5d078b530b1a.png)

![Screenshot from 2021-10-14 11-43-50](https://user-images.githubusercontent.com/8699850/137365890-7c0beb2d-b90f-4425-abf7-0069e5b88154.png)

![Screenshot from 2021-10-14 13-55-41](https://user-images.githubusercontent.com/8699850/137365925-d80a527f-da83-498f-aba1-d24382966d71.png)

![Screenshot from 2021-10-14 13-55-17](https://user-images.githubusercontent.com/8699850/137365941-232f0452-a491-46a4-a860-a5344e85bc0e.png)

### Machine Info

OS: Arch Linux
Vim type: neovim
Version: NVIM v0.5.1
Terminal: Kitty

**Comment by dsifford** [comment]
> Do you think `nvim-treesitter` will help to improve syntax colors?

Yes, very much so.
