### ISSUE TITLE
Provide a direct access to dracula.vim file.

### ISSUE THREAD

**Issue by Narann** [dracula/vim#27]
I just continue the discussion here:

https://github.com/dracula/dracula-theme/issues/207

Please provide a direct access to the `dracula.vim` file:

https://github.com/dracula/vim/blob/master/colors/dracula.vim

I don't know how pathogen or vundle works. I'm still learning vim.

Thanks in advance,

Dorian

**Comment by heinst** [comment]
Add it to where?

**Comment by Narann** [comment]
To this page: https://draculatheme.com/vim/

**Comment by zenorocha** [comment]
Fixed on https://github.com/dracula/dracula.github.io/pull/48.

Thanks for the suggestion @Narann!
