### ISSUE TITLE
The color of variables imported in typescript code is different from vscode

### ISSUE THREAD

**Issue by backtolife2021** [dracula/vim#271]
### What happened
The color of variables imported in typescript code is different from vscode

### What I expected to happen
Same color
### Screenshot
![image](https://user-images.githubusercontent.com/24669431/145169324-9e2d3418-2400-4c10-a7ff-4947cc3b8058.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: neovim
- **Vim version**:  NVIM v0.6.0
- **OS**: Linux arch 5.15.6-arch2-1 # 1 SMP PREEMPT Thu, 02 Dec 2021 15:47:09 +0000 x86_64 GNU/Linux
- **Terminal/Terminal Emulator/VTE**: kitty
- **`TERM` environment variable**: xterm-kitty

**Comment by benknoble** [comment]
This is fairly normal. VsCode uses (AFAIK) tree-sitter for syntax highlighting. Some LSPs can also do highlighting.

Vim has a fairly complex syntax system, and it isn't perfect.

Dracula as a colorscheme does _not_ attempt to improve any of the syntax files.

So, your options are:

- use a system like tree-sitter or LSP for syntax highlighting (NeoVim has tree-sitter; both vim's have LSP plugins);
- install an improved syntax file for typescript (I'm sure some exist)
- live with the difference :)

References: https://github.com/dracula/vim/issues/263, https://github.com/dracula/vim/issues/254, https://github.com/dracula/vim/issues/250, https://github.com/dracula/vim/issues/214, etc
