### ISSUE TITLE
nvim-cmp colors

### ISSUE THREAD

**Issue by caarlos0** [dracula/vim#278]
### What happened

Would be nice to have colors for nvim-cmp components: https://github.com/hrsh7th/nvim-cmp/blob/ba47440a97710d0f4f63eea2bc196fe17297e4ae/doc/cmp.txt#L318-L342

### What I expected to happen

n/a 

### Screenshot

n/a

### Machine Info
n/a

### Additional Info
n/a

**Comment by benknoble** [comment]
Proposals accepted in the form of PRs :)

**Comment by stnley** [comment]
@caarlos0 nvim-cmp highlights were added in #272 and #274. Make sure you are up to date. If there is something missing I'd be happy to add or help with a PR.

**Comment by stnley** [comment]
@caarlos0 are you lazy-loading nvim-cmp by any chance? 

Right now there is a guard to only add the highlights when the plugin is loaded. I was just testing it out and loading cmp on `InsertEnter` the highlights are not added. I am not sure if there is a better check we could do. @yuys13 any ideas?

**Comment by yuys13** [comment]
I'll see if there is a way to determine that nvim-cmp is already installed before loading, like `g:fzf_colors` or `g:ale_enabled`.

**Comment by yuys13** [comment]
Hmmm, I don't have a good idea.
If you are lazy loading nvim-cmp, I suggest running `runtime after/plugin/dracula.vim` after nvim-cmp has finished loading.

**Comment by benknoble** [comment]
This looks a bit stale, so I'll close it.
