### ISSUE TITLE
[advice] change the name of plugin

### ISSUE THREAD

**Issue by Freed-Wu** [dracula/vim#281]
This plugin's name is vim, which is confused, because most of plugin's name is `vim-*` or `*.vim`, like this:

```
Updating plugins (161/168)
[==================================================]

- suda.vim: Updating done.
- tagalong.vim: Updating done.
- targets.vim: Updating done.
- textobj-word-column.vim: Updating done.
- trailguide.vim: Updating done.
- transparency-windows-vim: Updating done.
...
- vim: Updating done. // this plugin
- vim-abolish: Updating done.
- vim-airline: Updating done.
- vim-airline-clock: Updating done.
+ vim-airline-themes: Updating...
- vim-anyfold: Updating done.
- vim-anzu: Updating done.
- vim-asciidoc-folding: Updating done.
```

This plugin's name `vim` is confused, I advice to change it to `vim-dracula` or `dracula.vim`. Thanks.

**Comment by dsifford** [comment]
@Freed-Wu Agree that this is annoying, but it's named this way to follow the convention of the [entire dracula org](https://github.com/dracula) on github. Each theme's name corresponds to the application that the theme is for.

Most plugin installers allow you to rename a plugin though, example being `vim-plugged`...

```
Plug 'dracula/vim', { 'as': 'dracula' }
``` 

..etc

**Comment by Freed-Wu** [comment]
I see. Using plugin manager to rename looks like a remedy.
