### ISSUE TITLE
The bg-color of neovim with dracula theme is not as in their site.

### ISSUE THREAD

**Issue by anukaransubedi** [dracula/vim#286]
<img width="1234" alt="vim" src="https://user-images.githubusercontent.com/107559310/175263716-e6565529-46fe-404e-bf2a-2dd4ce772425.png">

The official site of dracula shows the background colour as above but my background color of neovim is as follows.

![image](https://user-images.githubusercontent.com/107559310/175264042-5568d30d-fbd5-4320-bfc4-b42154388985.png)

how to make my neovim look like shown in the official site of dracula??

My init.vim file:
![image](https://user-images.githubusercontent.com/107559310/175265112-91a2f4bc-2164-4d60-ad9a-382740c90a64.png)

**Comment by benknoble** [comment]
Try `:let g:dracula_colorterm = 1` as in `:help dracula`; that effectively lets your terminal background take precedence by not using a background for vim via the Normal highlight group (IIRC).

**Comment by anukaransubedi** [comment]
where should i do that??

**Comment by benknoble** [comment]
Ah, sorry, should have been 0. And you still need a terminal with the right background color.

Better yet if your terminal supports truecolor; then you'll get unapproximated colors.

**Comment by anukaransubedi** [comment]
Thanks for your help. but i switched to nightfox.
