### ISSUE TITLE
The highlight breaks after the second use of :colorscheme dracula 

### ISSUE THREAD

**Issue by Ddystopia** [dracula/vim#287]
### What happened

My config is loaded, dracula works fine. After second `:colorscheme dracula` colorscheme is changed.

### What I expected to happen

To theme stay the same.

### Screenshot

In python file

Before:

![image](https://user-images.githubusercontent.com/63151578/183501096-27f64eeb-d78d-4cdc-8e7f-91c422759ecf.png)

After:

![image](https://user-images.githubusercontent.com/63151578/183501127-031801e6-e217-4ca7-a6c6-e27f95773c8c.png)

### Machine Info

- **Vim type (`neovim`)**:
- **Vim version**: 0.7.2
![image](https://user-images.githubusercontent.com/63151578/183501316-7f957ef2-f18a-4b61-b736-f15f532833cb.png)

- **OS**: `Linux ddps 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_64 GNU/Linux`
- **Terminal/Terminal Emulator/VTE**: `Terminal Emulator`
- **`TERM` environment variable**: `alacritty`

**Comment by benknoble** [comment]
Generally running `:colorscheme` again can be a bit buggy; usually `:edit` or `:edit!` (make sure to save first) helps.

**Comment by benknoble** [comment]
Closing this unless it didn't solve the problem (comment/re-open).

**Comment by benknoble** [comment]
(also note that in #280 I mentioned that this doesn't happen for me, though I don't use treesitter)
