### ISSUE TITLE
Colors problem

### ISSUE THREAD

**Issue by nemanjan00** [dracula/vim#29]
Hi, guys. 

I spent days trying to fix this and am pulling my hair... 

Any hints? 

I am using urxvt (256 one), neovim and this theme... 

My Vim config: https://github.com/nemanjan00/vim/blob/master/vimrc
My .Xresources: https://gist.github.com/16b0484a0281b873ef3e7bacae3da960

Also, I have set TERM to xterm-256color... 

SS: http://i.imgur.com/bzXmcsN.png

![](http://i.imgur.com/bzXmcsN.png)

**Comment by nemanjan00** [comment]
Seams like it is not drawing parts of background. (at least to me)

**Comment by filipesf** [comment]
Mine looks slightly different as well. Though not that bad.

![screen shot 2017-04-21 at 17 49 24](https://cloud.githubusercontent.com/assets/6840345/25288899/594247d0-26bf-11e7-8476-11397a3c6dd3.png)

My guess is that I'm not using any GUI:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 19 2017 09:57:52)
MacOS X (unix) version
Included patches: 1-567
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
```

Could it be the reason? I'm running Vim straight from iTerm2.

There's any way to enable vim to use GUI colours instead cterm?

In case someone need, here's my vimrc:
https://github.com/filipesf/dotfiles/blob/master/vim/vimrc

**Comment by spoike** [comment]
Updated the colorscheme today via Plug and got the same problem as @nemanjan00. I'm guessing fairly recent breaking change?

**Comment by spoike** [comment]
Seems like this commit breaks it for me: https://github.com/dracula/vim/commit/38d5c9b7335c02b8e3f77f83748103426e176cf9

`ctermbg` is set which causes weird background color artifacts (screenshot provided with cowsay from Startify):

![image](https://cloud.githubusercontent.com/assets/9253/25843364/7191e2f0-34a7-11e7-8509-fe76322a1414.png)

Current hacky workaround for me is to set it to `NONE` after the colorscheme line:

```
colorscheme dracula
highlight Normal ctermbg=NONE
```

**Comment by BourgeoisBear** [comment]
I'm not sure if I had the same problem, but for most terminals I've tried this with under Linux (xfce4-terminal, urxvt), the dracula theme did not work.

This fixed it for me:

Add `set t_Co=256` before `let g:colors_name = 'dracula'` on line 21.

**Comment by dsifford** [comment]
System: Arch Linux
Terminal: urxvt

@spoike's solution of setting `highlight Normal ctermbg=NONE` after `colorscheme` worked for me.

@BourgeoisBear's solution did not.

**Comment by 5t111111** [comment]
I had the same problem and it was solved after setting either @spoike's solution or reverting https://github.com/dracula/vim/commit/38d5c9b7335c02b8e3f77f83748103426e176cf9 .

**Comment by enosair** [comment]
I had the same issue as @filipesf. 
Finally I found that I forgot to enable truecolor support in vim.

Add `set termguicolors` into my vimrc did the trick.

**Comment by nemanjan00** [comment]
Shit. 4 years of using Vim and I did not figure it out until now. :D

**Comment by aktof** [comment]
@enosair Thank you!

**Comment by ferre1** [comment]
> I had the same issue as @filipesf.
> Finally I found that I forgot to enable truecolor support in vim.
> 
> Add `set termguicolors` into my vimrc did the trick.

Спасибо тебе добрый человек, я 2 дня убил на это
