### ISSUE TITLE
Janky Cursorline Highlighting With Treesitter

### ISSUE THREAD

**Issue by hazyboba** [dracula/vim#295]
### What happened
When using `set cursorline` in tandem with Treesitter, the Cursorline highlighting looks janky.
### What I expected to happen
The Cursorline would appear uniform across the whole line.
### Screenshot
what it looks like
![image](https://user-images.githubusercontent.com/79121360/199903067-84268375-6329-4d02-9eb9-1a908e5cdce7.png)
what it should look like
![image](https://user-images.githubusercontent.com/79121360/199903213-22b01f7b-87b5-4bb8-81b7-b2be5c19edda.png)

### Machine Info

- **Vim type**: `neovim (GUI Client)`
- **Vim version**:  `nvim v0.80`
- **OS**: Windows

### Additional Info

This problem does get fixed when setting the colorscheme again.
The second image I provided is the same line but in visual line mode.

Note that visual mode and cursorline highlights are very similar in color. This makes it difficult for the user to determine whether or not they are in visual line selection with cursorline enabled. Perhaps make the visual mode highlight color darker?

**Comment by benknoble** [comment]
Hm, perhaps tree sitter takes precedence over cursorline? I would consider that a tree sitter bug of some sort; syntax highlighting should go "under" UI highlighting.

**Comment by benknoble** [comment]
RE: Visual line, between a mode indicator and the unlikeliness that a single-line selection is useful (a multi-line selection should stand out), I'm not sure anything needs changed. But see the help document for suggestions on tweaking the colorscheme.

**Comment by UnrealApex** [comment]
Ah I see, I will check if there is an issue similar to this filed in the Neovim Treesitter repository

**Comment by UnrealApex** [comment]
See [#3766](https://github.com/nvim-treesitter/nvim-treesitter/issues/3766#issue-1436818585)

**Comment by UnrealApex** [comment]
> Hm, perhaps tree sitter takes precedence over cursorline?

If reloading the colorscheme fixes the highlight then your hypothesis is likely true.

**Comment by UnrealApex** [comment]
@benknoble any update on this?
