### ISSUE TITLE
Colors doesn't look the same of VScode for JS files

### ISSUE THREAD

**Issue by leandrocunha** [dracula/vim#302]
Hi guys,
I started to use Vim with Dracula theme and I would like to ask there is any way to make the syntax highlight (for js/ts files) equal to the VSCode

### Current behavior
![Screenshot 2023-01-04 163207](https://user-images.githubusercontent.com/1820920/210590748-f736f78c-f511-4778-8cec-76aaaa6d6837.png)

### What I expected to happen
![Screenshot 2023-01-04 162421](https://user-images.githubusercontent.com/1820920/210590823-2aa4605c-bb0a-4be2-a7c3-c225c713f1aa.png)

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 9.0
- **OS**: Windows 10 Pro
- **Terminal/Terminal Emulator/VTE**: Windows Terminal

**Comment by benknoble** [comment]
cf. https://github.com/dracula/vim/issues/271 and linked issues.
