### ISSUE TITLE
Would be possible to assign a different color to a nvim :terminal window?

### ISSUE THREAD

**Issue by aisneto** [dracula/vim#308]
I use Nvim to conduct data analysis using a REPL in the form of a :terminal window. I'm curious if it's possible to assign a different background color exclusively to :terminal instances, as a means to differentiate between my code and the console. I believe the [tokyonight](https://github.com/folke/tokyonight.nvim) theme has a setting that allows for such customization.

**Comment by benknoble** [comment]
Away from my computer, but if this is possible you can do it for yourself (without changes on our end) by reading `:help dracula-customization` (assuming I spelled the help tag correctly).

**Comment by aisneto** [comment]
Thank you for the clarification that it was possible to do it on my own (for some reason I though that any aesthetic modifications should be made internally through the colorscheme). After some searching, I've found that these lines do the job:

```
hi TermiBg guibg = #101116
au TermOpen * :set winhighlight=Normal:TermiBg
```
