### ISSUE TITLE
How dracula supports italics for comments

### ISSUE THREAD

**Issue by Elite-zx** [dracula/vim#315]
### What I expected to happen
dracula supports italics for comments
### Machine Info

Linux ELITEZX 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: vim9.0
- **OS**: ubuntu22.04
- **Terminal/Terminal Emulator/VTE**: gnome terminal
- **`TERM` environment variable**: 
❯ echo $TERM
xterm-256color

I used `highlight Comment cterm=italic gui=italic` （from [here](https://stackoverflow.com/a/3494948/19705477)）to make the comment italicized, but this changed the color of the theme
![image](https://github.com/dracula/vim/assets/110723979/47496d9f-7615-4346-8254-c956c4baf25e)
![image](https://github.com/dracula/vim/assets/110723979/65ceb892-9dc8-4791-be96-0096adad6996)

**Comment by benknoble** [comment]
Please see `:help dracula`; I believe you need to make sure you have italics enabled. If that fails, you should customize the groups via autocommands as in the help. 

Taking a quick peek at the colors file, it seems we don't default to italicized comments. We do link `Comment` to `DraculaComment`, so you'll want to modify the latter to make it italic.

**Comment by Elite-zx** [comment]
> Please see `:help dracula`; I believe you need to make sure you have italics enabled. If that fails, you should customize the groups via autocommands as in the help.
> 
> Taking a quick peek at the colors file, it seems we don't default to italicized comments. We do link `Comment` to `DraculaComment`, so you'll want to modify the latter to make it italic.

Thank you!

![image](https://github.com/dracula/vim/assets/110723979/822dfbf2-1728-4424-a4ad-1525b84df9b8)

I enabled the italics now, what autocommands do i need to add ? how can I modify the latter to make it italic ?

**Comment by benknoble** [comment]
Like [the example](https://github.com/dracula/vim/blob/6495b4ff40479ec7705addb4ea800ec308026648/doc/dracula.txt#L117-L120):
```vim
augroup dracula_customization | autocmd!
  autocmd ColorScheme dracula highlight DraculaComment cterm=italic gui=italic
augroup end
```

**Comment by Elite-zx** [comment]
Thank you.  Adding the following 2 lines to .vimrc solved my problem
```vimrc
"italic for comments
highlight DraculaComment cterm=italic gui=italic

```
