### ISSUE TITLE
Lunar Vim Color Scheme Mismatch to Other Editors

### ISSUE THREAD

**Issue by AhmedLilah** [dracula/vim#316]
Hi there,

as mentioned in the title I'm having a problem with the Dracula color scheme on my LunarVim (a Neovim config).

It's not the same on my LunarVim and Visual Studio as it's supposed to look on the repo and my VSCode, Pycharm, and InteliJ Editors.

I'm running LuanrVim on Windows Powershell on Windows Terminal.

**Comment by benknoble** [comment]
Different editors have different theming systems; 100% parity is impossible (_even_ with treesitter, AFAICT). See #302, the linked issue #271, and the issues linked there…
