### ISSUE TITLE
Dracula breaks in floating windows in neovim 0.10.0

### ISSUE THREAD

**Issue by aricursion** [dracula/vim#322]
### What happened
Colorscheme is not applied to floating windows properly.
### What I expected to happen
The dracula colorscheme is applied to floating windows
### Screenshot
Unintended behavior:
![Screenshot_20240603_095513](https://github.com/dracula/vim/assets/32079362/4a45a21f-1ba7-4afe-8039-2e46a7b34cb6)

Intended behavior: (nvim version 0.9.5)

![Screenshot_20240603_095642](https://github.com/dracula/vim/assets/32079362/82ff66f4-a8a1-49af-9efa-d8737f236c0b)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**:
    neovim
- **Vim version**:
    0.10.0
- **OS**:
    Linux zach-arch 6.9.2-arch1-1 # 1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000 x86_64 GNU/Linux
- **Terminal/Terminal Emulator/VTE**:
    Kitty
- **`TERM` environment variable**:
    xterm-kitty

### Additional Info
Colorschemes have been a known issue due to some changes in nvim 0.10.0 the "standard" fix for this is to `:set colorscheme vim` before loading the custom colorscheme. However, this does not fix the behavior.

**Comment by benknoble** [comment]
I know that something in colorschemes has been changed with 0.10.0, but it would be really helpful to know what changed in 0.10.0 to affect the floating or popup windows.

**Comment by benknoble** [comment]
There are a few bits in the [release notes](https://neovim.io/doc/user/news-0.10.html) about Floating highlights, but I don't see any that jump out as part of the problem. Indeed, it seems more like syntax highlighting is not being applied correctly in your screenshot.

**Comment by aricursion** [comment]
Would syntax highlighting effect the background color which is also wrong?

**Comment by benknoble** [comment]
> Would syntax highlighting effect the background color which is also wrong?

I noticed that, and I don't think so. But the other colors, while not correct, are Dracula colors. So that's confusing. What's needed is more information, essentially: I don't know what we need to do differently, and (since I use Vim, not Neovim), I don't personally have the bandwidth to figure it out.
