### ISSUE TITLE
Please change whitespace character color

### ISSUE THREAD

**Issue by kanneg881** [dracula/vim#328]
### What happened

Whitespace character color of pink is too shiny.

### What I expected to happen

Whitespace character color can be comment color

### Screenshot

![image](https://github.com/user-attachments/assets/2f189b8c-a3f2-4362-8de8-0819f2c7e914)

**Comment by kanneg881** [comment]
I think there would be change SpecialKey in `plugged\dracula\colors\dracula.vim`

`hi! link SpecialKey DraculaComment`

**Comment by dsifford** [comment]
The pink color is not the whitespace character (see screenshot) -- Have you possibly overrided this in your configuration?

<img width="420" alt="image" src="https://github.com/user-attachments/assets/a9b65b2d-7841-4094-85f3-8cd75e73f713">

**Comment by benknoble** [comment]
@dsifford I think this differs between NeoVim and Vim; on Vim, to make things like `:map` and `:digraph` readable, we have to make SpecialKey pink. SpecialKey also affects `listchars` on Vim, IIRC.

**Comment by kanneg881** [comment]
@benknoble

You are right, but reading pink whitespace characters is really painful for me. I sacrificed the readability of `:digraph` for now.

![image](https://github.com/user-attachments/assets/e02c8dd3-1e63-49c7-8569-f151dedf4a06)

![image](https://github.com/user-attachments/assets/910be95e-9e9e-482f-8cf6-61b53a00acef)

I haven't found any other way to change the color of whiltespace character.

**Comment by benknoble** [comment]
Yep; separating them has to be done upstream. In the meantime, our help files document how you can do this customization yourself.
