### ISSUE TITLE
How can I install this theme with vim-plug?

### ISSUE THREAD

**Issue by lifeBalance** [dracula/vim#35]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by bengadbois** [comment]
Add to your .vimrc `Plug 'dracula/vim', { 'as': 'dracula' }` and then just `:PlugInstall`

There's an open PR on the website to add this https://github.com/dracula/dracula.github.io/pull/17

**Comment by lifeBalance** [comment]
I tried that and got the error:
```
remote: Not Found                           
fatal: repository 'https://github.com/dracula/vim/blob/master/colors/dracula.vim/'
```

**Comment by dukebarman** [comment]
It works. Try to add in your .vimrc or init.vim
```
...
Plug 'dracula/vim'
call plug#end()

color dracula
```

**Comment by zenorocha** [comment]
@BlakeWilliams can this be closed once https://github.com/dracula/dracula.github.io/pull/17 is merged?

**Comment by BlakeWilliams** [comment]
Yep, once that PR is merged this issue will be resolved.

**Comment by zenorocha** [comment]
Merged ;)
