### ISSUE TITLE
Better whitespaces visualization

### ISSUE THREAD

**Issue by vitornogueira** [dracula/vim#45]
How can I improve the visualization of white spaces? (spaces and tabs)

VIM:
![selection_022](https://user-images.githubusercontent.com/928406/30661672-1eef983e-9e1b-11e7-9a8c-210773018fde.png)

VSCODE:
![selection_023](https://user-images.githubusercontent.com/928406/30661788-6f43553c-9e1b-11e7-86da-2d9cec658181.png)

**Comment by anchnk** [comment]
`:help listchars` might gives you some insights here.

For instance, here is my current set up:

`listchars=eol:$,tab:->,trail:.,extends:>,precedes:<,nbsp:_`

For indentation indicators I believe there's a plugin for that. I don't think vim can do that by itself.

You can change the colors by setting `NonText` to the same color as for your comment for instance.

See `hi NonText`, hope it helps, cheers
