### ISSUE TITLE
Colors in vim-diff 

### ISSUE THREAD

**Issue by DenniJensen** [dracula/vim#50]
With (fugitive)]https://github.com/tpope/vim-fugitive] 
it is possible to browse the git-history in vim. `dracular` does not highlight the deletions (line 23)

![image](https://user-images.githubusercontent.com/3010752/33829482-c3c40008-de70-11e7-95c9-274d5f8e7107.png)

other colorscheme are highlighting the deletions

![image](https://user-images.githubusercontent.com/3010752/33829541-05d871f4-de71-11e7-9818-d95523e568d6.png)

**Comment by benknoble** [comment]
See also #46
