### ISSUE TITLE
theme-dracula can not apply to VIM (with install by Plug)

### ISSUE THREAD

**Issue by cyrilkong** [dracula/vim#51]
![draculavimproblem](https://user-images.githubusercontent.com/334909/34354528-e078bbda-ea69-11e7-9d4c-7c601e6b61be.png)

Please see in the picture, Dracula theme was installed by Plug. (And it was no error at all)

![draculavimproblem2](https://user-images.githubusercontent.com/334909/34354543-faea8aca-ea69-11e7-9007-e8a56dfb7e46.png)

VIM shows the details of .vimrc but you see it comes with no colors (even airline)

**Comment by benknoble** [comment]
I don't use Plug, but I don't have this issue... can you check the output of `:colorscheme` and `:AirlineTheme` ?

**Comment by dsifford** [comment]
@cyrilkong What is the output of `:echo &runtimepath` ?

**Comment by dsifford** [comment]
Haven't heard back on this. I'm not able to reproduce and I use vim-plug. Closing. 

Reopen if the issue persists.

**Comment by vinnyA3** [comment]
Still having an issue with vim-airline
