### ISSUE TITLE
Background color not changed

### ISSUE THREAD

**Issue by cpplucifer** [dracula/vim#54]
OS: Mint 18.2
VIM: 8.0

Text is highlighted well while background color is not changed.

![vimrc](https://user-images.githubusercontent.com/29917069/34771724-92a20d48-f640-11e7-9ccc-a05785e8ed83.png)

**Comment by gdc5p** [comment]
try 

```vimrc
set background=dark
``` 

before 

```vimrc
color dracula
```

**Comment by cpplucifer** [comment]
@gdc5p 
I have tried 
`set background=dark`
`set t_Co=256`
None works.
Now I upgrade my os to mint 18.3 and the problem still exists.

**Comment by gdc5p** [comment]
@cpplucifer 

Now I have no any idea.

Have you tried any other colorscheme ?

**Comment by cpplucifer** [comment]
@gdc5p 
Yeah, I am using PaperColor theme. It works well.

**Comment by tiagoyukio12** [comment]
Dont know if you've tried yet, but `set termguicolors` solved the problem for me.

**Comment by cpplucifer** [comment]
@tiagoyukio12  Wow! That works for me. Thanks!
