### ISSUE TITLE
Tab spaces golang or indents

### ISSUE THREAD

**Issue by magicalbanana** [dracula/vim#55]
Is this expected? If so, how can I change this to be less, bright?

![image](https://user-images.githubusercontent.com/7953984/35479147-4ff3c8ce-03b5-11e8-94ae-8b3e2c1a33d5.png)

**Comment by benknoble** [comment]
- `:help 'list'`
- `:help 'listchars'`

This is not a Dracula issue imo, "voting to close"

**Comment by zenorocha** [comment]
Thanks for reporting @magicalbanana and thanks for checking it @benknoble!
