### ISSUE TITLE
vim background color does not change when installing via colors directory

### ISSUE THREAD

**Issue by pdaniell** [dracula/vim#60]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

I have tried installing the dracula theme into to the colors directory and then setting ```colorscheme``` to dracula in my ```.vimrc.``` Though the colors change for the fonts (i.e. the foreground colors), the background color stays the same. See for example the screenshot. (The background is the standard background for the terminal in Ubuntu). I have typically used the onedark vim theme (https://github.com/joshdick/onedark.vim) which doesn't seem to have this problem (though installing the vim theme there means adding an additional file in the autoload directory). Strangely, I tried this out on my macbook and the same problem happens.

I'm attaching pictures of both the onedark theme and dracula theme. It would be nice to be able to install this without a plugin. 

![dracula](https://user-images.githubusercontent.com/5911713/37498776-1632a628-28b8-11e8-8fef-9c3f3fbe5de5.png)
Above: Dracula without right background

![onedark](https://user-images.githubusercontent.com/5911713/37498780-19ec6196-28b8-11e8-896a-b4a19efcbf4f.png)
Above: Onedark

**Comment by dsifford** [comment]
@pdaniell Can you tell me the following:
- What OS are you running?
- What terminal/terminal emulator/VTE are you running?
- What is the background color of your terminal?

Thanks

**Comment by pdaniell** [comment]
@dsifford 

- I was able to reproduce it on both Mac (10.13.3) and Ubuntu (16.04 LTS -- the 3rd iteration)
- In both cases these were the OS provided apps, each called "Terminal." 
- The background of the terminal in both cases was set to hex 320B28 (this is the default color of the terminal in Ubuntu and I set it to that manually on the Mac).

**Comment by dsifford** [comment]
Noted. Thanks!

Updates to follow...

(If you don't hear back on this by the end of the week, feel free to comment back and remind me)

**Comment by pdaniell** [comment]
Incidentally, I installed vim-plug and tried installing the dracula theme that way and the same problem occurs.

**Comment by pdaniell** [comment]
Aha! I found the problem at least in Ubuntu.  I learned in some other bugs that you have to add some settings in your .vimrc like:

```

" """"""""""""""""""""""""""""""""""""""
" Theme Settings
" """"""""""""""""""""""""""""""""""""""
set termguicolors
color dracula
```

The problem is that the vim installed on 16.04 (which is still the LTS version) is 7.3 --- which does not seem to have any support for the termguicolors directive. So I upgraded vim (some instructions here on how to do that in ubuntu: http://tipsonubuntu.com/2016/09/13/vim-8-0-released-install-ubuntu-16-04/ )
and the background is now working on ubuntu. (My recommendation would be here to include the suggestion about termguicolors on the webpage for dracula and then maybe to warn that this option only works for vim 8+)

However not so much luck with the Mac --- i had vim 8 installed there through homebrew. When I tried the same trick I get the following sort of weird green color theme: 

![screen shot 2018-03-20 at 01 59 13](https://user-images.githubusercontent.com/5911713/37631809-2e818874-2be3-11e8-8183-6436a1424de3.png)

I'll try experimenting some more.

**Comment by dsifford** [comment]
Thanks for the updates.

I think I might know what's going on now after digging through this some more. Gonna be working on a more hardened fix for this over the next several days as time allows.

**Comment by benknoble** [comment]
Could this be connected to #59 ?

**Comment by dsifford** [comment]
@pdaniell Can you pull the update and see if this issue is still happening?

**Comment by pdaniell** [comment]
I am having a little trouble pulling my machines back into the requisite state to test these changes because I ended up installing vim-plug on both my ubuntu and mac as workaround. It seems even with vim-plug, the greenscreen happens on the System terminal so as a workaround i installed iTerm2 --- where it works well. This is a sufficient work around for me. Many thanks.
