### ISSUE TITLE
Permission to come aboard

### ISSUE THREAD

**Issue by dsifford** [dracula/vim#61]
Hi there,

I'm the maintainer of the VSCode Dracula implementation. I'm currently finding myself using actual Vim rather than pseudo-vim a lot more now and, as a consequence of that, I'm now using this theme a whole lot more than usual.

I'm wondering if you guys would be willing to add me in as a maintainer here as well? 

I'm pretty anal when it comes to syntax and highlight groups, so if you all don't really feel like having another person come in and add a bunch of scopes normalize the project as [defined here](https://github.com/dracula/dracula-theme/issues/232) then that's okay too. I'll create a fork and target neovim.

Thanks for considering.

CC @zenorocha

**Comment by zenorocha** [comment]
That would be awesome! You have been doing an amazing job on the VSCode theme and the Vim theme needs that same kind of love. Your help would be very appreciated @dsifford ;)
