### ISSUE TITLE
"source ~/.vimrc" throws errors

### ISSUE THREAD

**Issue by rivyx** [dracula/vim#68]
Hi!

I am finding that upon re-sourcing the vimrc file, a bunch of errors get thrown.

This happens in and out of tmux inside of iTerm2.

![image](https://user-images.githubusercontent.com/16969699/38117707-64d60262-336b-11e8-8379-11d6899e4afd.png)

I've also found that my background color broke, but I see that there is an issue for that already. Anyways, thanks for all of your work on this package, I'm a long-time dracula user and am glad improvements are still going on :).

Thanks!

**Comment by dsifford** [comment]
Aha... Good catch. This is likely related to the second part of #67 

I'll add in a fix for this shortly. :+1:
