### ISSUE TITLE
Word block matches make keywords disappear 

### ISSUE THREAD

**Issue by aalvarado** [dracula/vim#70]
### What happened

This plugin https://github.com/andymass/vim-matchup highlights matches, highlighting matches in the current theme version color is set to `none` for text color, if you jump to a method definition like `def...end` or `if...endif` these keywords will get lost in the background since both will have the same color.

### What I expected to happen
correctly highlight matches.

commenting this line on line 321 sort of fixes it.

```viml
call s:h('MatchParen', s:none, s:pink, [s:attrs.underline])
```

but the color doesn't match the rest of the color scheme.

### Screenshot
![screen shot 2018-04-02 at 4 57 13 pm](https://user-images.githubusercontent.com/370322/38221939-dbc12a7c-3696-11e8-9461-50162ffcbb4b.png)

commenting it:
![screen shot 2018-04-02 at 4 59 24 pm](https://user-images.githubusercontent.com/370322/38221980-2b267c7a-3697-11e8-95f4-779a07c89915.png)

mvim 8.0, OSX.

**Comment by dsifford** [comment]
Neat plugin!

Agree that this should probably be adjusted. Thanks for the report.

**Comment by dsifford** [comment]
@aalvarado Thoughts on this?

![image](https://user-images.githubusercontent.com/5240018/38224525-6a34b68a-36be-11e8-9a0a-22662f189af7.png)

![image](https://user-images.githubusercontent.com/5240018/38224538-77e8c212-36be-11e8-81be-c9687d9eb379.png)

**Comment by aalvarado** [comment]
I really like it!

**Comment by aalvarado** [comment]
thanks for patch, that was really fast!
