### ISSUE TITLE
Turning off highlighting

### ISSUE THREAD

**Issue by chrismitchell** [dracula/vim#81]
### What happened
This is not a bug but more a question and reach out for assistance.

I recently update this plugin and am getting a lot of highlighting which I'd like to disable if I can. 

### What I expected to happen
This may be what is expected to happen but I would like to disable or turn off. 

### Screenshot
<img width="436" alt="screen shot 2018-05-16 at 12 50 02 pm" src="https://user-images.githubusercontent.com/618328/40131605-6e08ed14-5908-11e8-8d0c-01f669e188c3.png">

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: vim 
- **Vim version**: 8.0.180
- **OS**: macOS Sierra
- **Terminal/Terminal Emulator/VTE**: iTerm2
- **`TERM` environment variable**: xterm-256color

**Comment by dsifford** [comment]
Your terminal doesn't support italics which is the reason for the wild background colors.

try adding this to your vimrc before you load the colorscheme:

```vim
let g:dracula_italic = 0
```

**Comment by chrismitchell** [comment]
Perfect thanks @dsifford. I still new to vim and added that but not before the colorscheme was being set 😊
