### ISSUE TITLE
Undercurl should not be forced by color scheme in errors/warnings

### ISSUE THREAD

**Issue by nudzg** [dracula/vim#84]
### What happened

Using w0rp/ale to display errors/warnings I see the indicator on left gutter has an unexpected undercurl. 

### What I expected to happen

Left gutter indicator should not be undercurled.

Setting undercurl seems like is something ale (or equivalent) has to do, not the colorscheme.

If I change:

call s:h('DraculaError', s:red, s:none, [s:attrs.undercurl], s:red)

to:

call s:h('DraculaError', s:red, s:none, [], s:red)

I get what I think is correct.

### Screenshot
![dracula-ale](https://user-images.githubusercontent.com/5119900/40226833-18430668-5a8d-11e8-9cb4-062eeee70f80.png)

Top example is the current and in my opinion wrong behavior. Bottom is what I get with the suggested change.

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: gvim
- **Vim version**: 8.0.1815
- **OS**: Linux xxx 4.16.8-1-ARCH #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018 x86_64 GNU/Linux

**Comment by dsifford** [comment]
We can give your suggestions a shot. Sounds reasonable.
