### ISSUE TITLE
Making background transparent

### ISSUE THREAD

**Issue by SethGower** [dracula/vim#88]
### What happened
The background of my vim is non-transparent. 

### What I expected to happen
I was expecting to see the background behind my terminal, since I have `compton` running. 

### Screenshot
![jun10-14 58 59](https://user-images.githubusercontent.com/19225089/41205300-daa33e24-6cbe-11e8-9267-1f53feae730d.png)

![Screenshot](https://user-images.githubusercontent.com/19225089/41205267-60187d18-6cbe-11e8-8ba0-fe2263225a08.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: neovim
- **Vim version**:
- **OS**: 
`Linux daedalus 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux`
- **Terminal/Terminal Emulator/VTE**: Termite
- **`TERM` environment variable**: `screen-256color`

### Additional Info

The output of `tmux info` can be found [here](https://gist.github.com/SethGower/7d00e91c36e5fb04918d093b807e8764).

**Comment by SethGower** [comment]
Adding `hi Normal guibg=NONE ctermbg=NONE` to my `init.vim` made this work.

**Comment by dsifford** [comment]
Glad you were able to sort it out.

The built-in fix for this should be `let g:dracula_colorterm = 0` as described in `:h dracula`

**Comment by SethGower** [comment]
Ok, I used that, the correct value was `let g:dracula_colorterm = 1`

**Comment by SethGower** [comment]
My `init.vim` is located [here](https://gitlab.com/SethGower/dotfiles/blob/master/.config/nvim/init.vim)

**Comment by SethGower** [comment]
I was able to fix it with the built in fix. the line `let g:dracula_colorterm = 0` must be placed above `colorscheme dracula`. When it is placed below I need to `source init.vim`
