### ISSUE TITLE
Match removes syntax colors

### ISSUE THREAD

**Issue by aalvarado** [dracula/vim#89]
Calling the function for MatchParen when using the plugin Matchup removes all syntax colors in XML like markup:

For example, React code:

![screen shot 2018-06-11 at 11 22 51 am](https://user-images.githubusercontent.com/370322/41249840-19cd6fe2-6d6a-11e8-88e6-4b65bacc2b1e.png)

Using this seems a bit better:
`call s:h('MatchParen', s:none, s:subtle, [s:attrs.underline])`

![screen shot 2018-06-11 at 11 23 31 am](https://user-images.githubusercontent.com/370322/41249864-27067064-6d6a-11e8-997d-2f09440274d3.png)

- mvim
- 8.1
- **OS**: High Sierra
- **Terminal/Terminal Emulator/VTE**: n/a
- **`TERM` environment variable**: n/a

**Comment by aalvarado** [comment]
but might not work well with single parens ... not sure if there's a way to know which is which

**Comment by aalvarado** [comment]
this is prob more for the matchup author... 

ref: https://github.com/andymass/vim-matchup/issues/30

**Comment by andymass** [comment]
FYI- you can now highlight words separately from parens:

    call s:h('MatchWord', s:none, s:subtle, [s:attrs.underline])

Plus there are groups `MatchParenCur` and `MatchWordCur` for the match under the cursor (as opposed to corresponding matches).  By default they are linked to `MatchParen` so it's totally optional.
