### ISSUE TITLE
Bash on Ubuntu on Windows support

### ISSUE THREAD

**Issue by dougfour** [dracula/vim#9]
I Haven't been able to get this to work on Windows 10 new "Bash on Ubuntu on Windows". Was hoping it would work normal, instead the text all turns a bright blue color. All the default color schemes work (eg blue, desert, etc.)

![image](https://cloud.githubusercontent.com/assets/17149475/16510761/228624ba-3f06-11e6-9a36-f27ed43864b8.png)

**Comment by nesl247** [comment]
This happens because Bash on Windows (which is the real name, not Bash on Ubuntu on Windows) only supports the 16 color palette.

**Comment by dougfour** [comment]
You are right. Thanks.
