### ISSUE TITLE
Error is not distinguishable.

### ISSUE THREAD

**Issue by zhou13** [dracula/vim#91]
I found the dracula's error color is not very distinguishable:
![image](https://user-images.githubusercontent.com/576382/41512983-1bd37460-7249-11e8-8c17-b4be9ec68709.png)

In fact, `b // asdf` does not look like an error but a keyword!

On the other hand, default theme and desert clearly marked it:
![image](https://user-images.githubusercontent.com/576382/41513000-711a7d24-7249-11e8-8865-a095165325a1.png)
![image](https://user-images.githubusercontent.com/576382/41513003-7d45704a-7249-11e8-8055-8ffb55f7dc33.png)

Currently I put the workaround `hi! DraculaError gui=inverse` or `hi! DraculaError gui=undercurl`
in my vimrc and I get
![image](https://user-images.githubusercontent.com/576382/41513068-b1394902-724a-11e8-86e6-c2dc1433712e.png)
![image](https://user-images.githubusercontent.com/576382/41513085-0f53a5c8-724b-11e8-8712-2d212cc27098.png)

**Comment by dsifford** [comment]
Are these errors being produced by the syntax, or are you using a language server or linting library?

If the latter, the library should provide the undercurls (see #84)

Regarding the color: That's the dracula-defined error color. We can't stray from it. But as you've alluded, you're more than welcome to modify it in your init scripts.

Re: inverting the color -- Same as above IMHO. I don't think most would want the errors to be that extremely colored, especially those that use aggressive, real-time linters or language servers.

Thoughts @benknoble?

**Comment by zhou13** [comment]
Those error are produce by syntax.  Also I have the same problem with `spell`.  Not sure how can I add underline without touching the highlight theme.

**Comment by dsifford** [comment]
cc @nudzg

**Comment by benknoble** [comment]
@zhou13 `spell` uses `SpellBad` which is linked to `DraculaErrorLine`

**Comment by zhou13** [comment]
I found the reason that the library should provide the undercurls does not make a lot of sense to me because vim syntax marked error as Error. Even for ALE the default setting in dracula is not nice due to the usage of TODO.

Here is how I patch dracula to make both ALE and syntax error look nicer:
```
hi! link Error DraculaErrorLine

hi! link ALEError DraculaErrorLine
hi! link ALEWarning DraculaWarnLine
hi! link ALEInfo DraculaInfoLine

hi! link ALEErrorSign DraculaRed
hi! link ALEWarningSign DraculaOrange
hi! link ALEInfoSign DraculaCyan
```

Before:
![image](https://user-images.githubusercontent.com/576382/41564424-94e45ed2-7307-11e8-9f19-0eac7207bee4.png)

After
![image](https://user-images.githubusercontent.com/576382/41564459-b08cbb2a-7307-11e8-8531-f63a38d0cabb.png)

Hope that is useful.  Feel free to close the issues.

**Comment by dsifford** [comment]
Good tips @zhou13, thanks for taking the time to do that.

I'm indifferent. No strong feelings either way. I'll leave the decision to @benknoble and others.

**Comment by benknoble** [comment]
No reason we can't add the `ALE` patches to `after/plugin` if that's something we want to do; I could go either way.

As for `Error` vs. `ErrorLine`, I'm in favor of something more noticeable. Either `DraculaErrorLine` or `DraculaRedInverse`.

@zhou13 do you want to open a PR covering that?
