### ISSUE TITLE
Background becomes grey

### ISSUE THREAD

**Issue by yzgyyang** [dracula/vim#96]
### What happened
This might be a silly question and it probably is my configuration, but after certain update of dracula, the background becomes grey, and I thought it's not expected.

The screenshot attached is also my .vimrc.

### Screenshot
![image](https://user-images.githubusercontent.com/16748524/42236009-8a4ae2b8-7ec7-11e8-92d0-7456be525592.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: vim
- **Vim version**: 8.1
- **OS**: macOS, FreeBSD, Ubuntu
- **Terminal/Terminal Emulator/VTE**: Multiple
- **`TERM` environment variable**: xterm-256color

**Comment by dsifford** [comment]
You're likely using a terminal that doesn't support 256 colors. 

The BEST solution is to find a better terminal. But the solution I think you're personally looking for is to set the variable `let g:dracula_colorterm = 0` in your init scripts before loading the colorscheme.

Let me know if that helps.

**Comment by dsifford** [comment]
Also, you'll need to set `let g:dracula_italic = 0` to make those blue highlights go away. Your terminal also does not support italic fonts (or you have tmux set up incorrectly and they're not being rendered)

**Comment by yzgyyang** [comment]
Worked like a charm, thank you @dsifford for the solution and explanation. I only knew about `xterm-256color` before and never realized the truecolor and italic settings for multiple terminals like iTerm and gnome-terminal. 

Sorry again for a newbie question!

**Comment by yzgyyang** [comment]
@dsifford As I try to configure my terminal (iTerm2 v3.1.7), I found out that those values are already:

```
➜  ~ echo $TERM
xterm-256color
➜  ~ echo $COLORTERM
truecolor
```

Do you have any insights about what has possibly gone wrong here?

**Comment by yzgyyang** [comment]
> Are you using tmux?
I am not.

**Comment by dsifford** [comment]
Add `set termguicolors` to your vimrc

**Comment by yzgyyang** [comment]
Right on, now it worked.. Thanks again for the help! @dsifford

**Comment by pbnanc** [comment]
> Add `set termguicolors` to your vimrc

That works on xfce-terminal

**Comment by benknoble** [comment]
@pbnanc it asks vim to use GUI-based colors even in the terminal, which can provide "better" color on terminals that support truecolor (I don't have a metric handy for the "better," hence the quotes).

cf. `:help termguicolors`

**Comment by Knowledge-Wisdom-Understanding** [comment]
> You're likely using a terminal that doesn't have truecolor support.
> 
> The BEST solution is to find a better terminal. But the solution I think you're personally looking for is to set the variable `let g:dracula_colorterm = 0` in your init scripts before loading the colorscheme.
> 
> Let me know if that helps.

omg omg this worked hooray!!!!! I'm using ohmyzsh + ohmytmux + amix/vimrc + tilix terminal and nothing seemed to work. but this. this worked. : ) 👍 💯
