### ISSUE TITLE
MacVim: Can't see text under cursor

### ISSUE THREAD

**Issue by nikersify** [dracula/vim#98]
### What happened
The text under cursor was the same color as the cursor.

### What I expected to happen
The text under cursor not to be the same color as the cursor.

### Screenshot
In terminal - as it should be:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/7091471/43359771-d56f5464-92a8-11e8-87f1-3113c5a7d918.png">

In MacVim - as it shouldn't be:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/7091471/43359767-bd60608e-92a8-11e8-9b0b-ab9cefb4035b.png">
### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: MacVim
- **Vim version**: See below
- **OS**: macOS 10.13.6
- **Terminal/Terminal Emulator/VTE**: n/a
- **`TERM` environment variable**: n/a

### Additional Info
<img width="771" alt="image" src="https://user-images.githubusercontent.com/7091471/43359794-63c03e18-92a9-11e8-9ed4-665c970b5959.png">

Let me know if you need any additional information, I'll really appreciate any help! Thanks in advance.

**Comment by benknoble** [comment]
I don't use MacVim, so my cursor color is coming from my terminal.

Can you share the output of `:verbose hi Cursor` ?

**Comment by nikersify** [comment]
Thanks for your reply, sure thing:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/7091471/43364129-909a0912-9314-11e8-9ec0-7946aff5e055.png">

**Comment by benknoble** [comment]
This is rather odd, as `dracula` on it's own doesn't actually mess with `Cursor` as far as I can tell.

These are the only three lines that come close:

```
colors/dracula.vim
240:call s:h('CursorLine', s:none, s:subtle)
243:hi! link CursorColumn DraculaSelection
244:hi! link CursorLineNr DraculaYellow
```

That doesn't mean we *couldn't* support it, just that it's not really `dracula` that's causing the problem. Of course, terminal `vim` doesn't set `Cursor` at all... @dsifford uses `gvim` I think, perhaps he can weigh in?

**Comment by nikersify** [comment]
Got it working, really appreciate your replies guys, the snippet you've linked to @dsifford didn't work though, but thanks for the effort!

It was an issue in my config with `guicorsor` in `.gvimrc`, doing the following fixed it:
```diff
-set guicursor=a:ver100-Cursor
+set guicursor=a:block-Cursor
```

What now seems obvious, cursor `ver100` behaves differently to cursor `block` with regards to coloring.

Thanks again, all best!
