### ISSUE TITLE
I want to know why linenr not background color

### ISSUE THREAD

**Issue by shenchao890216** [dracula/vim#99]
use vim in itrem2 

the official picture like this :
![image](https://user-images.githubusercontent.com/3608667/43825153-9a785816-9b26-11e8-8fe6-78ade7552c34.png)

but my vim :
![image](https://user-images.githubusercontent.com/3608667/43825226-c84eca40-9b26-11e8-8364-848ff54e5389.png)

can i change this? why do like this?

thanks

**Comment by dsifford** [comment]
The official picture in this repo is extremely outdated and no longer accurately reflects the current state of the scheme.

You're free to change the color to whatever you'd like in your vimrc by calling `highlight` on `LineNr` after loading the scheme in your vimrc.
